### ISSUE TITLE
Errors while running autogen.py

### ISSUE THREAD

**Issue by angel-melchor** [keras-team/keras-io#100]
After cloning the repo, installing the requirements and running: `python autogen.py make` I got this error:

> Generating md sources
> ...Processing .
> ...Processing about
> Traceback (most recent call last):
>   File "autogen.py", line 900, in <module>
>     keras_io.make_md_sources()
>   File "autogen.py", line 108, in make_md_sources
>     self.make_md_source_for_entry(self.master, path_stack=[], title_stack=[])
>   File "autogen.py", line 510, in make_md_source_for_entry
>     self.make_md_source_for_entry(entry, path_stack[:], title_stack[:])
>   File "autogen.py", line 441, in make_md_source_for_entry
>     template = template_file.read()
>   File "C:\Users\Angel Melchor\AppData\Local\Programs\Python\Python37\lib\encodings\cp1252.py", line 23, in decode
>     return codecs.charmap_decode(input,self.errors,decoding_table)[0]
> UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 6350: character maps to \<undefined\>

Trying to add an example with `python autogen.py add_example` throws:

> Traceback (most recent call last):
>   File "autogen.py", line 907, in <module>
>     working_dir=get_working_dir(sys.argv[3]) if len(sys.argv) == 4 else None,
>   File "autogen.py", line 233, in add_example
>     tutobooks.py_to_nb(py_path, nb_path, fill_outputs=False)
>   File "C:\Users\Angel Melchor\GitHub\keras-io\scripts\tutobooks.py", line 121, in py_to_nb
>     validate(py)
>   File "C:\Users\Angel Melchor\GitHub\keras-io\scripts\tutobooks.py", line 323, in validate
>     f = open(fpath, "w")
> FileNotFoundError: [Errno 2] No such file or directory: '/tmp/5020644.py'

Working on a fresh python 3.7.7 environment.

**Comment by falaktheoptimist** [comment]
I've had this issue in Windows. It'll take some changes to `autogen.py` and `tutobooks.py` to allow usage on Windows since the `/` separator is hardcoded at a few places. I've made the changes to make it platform agnostic. Will submit it soon.

**Comment by sachinprasadhs** [comment]
Hi @angel-melchor ,

This should work fine now, since the PR https://github.com/keras-team/keras-io/pull/127/files is merged which addressed this issue. 
Please verify and close the issue. Thanks!
