### ISSUE TITLE
Typing Mistake in Documentation of English-to-Spanish translation with a sequence-to-sequence Transformer

### ISSUE THREAD

**Issue by aryan7781** [keras-team/keras-io#1002]
https://github.com/keras-team/keras-io/blob/c300386a5989a99f1508a068e62436083c48797c/examples/nlp/neural_machine_translation_with_transformer.py#L156

## Error
![image](https://user-images.githubusercontent.com/75094180/181175763-112772ff-8f11-43f2-94aa-d0ad347d6690.png)
Here, **encoder_inputs** is the target sentence "so far" is wrong. It should be-
    **decoder_inputs** is the target_sentence "so far".

**Comment by SuryanarayanaY** [comment]
@aryan7781 ,

I agree that it is typo mistake. Will raise a PR to fix this. Thanks!
