### ISSUE TITLE
Error "SystemError: Negative size passed to PyUnicode_New"

### ISSUE THREAD

**Issue by deicool** [keras-team/keras-io#1007]
Hello

I get the following error:
"SystemError: Negative size passed to PyUnicode_New"

when I run the following program:
https://github.com/keras-team/keras-io/blob/master/examples/generative/ddim.py

Please advise.

Thanks.

**Comment by sachinprasadhs** [comment]
Hi, The tutorial has been migarted to Keras 3 and it is working fine now.
Please find the updated example link here https://keras.io/examples/generative/ddim/
