### ISSUE TITLE
process the attached captchas

### ISSUE THREAD

**Issue by MauroLondon** [keras-team/keras-io#1008]
Hello, excellent work. What changes would you have to make to process the attached captchas. I changed the dimensions but it doesn't work for me

![74qxL2](https://user-images.githubusercontent.com/75399405/182003265-b9d4c09f-aaa3-44c1-88de-efc4cad008bd.png)
![7XpDem](https://user-images.githubusercontent.com/75399405/182003268-ad1d81c4-b3c0-42e4-a944-5afc60dbc2f9.png)

**Comment by goodwin64** [comment]
I doubt humans will solve the bottom one 😰

**Comment by pcoet** [comment]
Hi @MauroLondon, thanks for reaching out. The issue backlog is not the best place for support requests. Can you repost this to one of the forums below? That way your question will have more visibility.

* [TensorFlow forum](https://discuss.tensorflow.org/)
* [Keras mailing list](https://groups.google.com/forum/#!forum/keras-users)

Thanks!
