### ISSUE TITLE
Model graph is not rendered in "Timeseries classification from scratch"

### ISSUE THREAD

**Issue by jpodivin** [keras-team/keras-io#1009]
Necessary prerequisites are presumably missing from the container used to render the document.
The error message points in that direction:

> ('Failed to import pydot. You must `pip install pydot` and install graphviz (https://graphviz.gitlab.io/download/), ', 'for `pydotprint` to work.')

https://github.com/keras-team/keras-io/blob/a994cb4d5a3b89de4ff275cf98cf0fbeb5f22a34/examples/timeseries/timeseries_classification_from_scratch.py#L159

**Comment by sachinprasadhs** [comment]
Thanks for reporting the issue. I have created a PR by generating new `.md` file, which should resolve the issue.
