### ISSUE TITLE
Timeseries forecasting with LSTM for weather prediction example contribution

### ISSUE THREAD

**Issue by PrabhanshuAttri** [keras-team/keras-io#102]
I see that 'Timeseries forecasting with LSTM for weather prediction' example if required by the [repository](https://github.com/keras-team/keras-io/blob/master/call_for_contributions.md#timeseries-forecasting-with-lstm-for-weather-prediction)

My team in MLH Fellowship is working on this. Here is the link to the Jupiter notebook: https://github.com/MLH-Fellowship/keras-io/blob/example/timeseries/examples/timeseries/ipynb/timeseries_weather_forecasting.ipynb

I just want to confirm that no one else is not working on this.

Also, as per our understanding, the requirements include a single LSTM layer and nice visualizations. We are still figuring out `timeseries_dataset_from_array` import due to dependency issues.

**Comment by fchollet** [comment]
`timeseries_dataset_from_array` requires tf-nightly or TF 2.3 / higher

Please make a PR to the call for contributions doc to notify others that you're working on this example

**Comment by PrabhanshuAttri** [comment]
Thanks @fchollet 

This week we were able to figure out the imports with tf-nightly. We are doing the cleanup and squashing commits. The latest notebook can be found [here](https://github.com/MLH-Fellowship/keras-io/blob/example/timeseries_dataset_from_array/examples/timeseries/ipynb/timeseries_weather_forecasting.ipynb)

Created a new PR to the call for contributions for work in progress #117

**Comment by sachinprasadhs** [comment]
Hi @PrabhanshuAttri , I see your tutorial **Timeseries forecasting for weather prediction** is already published here https://keras.io/examples/timeseries/timeseries_weather_forecasting/.

Could you please spare some time to close this issue. Thanks!

**Comment by PrabhanshuAttri** [comment]
Thanks for reminder @sachinprasadhs 
Closing the issue.
