### ISSUE TITLE
Adding hands on exercises to keras.io Developer guides (and in future for Code Examples)

### ISSUE THREAD

**Issue by Samarendra109** [keras-team/keras-io#1029]
In general, a new developer getting introduced to keras, used the developer guides to get started with the library. It will be extremely helpful for new comers, if each guide included a hands on exercise section. It will allow the learner to apply the concepts he/she just learnt into an example scenario.
We have (as of now) 16 pages of guides. So adding exercises to each of the guides shouldn't be a difficult task. Later on, probably incrementally, exercises can be added for Code Examples section too.

**Comment by SuryanarayanaY** [comment]
@Samarendra109 ,

Thanks for the request.IMO this  may not add much value as we have Google Colab which is free to all will better serve this purpose.

Anyways Keras-team will review this request and will take a final call on this. Thanks!

**Comment by sachinprasadhs** [comment]
We don't have any plan to support this for now.
Our aim is to help user community about the usage of Keras API with the [guides](https://keras.io/guides/), API usage and to start working on your use case with different APIs together, you can refer to any one of our published [examples](https://keras.io/examples/) from different categories to choose from.
