### ISSUE TITLE
Keras.io lacks an easy way to take ownership of an issue (e.g. contributing an example)

### ISSUE THREAD

**Issue by joshuacwnewton** [keras-team/keras-io#103]
### Issue

Requests for code examples are currently managed by [call_for_contributions.md](https://github.com/keras-team/keras-io/blob/master/call_for_contributions.md). This makes it difficult to indicate when someone is currently working on a contribution, and may result in conflicts.

Issue #102 is also a good example of the need for a fix.

### Proposed solution

It might be helpful to instead create GitHub issues for each of the requested examples. _(Possibly with a unique tag to distinguish them from other issues, which could then be referred to using a link in the Keras.io documentation.)_ That way, people can comment/assign themselves to indicate that they've started working on an example. This would also allow for discussion about implementation details prior to a PR. 

Thanks!

**Comment by fchollet** [comment]
> It might be helpful to instead create GitHub issues for each of the requested examples. (Possibly with a unique tag to distinguish them from other issues, which could then be referred to using a link in the Keras.io documentation.) That way, people can comment/assign themselves to indicate that they've started working on an example. This would also allow for discussion about implementation details prior to a PR.

I would suggest submitting PRs to `call_for_contributions.md` to add information such as: an example is currently being worked on, who is working on it, a link to GitHub issue tracking discussions and progress, etc.

**Comment by joshuacwnewton** [comment]
Thanks for the clarification. :)
