### ISSUE TITLE
where is correct_pad  function?

### ISSUE THREAD

**Issue by mhyeonsoo** [keras-team/keras-io#1054]
Hi, thanks for the great resources.

I've been looking into the mobileViT examples which is https://keras.io/examples/vision/mobilevit/, 
and facing the error that 
```
AttributeError: module 'keras.applications.imagenet_utils' has no attribute 'correct_pad'
```

I googled for this, but couldn't find any information about this.
Can you explain where this function or version comes from? Or can you tell me with which values can I replace this?
Thanks,

**Comment by SuryanarayanaY** [comment]
Hi @mhyeonsoo ,

I have executed the tutorial and its working fine now. Could you please verify the [gist](https://colab.sandbox.google.com/gist/SuryanarayanaY/5a1b0d27e0f99f702e37323a9389935e/kerasio_1054-mobilevit.ipynb) and confirm whether we can mark this as closed now.

Thanks!

**Comment by mikechen66** [comment]
It seems that keras.applications is deprecated in the year of 2022.  And it is achived. 

For both keras and tensorflow.keras, there is no correct_pad in the imagenet_utils script.

**Comment by SuryanarayanaY** [comment]
@mhyeonsoo , @mikechen66 ,

The correct import is `from keras.src.applications import imagenet_utils` from TF2.13v onwards. Raised a PR #1546 for this already.

Please check the above import and let us know if it resolved.
