### ISSUE TITLE
RetinaNet ValueError: Dimensions must be equal

### ISSUE THREAD

**Issue by satpalsr** [keras-team/keras-io#1062]
While running [RetinaNet object detection model with KerasCV](https://twitter.com/fchollet/status/1568273735769272321)
```
ValueError                                Traceback (most recent call last)
[<ipython-input-24-f1ccc1110a56>](https://localhost:8080/#) in <module>
      3     validation_data=val_ds,
      4     epochs=EPOCHS,
----> 5     callbacks=callbacks,
      6 )
      7 model.save_weights(CHECKPOINT_PATH)

2 frames
[/usr/local/lib/python3.7/dist-packages/keras/engine/training.py](https://localhost:8080/#) in tf__train_function(iterator)
     13                 try:
     14                     do_return = True
---> 15                     retval_ = ag__.converted_call(ag__.ld(step_function), (ag__.ld(self), ag__.ld(iterator)), None, fscope)
     16                 except:
     17                     do_return = False

ValueError: in user code:

    File "/usr/local/lib/python3.7/dist-packages/keras/engine/training.py", line 1160, in train_function  *
        return step_function(self, iterator)
    File "/usr/local/lib/python3.7/dist-packages/keras/engine/training.py", line 1146, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "/usr/local/lib/python3.7/dist-packages/keras/engine/training.py", line 1135, in run_step  **
        outputs = model.train_step(data)
    File "/usr/local/lib/python3.7/dist-packages/keras_cv/models/object_detection/retina_net/retina_net.py", line 354, in train_step
        loss = self._backward(y_training_target, y_pred)
    File "/usr/local/lib/python3.7/dist-packages/keras_cv/models/object_detection/retina_net/retina_net.py", line 335, in _backward
        y_pred,
    File "/usr/local/lib/python3.7/dist-packages/keras_cv/models/object_detection/retina_net/retina_net.py", line 317, in compute_losses
        tf.equal(ignore_mask, 1.0), 0.0, classification_loss

    ValueError: Dimensions must be equal, but are 49104 and 20 for '{{node SelectV2}} = SelectV2[T=DT_FLOAT](Equal_1, SelectV2/t, FocalLoss/weighted_loss/Mul)' with input shapes: [?,49104], [], [?,49104,20].
    ```

**Comment by innat** [comment]
@doncarlos999 @satpalsr 

> ValueError: Dimensions must be equal, but are 49104 and 20 for '{{node SelectV2}} = SelectV2[T=DT_FLOAT](Equal_1, SelectV2/t, FocalLoss/weighted_loss/Mul)' with input shapes: [?,49104], [], [?,49104,20].

The issue may be more close to colab environment. I tested the code on GCP with TF 2.9.2, the model run successfully.

**Comment by doncarlos999** [comment]
Thanks for the suggestion @innat but I just tried on colab with TF==2.9.2 and I get the same error. It must be another package causing the problem.

**Comment by innat** [comment]
As mentioned, this main issue is more related to colab env. Even if TF 2.9.1+ is installed, there may be other depencides which causing such conflict. I think it's better to create vm locally with necessary packages to run this model at the moment until colab gets upgrade.

**Comment by doncarlos999** [comment]
Fair point @innat  and I could do that but the authors have a run in colab badge on the tutorial webpage so I would expect it to work there too.

**Comment by innat** [comment]
I'm using notebook-api. Here is the [req.txt](https://drive.google.com/file/d/1uuJq-k-EKb5_ru44X1zOKhKyD1y2JOSE/view?usp=sharing) file. Please note, there are many unnecessary packags inside the .txt which you may not needed at all.

<img src="https://user-images.githubusercontent.com/17668390/190965371-2317744b-0f26-4dc5-b2b4-4aa7dada4fd4.png"  width="700" height="300">

And here is the tf and cuda version this gcp instance provided.

```yaml
TF System Cuda V.  :  11.2
TF System CudNN V. :  8
```

**Comment by innat** [comment]
cc. @LukeWood

**Comment by innat** [comment]
@doncarlos999 
I've sucessfully run retinanet on colab by installing following at the beginning. First install TF (<=2.9.1) and restart the runtime. Next, install keras-cv and the following packages. Rest of the code should run flawlessly.

```
pip install tensorflow==2.9.1
```

Restart may or may not required.

```bash
!pip install git+https://github.com/keras-team/keras-cv.git
!apt install --allow-change-held-packages libcudnn8=8.1.0.77-1+cuda11.2
```

**Comment by doncarlos999** [comment]
@innat this works perfectly thank you very much.

**Comment by LukeWood** [comment]
Thanks for the bug report!  Hopefully as Colab gets newer TF versions this will work out of the box.
