### ISSUE TITLE
[macOS] Washed-out, dark gray squares

### ISSUE THREAD

**Issue by akaalias** [keras-team/keras-io#1095]
I'm on an M1 Macbook Air and installed Tensorflow via https://developer.apple.com/metal/tensorflow-plugin/. 

When running the demo code, all I get are three generated, washed-out, dark gray squares. 

For any prompt. 

<img width="584" alt="Screenshot 2022-09-28 at 16 39 19" src="https://user-images.githubusercontent.com/111555/192808658-1a905234-6234-40d9-b8c6-1a760deef503.png">

Anyone else seeing this?

- macOS 13.0 Beta
- Python 3.10.6
- pip 22.2.2
- tensorflow-macos 2.10.0
- keras-cv 0.3.3

**Comment by cybergeekgyan** [comment]
Did you try the latest macOS along with the latest tf version, Are you still facing the issue?
@akaalias

**Comment by sachinprasadhs** [comment]
Hi, 

Thanks for reporting the issue.

Now, you can install Tensorflow on Mac M1 directly using pip. 
Could you please try installing the latest version and let us know if you are still facing an issue.
`pip install tensorflow==2.13.0`
