### ISSUE TITLE
Code examples sorted by and listed with date.

### ISSUE THREAD

**Issue by jacoverster** [keras-team/keras-io#1107]
A suggestion to add dates to code example titles and sort them by latest addition. This will be helpful for new visitors to see which examples are recent, or for frequent visitors to see new additions.

If this will add value I'd be happy to submit a pull request.

Example of proposed change:

![image](https://user-images.githubusercontent.com/22006760/194487449-84282a85-6606-46a4-8f10-a0942c451ef2.png)

**Comment by jacoverster** [comment]
Hi @fchollet, any comments on this suggestion?

**Comment by sachinprasadhs** [comment]
Hi, 

Thanks for opening the issue.

We don't sort examples based on the dates it was added, we basically split all the code examples into multiple categories like `Computer Vision`, `Natural Language Processing` etc. 
Again under these section, we have sub categories like `Image Classification`, `OCR`, `Image Segmentation` etc.
Under these sub category the order of code examples listed is prioritized with **★= Good starter example** and then followed by the significance of the training documents.

Refer to the code example list here https://keras.io/examples/

**Comment by jacoverster** [comment]
Ok, no problem, feel free to close the issue.
