### ISSUE TITLE
Gradio Demos for docs

### ISSUE THREAD

**Issue by brendenconnors** [keras-team/keras-io#1110]
Hello! I have currently been looking at developing Gradio demos that could be embedded with documentation to give the user something to play with as they are trying to understand docs. My first example was for the Keras Reshape layers which can be seen here https://huggingface.co/spaces/brendenc/Keras-Reshape-Layers . 

I am curious if you guys have any input on whether you believe this is something beneficial for documentation, or just makes them cluttered (I am not sure what I think quite yet).

**Comment by hertschuh** [comment]
Hi @brendenconnors ,

While it works well for the reshape layer, I think that for a lot of the layers, it is difficult to try them out in isolation. So we've been focusing on examples and guides that use these layers in the context of a model.

Thanks for the suggestion though!
Fabien
