### ISSUE TITLE
Problems with the image classification example

### ISSUE THREAD

**Issue by pgg3** [keras-team/keras-io#1119]
According to the code, x is activated twice when input into the residual block right?
![Screenshot 2022-10-19 114157](https://user-images.githubusercontent.com/34126221/196592551-98ea4ecf-b6bf-475b-b9ba-4ef5d7a2ac3c.png)

**Comment by SuryanarayanaY** [comment]
Hi @pgg3 ,

Referring to the [comment](https://github.com/keras-team/keras-io/pull/1418#issuecomment-1644643758) in the attached PR, the changes requested not approved.You may have a look into the PR and comments there.

The additional layer with relu activation will not anyway affect the output but only increases one layer. Hence this is not a bug anyway. Shall we close the issue now?

**Comment by pgg3** [comment]
Fine with me
