### ISSUE TITLE
Improve next-frame prediction with ConvLSTM contribution

### ISSUE THREAD

**Issue by ktakattack** [keras-team/keras-io#112]
I'm just started working on "Improve next-frame prediction with ConvLSTM" contribution. (https://github.com/keras-team/keras-io/blob/master/call_for_contributions.md#improve-next-frame-prediction-with-convlstm)

Please let me know if anyone else is working on this. Thanks!

**Comment by fchollet** [comment]
Sounds good, please make a PR to say so in the call to examples doc. You can also add a link to this issue to track progress

**Comment by ddaskan** [comment]
Hey @ktakattack , are you still working on this? Sorry if I miss, I can't see any PR or links to address to your work.

**Comment by ktakattack** [comment]
> Hey @ktakattack , are you still working on this? Sorry if I miss, I can't see any PR or links to address to your work.

Yes, I'm currently working on it. Forgot to submit the PR.

**Comment by fchollet** [comment]
Is there any update on this? Your name is still associated with the outstanding work item.

**Comment by sachinprasadhs** [comment]
Hi,

Could you please refer the below published tutorial on **Next-Frame Video Prediction with Convolutional LSTMs** and close this issue. Thanks!

https://keras.io/examples/vision/conv_lstm/
