### ISSUE TITLE
Keras reproducibility recipes

### ISSUE THREAD

**Issue by merveenoyan** [keras-team/keras-io#1120]
I wanted to ask what you expect from `Keras reproducibility recipes` in your [call for contributions](https://github.com/keras-team/keras-io/blob/master/call_for_contributions.md)? I'm willing to contribute but wanted to align on the expectations.

**Comment by sayakpaul** [comment]
@fchollet to comment more. Happy to collaborate.

**Comment by jbischof** [comment]
@merveenoyan sorry we missed this thread! Will follow up with @fchollet

**Comment by sachinprasadhs** [comment]
@merveenoyan , We don't update the call for contributions now, if you feel any example needs to be added to Keras which is not part of it, feel free to create a PR, team would be happy to review it.
Please go through the contributing guidelines before starting https://github.com/keras-team/keras-io/blob/master/contributor_guide.md
