### ISSUE TITLE
wide_deep_cross_networks

### ISSUE THREAD

**Issue by ywc1026** [keras-team/keras-io#1127]
I think the key point of wide network is the crossing of category features but it's not reflected in this code.
https://github.com/keras-team/keras-io/blob/master/examples/structured_data/wide_deep_cross_networks.py

Maybe the CategoryCrossing method can achieve it.

**Comment by sachinprasadhs** [comment]
Are you referring to feature crossing, which is mentioned here https://github.com/keras-team/keras-io/blob/master/examples/structured_data/wide_deep_cross_networks.py#L390
