### ISSUE TITLE
INVALID_ARGUMENT:  required broadcastable shapes in Classification Loss

### ISSUE THREAD

**Issue by nikeshdevkota** [keras-team/keras-io#1131]
Hi, I am trying to run RetinaNet on a custom dataset. To generate the dataset, I am using tf.data.Dataset.from_generator().

During model training, I run into  INVALID_ARGUMENT:  required broadcastable shapes while calculating classification loss and I can't seem to find any solution on the internet. I would appreciate it if I could get directions on how to solve this problem. I have uploaded the full error shown during model training below.
![Custom Generator](https://user-images.githubusercontent.com/45029614/199945452-e0ecb151-9df0-4da4-a802-474e3901b82b.PNG)

I had made some changes in the code and the deviations from the original code are as follows: 
1. For the custom generator, data_list is a list containing multiple dictionaries in the format [{"image":image,"image/filename":filenames, "objects": {"bbox":bbox,"label":labels}}] is passed to the tf.data.Dataset.from_generator() function.
2. The custom dataset has only 3 classes in total.
3. I have changed the area, aspect_ratio, and scale to fit my dataset.
4.  I haven't used horizontal flip as I don't want to flip the image.
5. I want to have my shorter side of the image to be 256 pixels, so I have changed the min_side to 256 in the "resize_and_pad_image" function. However, I don't understand the function of stride, so I would appreciate it if I could get some explanation of it.
6. I checked the maximum IOU returned for a limited sample of the dataset. Based on the limited data, on average, I was getting a maximum IOU of greater than 0.5 on 90% of the data.

![Resize and Pad](https://user-images.githubusercontent.com/45029614/199948774-d0fa7607-1095-4313-b3b6-77a7ecd294b0.PNG)
![Full_Error](https://user-images.githubusercontent.com/45029614/199949348-1d7f0a1d-d11d-4327-8160-e9065b08414e.PNG)
![Full_Error_1](https://user-images.githubusercontent.com/45029614/199949354-bbb2f069-2428-454d-b462-c967df56860e.PNG)
![Full_Error_2](https://user-images.githubusercontent.com/45029614/199949357-ee7aea9f-c5c2-4bc7-8eaf-0e02ecd0d70f.PNG)
![Full_Error_3](https://user-images.githubusercontent.com/45029614/199949360-2f92b931-6749-4ee7-a166-179fd04e878d.PNG)
@srihari-humbarwadi

**Comment by sachinprasadhs** [comment]
Could you please provide some sample reproducible code. Thanks
