### ISSUE TITLE
ValueError

### ISSUE THREAD

**Issue by johngriffin10** [keras-team/keras-io#1132]
ValueError: Can't convert non-rectangular Python sequence to Tensor.

I copied and pasted the code but got this error. 
TF version: 2.10.0

**Comment by SuryanarayanaY** [comment]
Hi @johngriffin10 ,

If you are trying to convert a Ragged list to a TF tensor then this error will happen.I am assuming you are using some `ragged_list` to convert into Tensor using tf.constant(ragged_list) which can raise this error. Instead use `tf.ragged.constant(ragged_list)` that can convert `ragged_list` into a `ragged_tensor`.

I am also attaching a [gist](https://colab.research.google.com/gist/SuryanarayanaY/c9a2a089eab4c618592e8f3b9c28f708/kerasio_1132.ipynb) for demo that causes the reported error and the solution mentioned above works for this case.

In case you are getting the error for different code please let us know. Thanks!
