### ISSUE TITLE
NotImplementedError in examples/generative/vae.py

### ISSUE THREAD

**Issue by wilhelmbraun** [keras-team/keras-io#114]
Dear all,

when running the script `examples/generative/vae.py` without any changes, I get this error message

`    raise NotImplementedError('When subclassing the `Model` class, you should'
NotImplementedError: When subclassing the `Model` class, you should implement a `call` method. `

I have python3.6.9 and tensorflow-gpu 1.12.0, but I think this might be a general problem with this script.

Thanks a lot for your answers.

Best,

Wilhelm

**Comment by fchollet** [comment]
You need TF 2.2 or higher

**Comment by wilhelmbraun** [comment]
Thanks, the error has disappeared after installing the latest stable TF version as described [here](https://www.tensorflow.org/install/pip).

**Comment by lefnire** [comment]
Also getting this error running in TF 2.3
