### ISSUE TITLE
AttributeError: 'AdamW' object has no attribute '_set_hyper'

### ISSUE THREAD

**Issue by t0uxe** [keras-team/keras-io#1142]
Hi,

I've just copied and pasted this sample:
examples/vision/object_detection_using_vision_transformer.py

I' running it on JupyterLab.
Python version: 3.10.8
tensorflow-addons             0.18.0
tensorflow                    2.11.0

When I've runned it, everything ok, until it's has arrived to "Run the experiment" section, where I get this error:

`AttributeError: 'AdamW' object has no attribute '_set_hyper'`

Here the full error:

`
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In [1], line 379
    367 vit_object_detector = create_vit_object_detector(
    368     input_shape,
    369     patch_size,
   (...)
    375     mlp_head_units,
    376 )
    378 # Train model
--> 379 history = run_experiment(
    380     vit_object_detector, learning_rate, weight_decay, batch_size, num_epochs
    381 )
    384 """
    385 ## Evaluate the model
    386 """
    388 import matplotlib.patches as patches

Cell In [1], line 317, in run_experiment(model, learning_rate, weight_decay, batch_size, num_epochs)
    315 def run_experiment(model, learning_rate, weight_decay, batch_size, num_epochs):
--> 317     optimizer = tfa.optimizers.AdamW(
    318         learning_rate=learning_rate, weight_decay=weight_decay
    319     )
    321     # Compile model.
    322     model.compile(optimizer=optimizer, loss=keras.losses.MeanSquaredError())

File ~/.local/lib/python3.10/site-packages/typeguard/__init__.py:1033, in typechecked.<locals>.wrapper(*args, **kwargs)
   1031 memo = _CallMemo(python_func, _localns, args=args, kwargs=kwargs)
   1032 check_argument_types(memo)
-> 1033 retval = func(*args, **kwargs)
   1034 try:
   1035     check_return_type(retval, memo)

File ~/.local/lib/python3.10/site-packages/tensorflow_addons/optimizers/weight_decay_optimizers.py:525, in AdamW.__init__(self, weight_decay, learning_rate, beta_1, beta_2, epsilon, amsgrad, name, **kwargs)
    483 @typechecked
    484 def __init__(
    485     self,
   (...)
    493     **kwargs,
    494 ):
    495     """Construct a new AdamW optimizer.
    496 
    497     For further information see the documentation of the Adam Optimizer.
   (...)
    523             variables excluded from weight decay.
    524     """
--> 525     super().__init__(
    526         weight_decay,
    527         learning_rate=learning_rate,
    528         beta_1=beta_1,
    529         beta_2=beta_2,
    530         epsilon=epsilon,
    531         amsgrad=amsgrad,
    532         name=name,
    533         **kwargs,
    534     )

File ~/.local/lib/python3.10/site-packages/typeguard/__init__.py:1033, in typechecked.<locals>.wrapper(*args, **kwargs)
   1031 memo = _CallMemo(python_func, _localns, args=args, kwargs=kwargs)
   1032 check_argument_types(memo)
-> 1033 retval = func(*args, **kwargs)
   1034 try:
   1035     check_return_type(retval, memo)

File ~/.local/lib/python3.10/site-packages/tensorflow_addons/optimizers/weight_decay_optimizers.py:99, in DecoupledWeightDecayExtension.__init__(self, weight_decay, exclude_from_weight_decay, **kwargs)
     97 super().__init__(**kwargs)
     98 self._decay_var_list = None  # is set in minimize or apply_gradients
---> 99 self._set_hyper("weight_decay", wd)
    100 self.exclude_from_weight_decay = exclude_from_weight_decay

AttributeError: 'AdamW' object has no attribute '_set_hyper'
`

**Comment by tienenCUHK** [comment]
same problem , have you fixed it?

**Comment by dannyel2511** [comment]
I'm having the same issue with NovoGrad, error is `'NovoGrad' object has no attribute '_set_hyper'`. I'm also using TF 2.11

**Comment by alalio** [comment]
Hi, i had the same error after updating to TF 2.11. 
I've fixed it by replacing tfa.optimizers.AdamW with tf.keras.optimizers.experimental.AdamW

**Comment by amarseg** [comment]
I'm having the same issue with AdaBelief, using TF 2.11

**Comment by SuryanarayanaY** [comment]
Hi @t0uxe ,

I have tested the mentioned tutorial with TF 2.12V on colab and its working fine.Please refer attached [gist](https://colab.research.google.com/gist/SuryanarayanaY/fcbe8927b77706352698e197d3c03d4f/-examples-vision-object_detection_using_vision_transformer.ipynb).

I even tested with TF2.11 version and its working fine. May be you can try with latest version of tensorflow_addons using.   `!pip install tensorflow_addons` and it should work fine.

Could you please test as above and confirm the results.

Thanks!

**Comment by lirui03** [comment]
You can do this to solve:
opt = tfa.optimizers.AdamW(lr, weight_decay)

**Comment by neel26desai** [comment]
Tried doing . !pip install tensorflow_addons, still no luck.
