### ISSUE TITLE
Links not working in "High-performance image generation using Stable Diffusion in KerasCV"

### ISSUE THREAD

**Issue by AdityaKane2001** [keras-team/keras-io#1145]
In the aforementioned [tutorial](https://keras.io/guides/keras_cv/generate_images_with_stable_diffusion/), the links point to an older version of the files, resulting in an 404.

**Comment by cybergeekgyan** [comment]
I would like to work on this issue and solve the link not working problem by fixing @AdityaKane2001

**Comment by cybergeekgyan** [comment]
Sure @AdityaKane2001

**Comment by ADITYADAS1999** [comment]
hey [AdityaKane2001](https://github.com/AdityaKane2001) can you share the broken link page, because all the links of KerasCV are working perfectly.

**Comment by ADITYADAS1999** [comment]
> ![image](https://user-images.githubusercontent.com/64411306/208696084-33c8d2a2-3cef-4aee-89da-2ca4b3aceb11.png)
> 
> These links are not working.

thnaks for sharing [AdityaKane2001](https://github.com/AdityaKane2001)

**Comment by SuryanarayanaY** [comment]
Hi @AdityaKane2001 ,

I have cross checked now and all the reported links are working fine as it was fixed in [#1162 ](https://github.com/keras-team/keras-io/pull/1162). Could you please cross check and confirm whether we are good to close this issue.

Thanks!

**Comment by AdityaKane2001** [comment]
Solved in #1162, closing.
