### ISSUE TITLE
ocr error 

### ISSUE THREAD

**Issue by xor256** [keras-team/keras-io#1153]
// https://raw.githubusercontent.com/keras-team/keras-io/master/examples/vision/captcha_ocr.py //
python captcha_ocr.py 
Number of images found:  1040
Number of labels found:  1040
Number of unique characters:  19
Characters present:  ['2', '3', '4', '5', '6', '7', '8', 'b', 'c', 'd', 'e', 'f', 'g', 'm', 'n', 'p', 'w', 'x', 'y']
Traceback (most recent call last):
  File "captcha_ocr.py", line 98, in <module>
    char_to_num = layers.StringLookup(vocabulary=list(characters), mask_token=None)
AttributeError: module 'tensorflow.keras.layers' has no attribute 'StringLookup'

**Comment by ADITYADAS1999** [comment]
> // https://raw.githubusercontent.com/keras-team/keras-io/master/examples/vision/captcha_ocr.py // python captcha_ocr.py Number of images found: 1040 Number of labels found: 1040 Number of unique characters: 19 Characters present: ['2', '3', '4', '5', '6', '7', '8', 'b', 'c', 'd', 'e', 'f', 'g', 'm', 'n', 'p', 'w', 'x', 'y'] Traceback (most recent call last): File "captcha_ocr.py", line 98, in char_to_num = layers.StringLookup(vocabulary=list(characters), mask_token=None) AttributeError: module 'tensorflow.keras.layers' has no attribute 'StringLookup'

I work on it

**Comment by ADITYADAS1999** [comment]
> // https://raw.githubusercontent.com/keras-team/keras-io/master/examples/vision/captcha_ocr.py // python captcha_ocr.py Number of images found: 1040 Number of labels found: 1040 Number of unique characters: 19 Characters present: ['2', '3', '4', '5', '6', '7', '8', 'b', 'c', 'd', 'e', 'f', 'g', 'm', 'n', 'p', 'w', 'x', 'y'] Traceback (most recent call last): File "captcha_ocr.py", line 98, in char_to_num = layers.StringLookup(vocabulary=list(characters), mask_token=None) AttributeError: module 'tensorflow.keras.layers' has no attribute 'StringLookup'

I work on it

**Comment by ADITYADAS1999** [comment]
It is working fine for me

![451278](https://user-images.githubusercontent.com/58718316/208310405-5a0b32c6-44f2-4c23-8549-0d0f09d17788.PNG)

**Comment by sachinprasadhs** [comment]
I was able to run the code successfully without any issues using Tensorflow 2.13.
Could you please upgrade your Tensorflow/Keras to the latest version and try again.
Attaching the working Gist for reference: https://gist.github.com/sachinprasadhs/7881a34866ac90880be5a9fef0d0bf84
