### ISSUE TITLE
Rendering bug with lists in an argument docstring

### ISSUE THREAD

**Issue by mattdangerw** [keras-team/keras-io#1156]
We have a few places on in our API documentation where our arguments contain a sublists of possible values. This currently does not render well on keras.io, but does render properly on tf.org.

![image](https://user-images.githubusercontent.com/1389937/207431612-b60f7d22-8b36-4428-a1a8-c284e8c48393.png)

We would like the bullets within `output_mode` to render as a nested list, not smushed into a single continuous paragraph.

**Comment by ADITYADAS1999** [comment]
hey [mattdangerw](https://github.com/mattdangerw) this issue is still open ?
Can you share the source file of this docs.

**Comment by mattdangerw** [comment]
> I found the source file. can I made the changes and try to a PR?

You are very welcome to help out with this! If possible we would like the change to happening in the rendering code in this repo, and not the source docstring itself. Tensorflow.org, for examples, already renders this block correctly -- https://www.tensorflow.org/api_docs/python/tf/keras/layers/StringLookup.

**Comment by sachinprasadhs** [comment]
The issue is fixed, I can see the sub list under the argument as below.

![image](https://github.com/keras-team/keras-io/assets/73069040/432d61cc-0b79-445b-a07a-362b6b666eb0)
