### ISSUE TITLE
Adding example of style-gan/style-gan2

### ISSUE THREAD

**Issue by prakharcode** [keras-team/keras-io#116]
Can I claim the opened style-gan example addition? Will start working on that.

**Comment by fchollet** [comment]
Sounds good, please make a PR to say so in the call to examples doc

**Comment by sachinprasadhs** [comment]
Hi, Could you please update on this request.

Also, could you please take a look into the below StleGAN based examples published, Thanks!
https://keras.io/search.html?query=StyleGan
