### ISSUE TITLE
[Examples] Potential typo in MIRNet example

### ISSUE THREAD

**Issue by miykael** [keras-team/keras-io#1160]
Hello @soumik12345, thank you for the great MIRNet example!

While working on an adaptation of your model I saw that the variable `level2_dau_2` in [line 347](https://github.com/keras-team/keras-io/blob/b56f87af9e968003666e61f88185a93ff0f0eee8/examples/vision/mirnet.py#L347) is never used in the code. Could it be that there's a typo in [line 352](https://github.com/keras-team/keras-io/blob/b56f87af9e968003666e61f88185a93ff0f0eee8/examples/vision/mirnet.py#L352) and that it should be `level2_dau_2` instead of `level3_dau_2`?

```diff
-      skff_ = selective_kernel_feature_fusion(level1_dau_2, level3_dau_2, level3_dau_2)
+      skff_ = selective_kernel_feature_fusion(level1_dau_2, level2_dau_2, level3_dau_2)
```

**Comment by cybergeekgyan** [comment]
I would like to work on this issue to sort this and close the issue .. Can you assign this to me and specify a bit more on what needs to be changed

**Comment by miykael** [comment]
Sure, feel free to take this over. Nothing to assign yet, as no PR was issued yet. And the only thing that needs to be changed, assuming that this is a typo, is the line indicated in my initial statement.

**Comment by SuryanarayanaY** [comment]
Hi @miykael ,

The proposed PR has been merged with master branch and now i can see the changes. Please refer the code in master branch attached below and if satisfied please feel free to close the issue.

https://github.com/keras-team/keras-io/blob/8f49b3ec63c7d959b9457ab7cc961ce4ca922d2f/examples/vision/mirnet.py#L353

Thanks!
