### ISSUE TITLE
Finetune stable diffusion with keras-cv, thanks

### ISSUE THREAD

**Issue by junyongyou** [keras-team/keras-io#1167]
Is it possible to finetune the keras-cv implementation of stable diffusion? Thanks a lot.

**Comment by tanzhenyu** [comment]
We should make it inherit from `keras.Model` or `tf.Module` before enabling this

**Comment by sayakpaul** [comment]
Just landed a PR for this: #1176

**Comment by geocine** [comment]
Looking forward to this. Is there a way to convert Diffusers model to Keras right now?

**Comment by sachinprasadhs** [comment]
Hi @junyongyou ,

Could you please refer the tutorial `Fine-tuning Stable Diffusion` published here https://keras.io/examples/generative/finetune_stable_diffusion/ 
Feel free to close this issue.

**Comment by junyongyou** [comment]
Great, thanks a lot.
