### ISSUE TITLE
"Image classification from scratch" example has warnings and training runs incredibly slow

### ISSUE THREAD

**Issue by EZeroDivide** [keras-team/keras-io#1174]
Tensorflow 2.11, Anaconda 2.3.1, Windows 10
[Image classification from scratch](https://keras.io/examples/vision/image_classification_from_scratch/)

Training is incredibly slow. After 8 hours the first epoch was still running (125/147).

Following warnings appear when executing this instruction:

augmented_train_ds = train_ds.map(
    lambda x, y: (data_augmentation(x, training=True), y))

WARNING:tensorflow:Using a while_loop for converting RngReadAndSkip cause there is no registered converter for this op.
WARNING:tensorflow:Using a while_loop for converting Bitcast cause there is no registered converter for this op.
WARNING:tensorflow:Using a while_loop for converting Bitcast cause there is no registered converter for this op.
WARNING:tensorflow:Using a while_loop for converting StatelessRandomUniformV2 cause there is no registered converter for this op.
WARNING:tensorflow:Using a while_loop for converting ImageProjectiveTransformV3 cause there is no registered converter for this op.
WARNING:tensorflow:Using a while_loop for converting RngReadAndSkip cause there is no registered converter for this op.
WARNING:tensorflow:Using a while_loop for converting Bitcast cause there is no registered converter for this op.
WARNING:tensorflow:Using a while_loop for converting Bitcast cause there is no registered converter for this op.
WARNING:tensorflow:Using a while_loop for converting StatelessRandomUniformV2 cause there is no registered converter for this op.
WARNING:tensorflow:Using a while_loop for converting ImageProjectiveTransformV3 cause there is no registered converter for this op.

**Comment by sampathweb** [comment]
Does your windows build has GPU?  If so, install and use from Windows WSL (https://www.tensorflow.org/install/pip#windows-wsl2).  Starting in TF 2.11, Native Windows doesn't have GPU support, but you could use it via WSL.

**Comment by SuryanarayanaY** [comment]
Hi @EZeroDivide ,

Since you are using WIndows, TF2.10 is the last versions that supports GPU on windows. Since you are using TF2.11 on windows I am assuming that you are using CPUs for the training which takes more time compared to GPU.

As mentioned in above [comment](https://github.com/keras-team/keras-io/issues/1174#issuecomment-1451182830), You can install WSL on windows and can  utilize GPU for faster trainings.

Thank you!
