### ISSUE TITLE
Doubt on the dataset used in the textural inversion tutorial

### ISSUE THREAD

**Issue by sayakpaul** [keras-team/keras-io#1177]
@LukeWood @ianstenbit thanks for the great tutorial on textual inversion. 

I visited the URLs of the images used in the training set manually but didn't find any group shots, as mentioned in the tutorial. All the images contain a single cat character. 

What do you refer to as group shots? The prompts used there also denote singularity.

**Comment by sayakpaul** [comment]
Nevermind. I later saw the construction of `group_ds`. 

Another question is why did you index with `1` here? 

```py
tokenized_initializer = stable_diffusion.tokenizer.encode("cat")[1]
```

**Comment by ianstenbit** [comment]
Hey @sayakpaul, this is because the tokenizer includes start of text and end of text tokens in its returned encoding, so it returns a list of [start_of_text, encoding_of_cat, end_of_text]

**Comment by sayakpaul** [comment]
Thanks very much!
