### ISSUE TITLE
The Encoder input doesn't use any Position Encoding?

### ISSUE THREAD

**Issue by rshahamiriuoa** [keras-team/keras-io#1183]
Hi,

I'm referring to the Transformer ASR code. The is supplied via SpeechFeatureEmbedding class. But it seems no Position Encoding was applied to the first Encoder input, unlike the original "Attention Is All You Need" and "Speech Transformer" architectures. Is that correct? If so, how does positional data added to the source spectrograms?

https://github.com/keras-team/keras-io/blob/e40fab4a194a3eb8a211a0369683d6c50abdbc55/examples/audio/transformer_asr.py#L78

**Comment by SuryanarayanaY** [comment]
Hi @rshahamiriuoa ,

It was removed in the master branch. Could you please check the master code [here](https://github.com/keras-team/keras-io/blob/master/examples/audio/transformer_asr.py).
