### ISSUE TITLE
Links not working in example code of "Video Classification with Transformers"

### ISSUE THREAD

**Issue by wayneshi08** [keras-team/keras-io#1189]
The download links in 

```
!wget -q https://git.io/JGc31 -O ucf101_top5.tar.gz
!tar xf ucf101_top5.tar.gz

!wget -q https://git.io/JZmf4 -O top5_data_prepared.tar.gz
!tar xf top5_data_prepared.tar.gz
```

are not working. Can someone please fix this. Thanks!

**Comment by sayakpaul** [comment]
Hi. I am the author of that example. I just verified that the links are working. Maybe some rate-limiting issues?

**Comment by sachinprasadhs** [comment]
@wayneshi08 , I was able to run the example with latest TensorFlow version, I did not observe any failures.
Attaching the working Gist for reference https://gist.github.com/sachinprasadhs/42abc049f2508b831a12d1bffe9dee60
