### ISSUE TITLE
keras.layers' has no attribute 'Conv1DTranspose'

### ISSUE THREAD

**Issue by ghm** [keras-team/keras-io#121]
There was an error when I executed the program of Timeseries anomaly detection using an Autoencoder.
The error message is as follows:
**AttributeError: module 'tensorflow.python.keras.api._v1.keras.layers' has no attribute 'Conv1DTranspose'**

here is a link which has class Conv1DTranspose: 
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/layers/convolutional.py

but the below link that doesn't have Conv1DTranspose:
https://tensorflow.google.cn/api_docs/python/tf/keras/layers/

Please tell me what should I do to use Conv1DTranspose correctly?

thanks!

**Comment by PrabhanshuAttri** [comment]
`tf.keras.layers.Conv1DTranspose` is new and only available in tf-nightly. You can find more about it [here](https://www.tensorflow.org/api_docs/python/tf/keras/layers/Conv1DTranspose)

Install tf-nightly to use it.

I had the same issue with `timeseries_dataset_from_array`

**Comment by ghm** [comment]
Thank you for your help, the error has disappeared after installing the latest tf-nightly version as you described.
