### ISSUE TITLE
Resource module error on MacOS and Windows

### ISSUE THREAD

**Issue by woolfel** [keras-team/keras-io#1212]
Resource module doesn't exist on Windows or Mac. When you try to run retina_net_overview.py on windows10 or macos it get resources module missing error.
https://github.com/keras-team/keras-io/blob/master/guides/keras_cv/retina_net_overview.py 

It would be a good idea to update the code to use a module that is cross platform. I'm willing to help update and patch this. Is there a different package that can replace luketils and resource?

**Comment by woolfel** [comment]
for now, I commented out the visualization calls in the script and it runs on windows.

**Comment by woolfel** [comment]
I'm trying to get a modified version of the guide working on MacOS without the visualization calls. It's getting errors.

ValueError: Requires start <= limit when delta > 0: 8/4 for '{{node retina_net_label_encoder/range_2}} = Range[Tidx=DT_FLOAT](retina_net_label_encoder/mul_18, retina_net_label_encoder/add_4, retina_net_label_encoder/Cast_9)' with input shapes: [], [], [] and with computed input tensors: input[0] = <8>, input[1] = <4>, input[2] = <16>.
    
    
    Call arguments received by layer "retina_net_label_encoder" (type RetinaNetLabelEncoder):
      • images=tf.Tensor(shape=(None, None, 3), dtype=float32)
      • box_labels={'classes': 'tf.Tensor(shape=(None,), dtype=float32)', 'boxes': 'tf.Tensor(shape=(None, 4), dtype=float32)'}

It appears something is causing it to fail on M2 Macbook. Anyone have tips where to look? I spent a couple of hours looking through keras_cv code to see what's throwing the error.

**Comment by woolfel** [comment]
I spent several hours debugging the error on MacOS and haven't been able to track down the real cause. I also looked keras-cv source code to see what might be causing the box_labels error. Any tips on which files to look at?

I'm willing to patch it and submit pull request, once I figure out what is causing the error. I was guessing recent changes to keras cv broke the example.

**Comment by LukeWood** [comment]
I think your inputs here are unbatched - am I correct?

**Comment by LukeWood** [comment]
If so, we can add support for unbatched inputs in the RetinaNet label encoder, or we can raise an error if unbatched inputs are passed to fit.

**Comment by woolfel** [comment]
@LukeWood  thanks for responding. I ran into an issue with batching shown in the guide

train_ds = train_ds.apply(tf.data.experimental.dense_to_ragged_batch(BATCH_SIZE))
eval_ds = eval_ds.apply(tf.data.experimental.dense_to_ragged_batch(BATCH_SIZE))

The original tutorial had those lines (123-124), but it threw a bunch of errors on MacOS. Removing those line got past the dense_to_ragged_batch error, but broke the eval during training. I'll try to get the batch to work again on Mac.

**Comment by woolfel** [comment]
I tried it with dense_to_ragged_batch and get this error on MacOS

    File "/var/folders/gm/cy08zj8x2wb3bjf_f2dx5s_w0000gn/T/__autograph_generated_filekevl6b3g.py", line 25, in if_body
        raise ag__.converted_call(ag__.ld(ValueError), (f"`RetinaNetLabelEncoder`'s `call()` method does not support RaggedTensor inputs for the `images` argument.  Received `type(images)={ag__.converted_call(ag__.ld(type), (ag__.ld(images),), None, fscope)}`.",), None, fscope)

    ValueError: Exception encountered when calling layer "retina_net_label_encoder" (type RetinaNetLabelEncoder).
    
    in user code:
    
        File "/Users/peter/miniconda3/envs/tensorflow_bench/lib/python3.9/site-packages/keras_cv/layers/object_detection/retina_net_label_encoder.py", line 169, in call  *
            raise ValueError(
    
        ValueError: `RetinaNetLabelEncoder`'s `call()` method does not support RaggedTensor inputs for the `images` argument.  Received `type(images)=<class 'tensorflow.python.ops.ragged.ragged_tensor.RaggedTensor'>`.
    
    
    Call arguments received by layer "retina_net_label_encoder" (type RetinaNetLabelEncoder):
      • images=tf.RaggedTensor(values=tf.RaggedTensor(values=Tensor("RaggedFromVariant/RaggedTensorFromVariant:2", shape=(None, 3), dtype=float32), row_splits=Tensor("RaggedFromVariant/RaggedTensorFromVariant:1", shape=(None,), dtype=int64)), row_splits=Tensor("RaggedFromVariant/RaggedTensorFromVariant:0", shape=(None,), dtype=int64))
      • box_labels={'classes': 'tf.RaggedTensor(values=Tensor("RaggedFromVariant_2/RaggedTensorFromVariant:1", shape=(None,), dtype=float32), row_splits=Tensor("RaggedFromVariant_2/RaggedTensorFromVariant:0", shape=(None,), dtype=int64))', 'boxes': 'tf.RaggedTensor(values=Tensor("RaggedFromVariant_1/RaggedTensorFromVariant:1", shape=(None, 4), dtype=float32), row_splits=Tensor("RaggedFromVariant_1/RaggedTensorFromVariant:0", shape=(None,), dtype=int64))'}

Here's the entire script.
`# Disclaimer!!   this script doesn't work on Windows or Mac yet. Even though I borrowed from Keras_cv guides,
# this spits out a bunch of errors. The only difference is this vesion doesn't use linux specific libraries
# and skips the visualization steps. The original script is https://github.com/keras-team/keras-io/blob/master/guides/keras_cv/retina_net_overview.py
# Since google doesn't care about writing good documentation or keeping it up-to-date, developers have to suffer
# the pain of a million paper cuts.
import tensorflow as tf
import tensorflow_datasets as tfds
from tensorflow import keras
from keras import optimizers
import keras_cv
from keras_cv import bounding_box
from keras_cv.callbacks import PyCOCOCallback
import time
import os
import sys

print('Tensorflow version - ',tf.__version__)
print('Keras_cv version - ', keras_cv.__version__)

checkpoint_path = "training/weights.{epoch:02d}-{epoch:02d}-{accuracy:.3f}-{val_accuracy:.3f}-{val_loss:.3f}.h5"
data_directory = '~/tensorflow_datasets/voc'
batch_size=64
epoch_count=50
num_classes=20

def main():
    args = sys.argv[0:]

    if len(args) == 1:
        print(' ----- checkpoints directory ', checkpoint_path)
    else:
        if len(args) == 3:
            batch_size = int(args[2])
        checkpoint_path = args[1] + "/weights.{epoch:02d}-{accuracy:.3f}-{loss:.3f}-{val_accuracy:.3f}-{val_loss:.3f}.h5"
        print(' ----- checkpoints directory ', args[1])
        print(' -- batch size: ', batch_size)
        mobilenet = loadModel()
        run(checkpoint_path, mobilenet)

def loadModel():
    # use MobileNet from Keras applications
    model = keras_cv.models.RetinaNet(classes=num_classes,bounding_box_format="xywh",
        backbone=keras_cv.models.ResNet50(include_top=False, weights="imagenet", include_rescaling=True).as_backbone())
    model.backbone.trainable = False
    return model

def unpackage_tfds_inputs(inputs):
    image = inputs["image"]
    boxes = bounding_box.convert_format(
        inputs["objects"]["bbox"],
        images=image,
        source="rel_yxyx",
        target="xywh",
    )
    bounding_boxes = {
        "classes": tf.cast(inputs["objects"]["label"], dtype=tf.float32),
        "boxes": tf.cast(boxes, dtype=tf.float32),
    }
    return {"images": tf.cast(image, tf.float32), "bounding_boxes": bounding_boxes}


def dict_to_tuple(inputs):
    return inputs["images"], bounding_box.to_dense(
        inputs["bounding_boxes"], max_boxes=32
    )

def run(checkpoint_path, model):
    # get pascalvoc dataset
    train_dataset = tfds.load('voc/2007', split='train+validation', 
        with_info=False, shuffle_files=True, data_dir=data_directory)
    eval_dataset = tfds.load('voc/2007', split='test',
        with_info=False, data_dir=data_directory)
    # map to convert VOC dataset
    train_ds = train_dataset.map(unpackage_tfds_inputs, num_parallel_calls=tf.data.AUTOTUNE)
    eval_ds = eval_dataset.map(unpackage_tfds_inputs, num_parallel_calls=tf.data.AUTOTUNE)
    
    inference_resizing = keras_cv.layers.Resizing(
        640, 640, bounding_box_format="xywh", pad_to_aspect_ratio=True)
    eval_ds = eval_ds.map(inference_resizing, num_parallel_calls=tf.data.AUTOTUNE)

    train_ds = train_ds.map(dict_to_tuple, num_parallel_calls=tf.data.AUTOTUNE)
    eval_ds = eval_ds.map(dict_to_tuple, num_parallel_calls=tf.data.AUTOTUNE)
    train_ds = train_ds.prefetch(tf.data.AUTOTUNE)
    eval_ds = eval_ds.prefetch(tf.data.AUTOTUNE)
    train_ds = train_ds.apply(tf.data.experimental.dense_to_ragged_batch(batch_size))
    eval_ds = eval_ds.apply(tf.data.experimental.dense_to_ragged_batch(batch_size))

    base_lr = 0.01
    lr_decay = tf.keras.optimizers.schedules.PiecewiseConstantDecay(boundaries=[12000 * 16, 16000 * 16],
        values=[base_lr, 0.1 * base_lr, 0.01 * base_lr],)
    optimizer = tf.keras.optimizers.SGD(learning_rate=lr_decay, momentum=0.9, global_clipnorm=10.0)
    model.compile(
        classification_loss="focal",
        box_loss="smoothl1",
        optimizer=optimizer)

    # Create a callback that saves the model's weights
    cp_callback = tf.keras.callbacks.ModelCheckpoint(filepath=checkpoint_path,
                                                    save_weights_only=False,
                                                    verbose=1,
                                                    monitor='accuracy',
                                                    save_freq='epoch')
    callbacks = [PyCOCOCallback(eval_ds, bounding_box_format="xywh"),
        cp_callback]

    start_time = time.time()
    model.fit(
        train_ds,
        epochs=epoch_count,
        validation_data=eval_ds,
        batch_size=batch_size,
        callbacks=callbacks
    )
    end_time = time.time()

    # A final test to evaluate the model
    print('Test loss:', model.loss)
    print('Elapsed Time: %0.4f seconds' % (end_time - start_time))
    print('Elapsed Time: %0.4f minutes' % ((end_time - start_time)/60))
    print(model.summary())


# this is the recommended approach of handling main function
if __name__ == "__main__":
    main()
`

**Comment by woolfel** [comment]
the conda config I'm using to create my virtual env

name: tensorflow_bench
channels:
  - apple
dependencies:
  - python=3.9
  - tensorflow-deps
  - pip:
      - tensorflow-macos==2.9
      - tensorflow-metal==0.5.0
      - tensorflow_datasets
      - keras_cv==0.4.1
      - numpy
      - marshmallow
      - pycocotools
      - wandb

**Comment by LukeWood** [comment]
> @LukeWood thanks for responding. I ran into an issue with batching shown in the guide
> 
> train_ds = train_ds.apply(tf.data.experimental.dense_to_ragged_batch(BATCH_SIZE)) eval_ds = eval_ds.apply(tf.data.experimental.dense_to_ragged_batch(BATCH_SIZE))
> 
> The original tutorial had those lines (123-124), but it threw a bunch of errors on MacOS. Removing those line got past the dense_to_ragged_batch error, but broke the eval during training. I'll try to get the batch to work again on Mac.

yeah you have to use batched data.

How did this break on MacOS?  Can you print the error.  Please upgrade to TF 2.11

**Comment by LukeWood** [comment]
> tensorflow-macos==2.9
> tensorflow-metal==0.5.0

does this give you two TF installations?

**Comment by woolfel** [comment]
To get Tensorflow to work on Apple Silicon, M1 and M2 you have to use both tensorflow-macos and tensorflow-metal.

tensorflow-macos is apple's package of tensorflow for apple sillicon
tensorflow-metal is the apple metal binding to enable GPU acceleration.

You can skip tensorflow-metal if you don't want to use GPU, but you can guess how slow that runs :)  I'll try upgrading to the latest and see if it works. There was a regression with tensorflow-metal 0.7.0 that broke gpu acceleration. I see 0.7.1 was just released on Feb7. I will report back

**Comment by woolfel** [comment]
unfortunately TF 2.11 doesn't work with any versions of tensorflow-metal :(  I tried every version combination I could think of without any luck. I will keep an eye on tensorflow-metal and try again when Apple releases a new version.  It's really too bad I can't benchmark my M2Max 38 GPU, 96G macbook with the latest release.

@LukeWood  thanks for the hints

**Comment by woolfel** [comment]
[error.log](https://github.com/keras-team/keras-io/files/10831363/error.log)

I was able to install tensorflow 2.11 without GPU support and verified it works with a simple cifar10 benchmark I wrote for mac. I'm still getting RaggedTensor errors.  The log file is attached.

**Comment by sachinprasadhs** [comment]
@woolfel , Could you please install latest `Keras(3.0.4) ` and try again.
You can import keras directly now with the multi backend framework support.

**Comment by woolfel** [comment]
@sachinprasadhs  it would be my pleasure. i will try to test it tomorrow nite and report back
