### ISSUE TITLE
Getting all predictions as zero

### ISSUE THREAD

**Issue by BlAKNinja** [keras-team/keras-io#1224]
I have trained this model using the same code provided here and have not used downloaded weights and getting all predictions as zero and no class has been predicted

**Comment by grasskin** [comment]
Hi @BlAKNinja could you provide a minimal colab for reproduction?

**Comment by BlAKNinja** [comment]
hi @grasskin here is link of google colab
 https://colab.research.google.com/drive/1iARsJD4SlI4N1LIgye6afyPZo-nRCc1i?usp=sharing

**Comment by yassiney** [comment]
I was facing the same issue
I solve it by editing confidence_hreshold in the DecodePredictions function.
DecodePredictions (confidence_hreshold=0.01 )

**Comment by BlAKNinja** [comment]
Thanks 👍🏻

**Comment by SuryanarayanaY** [comment]
Hi @BlAKNinja ,

COuld you please confirm whether the solution provided in above [comment](https://github.com/keras-team/keras-io/issues/1224#issuecomment-1503885429) works for you. Shall we mark it as resolved ?

Thanks!

**Comment by BlAKNinja** [comment]
Yes it work you can make it resolved.
