### ISSUE TITLE
Training time doubles after replacing Conv2D with SeparableConv2D 

### ISSUE THREAD

**Issue by coelho-k** [keras-team/keras-io#1225]
Everything about the architecture remains constant.
Using Tensorflow 2.9.0 within a Docker container, with cudnn 8

**Comment by grasskin** [comment]
Hi @coelho-k, could you provide a minimal colab example for reproduction?

**Comment by coelho-k** [comment]
Hi @grasskin, It is the exact code from: https://keras.io/examples/vision/mobilevit/
However, I just replaced all the Conv2D layers with SeparableConv2D

**Comment by SuryanarayanaY** [comment]
Hi @coelho-k ,

Apologies for the delay. I have tested the attached example with `Conv2D` and `SeparableConv2D` layers respectively and got training completed in `1219.6` seconds and `1236.8` seconds respectively which is almost same time for both cases. Please refer to attached [gist](https://colab.research.google.com/gist/SuryanarayanaY/37ed07dec20e4a26560a486c40140f15/mobilevit.ipynb#scrollTo=VOd_saSH2lD-).
