### ISSUE TITLE
integrated gradient example: provide the model as an argument into the functions API

### ISSUE THREAD

**Issue by jerabaul29** [keras-team/keras-io#1226]
I was at first quite a bit confused when reading https://github.com/keras-team/keras-io/blob/master/examples/vision/integrated_gradients.py , in particular:

https://github.com/keras-team/keras-io/blob/c2c487d4f089414c38d420af2bd3f5d9440a0a9a/examples/vision/integrated_gradients.py#L450-L495

as I did not understand where the model came in to play. After reading the full code, it seems that the model is passed as a global variable into the functions that compute the integrated gradient. This is a bit confusing from an API and user viewpoint, as it is not clear from looking at the user code what model is used where to compute the integrated gradient.

As I am looking into this topic of integrated gradients, a note to myself / other users: would be useful to refactor this example and provide some turn key functions that could be re-used with an easy to understand API and no hidden global variable arguments :) .

A second note to myself: compare https://github.com/keras-team/keras-io/blob/c2c487d4f089414c38d420af2bd3f5d9440a0a9a/examples/vision/integrated_gradients.py with alternatives such as https://github.com/hiranumn/IntegratedGradients .

**Comment by grasskin** [comment]
Hi jerabaul, thank you for opening this issue. Keras team does not actively maintain these examples and you should reach out to the author directly. Alternatively, you can of course submit a PR with the refactor as I'm sure other members of the community ran into similar issues.
