### ISSUE TITLE
gdown is not working in keras-io/examples/vision/deeplabv3_plus.py

### ISSUE THREAD

**Issue by victorbug** [keras-team/keras-io#1228]
Suggestion:
Replace:
!gdown https://drive.google.com/uc?id=1B9A9UCJYMwTL4oBEo4RZfbMZMaZhKJaz
By:
!gdown "1B9A9UCJYMwTL4oBEo4RZfbMZMaZhKJaz&confirm=t"

**Comment by nkovela1** [comment]
We are moving over this discussion to the PR you created. Thanks!
