### ISSUE TITLE
Tuning and early stop in writing a training loop from scratch

### ISSUE THREAD

**Issue by elamey** [keras-team/keras-io#1230]
First, fantastic resource! Thank you for all the time invested in "writing a training loop from scratch."

Could this guide be updated to include hyper parameter "auto" training and early stopping? With the training loop being "from scratch" aka custom, I've not been able to figure out how to implement them.

Thank you!

**Comment by SuryanarayanaY** [comment]
Hi @elamey ,

Apologies for the late response. I am hoping you are referring to the attached [example](https://keras.io/guides/writing_a_training_loop_from_scratch/) tutorial right ?

Basically for early stopping of the training irrespective of model we can define a callback using [tf.keras.callbacks.EarlyStopping](https://www.tensorflow.org/api_docs/python/tf/keras/callbacks/EarlyStopping) API and the pass this callback to `model.fit()` like below 

`model.fit(...,callbacks=[tf.keras.callbacks.EarlyStopping(...)]`

You can refer the attached API documentation for more details.

If you want to use features of `model.fit()` along with custom training you need to create a model using Model subclassing and then override the function `train_step()` inside this model class. Within the train_step function you can define your training loop. Please refer attached tutorial [here](https://keras.io/guides/customizing_what_happens_in_fit/) for an end to end example of how we can use model.fit along with custom training loop.I hope this helps for you.

Thank you!
