### ISSUE TITLE
New cell type for KerasCV/KerasNLP guides

### ISSUE THREAD

**Issue by LukeWood** [keras-team/keras-io#1232]
We need a special cell type for all KerasCV/KerasNLP guides that installs/upgrades to the latest TF/KerasCV/KerasNLP/a compatible Cuda version.  Our guides pretty consistently fail and require users to fix Colab environments themselves.

I think making this a special cell type is optimal, as it allows us to bump versions in a single location. 

@fchollet if you think this is a good idea I can hack something together.

**Comment by haifeng-jin** [comment]
This issue is no longer valid. The colab issues are fixed.
