### ISSUE TITLE
transformer.fit(train_ds, epochs=epochs, validation_data=val_ds) not working

### ISSUE THREAD

**Issue by amritangshudey** [keras-team/keras-io#1234]
InvalidArgumentError                      Traceback (most recent call last)
[<ipython-input-12-6ad212c33200>](https://localhost:8080/#) in <module>
      5     "rmsprop", loss="sparse_categorical_crossentropy", metrics=["accuracy"]
      6 )
----> 7 transformer.fit(train_ds, epochs=epochs, validation_data=val_ds)

[/usr/local/lib/python3.8/dist-packages/tensorflow/python/eager/execute.py](https://localhost:8080/#) in quick_execute(op_name, num_outputs, inputs, attrs, ctx, name)
     50   try:
     51     ctx.ensure_initialized()
---> 52     tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
     53                                         inputs, attrs, num_outputs)
     54   except core._NotOkStatusException as e:

InvalidArgumentError: Graph execution error:

**Comment by nkovela1** [comment]
Hi @amritangshudey, could you please provide a minimal Colab containing your code to reproduce this error?

**Comment by andreasvspies** [comment]
I am facing the same problem, even with the colab example provided on keras website
https://colab.research.google.com/github/keras-team/keras-io/blob/master/examples/nlp/ipynb/neural_machine_translation_with_transformer.ipynb

**Comment by amritangshudey** [comment]
> I am facing the same problem, even with the colab example provided on keras website https://colab.research.google.com/github/keras-team/keras-io/blob/master/examples/nlp/ipynb/neural_machine_translation_with_transformer.ipynb

**Comment by amritangshudey** [comment]
I was trying the same code and faced the same issue.
I was able to fix the issue by making two changes:-
1) train_samples should be a multiple of batch size.
2) num_heads = batch size.

I don't know how it works , if someone can explain??
and making these changes also hamper the model performance also, so is there any better solution?
