### ISSUE TITLE
Timeseries anomaly detection using an Autoencoder - Using Conv1DTranspose

### ISSUE THREAD

**Issue by CanK93** [keras-team/keras-io#124]
Hi,

is there any workaround for using Conv1DTranspose in the example because it is not in the stable version?
I tried to model it with Conv2DTranspose but it did not work.
Installing tf-nightly throws me an error: " ERROR: Could not find a version that satisfies the requirement tf-nightly (from versions: none)ERROR: No matching distribution found for tf-nightly" (Windows 10)

**Comment by alxfmpl** [comment]
Hi,

I had the same problem, turns out that a `Conv1DTranspose()` layer, if I understood it correctly, is very similar to a 
`Conv1D()` layer followed by a `UpSampling1D()` layer.

Hope this helps.

**Comment by jonathan-goh** [comment]
> Hi,
> 
> I had the same problem, turns out that a `Conv1DTranspose()` layer, if I understood it correctly, is very similar to a
> `Conv1D()` layer followed by a `UpSampling1D()` layer.
> 
> Hope this helps.

Would you be able to show the code on the workaround?

**Comment by alxfmpl** [comment]
Sure, note that I adjusted the layers a little but the general notion should be clear:

`model = keras.Sequential(
    [
        layers.Input(shape=(x_train.shape[1], x_train.shape[2])),
        layers.Conv1D(
            filters=32, kernel_size=8, padding="same", strides=3, activation="relu"
        ),
        layers.Dropout(rate=0.2),
        layers.Conv1D(
            filters=16, kernel_size=8, padding="same", strides=3, activation="relu"
        ),
        layers.Dropout(rate=0.2),
        layers.Conv1D(
            filters=8, kernel_size=8, padding="same", strides=3, activation="relu"
        ),
        layers.Conv1D(filters=8, kernel_size=8, padding="same", activation="relu"),
        layers.UpSampling1D(size=3),
        layers.Dropout(rate=0.2),        
        layers.Conv1D(filters=16, kernel_size=8, padding="same", activation="relu"),
        layers.UpSampling1D(size=3),
        layers.Dropout(rate=0.2),
        layers.Conv1D(filters=32, kernel_size=8, padding="same", activation="relu"),
        layers.UpSampling1D(size=3),
        layers.Conv1D(filters=1, kernel_size=8, padding="same"),
    ]
)`

**Comment by CPalas** [comment]
Hi would you be able to show the code of the modified Training code? I get many errors, with, at the end, the final:

ValueError: A target array with shape (3744, 288, 1) was passed for an output of shape (None, 297, 1) while using as loss `mean_squared_error`. This loss expects targets to have the same shape as the output.

**Comment by cwestby1** [comment]
You can also define a Conv1DTranspose from scratch like @Guitaricet writes here: https://github.com/tensorflow/tensorflow/issues/30309#issuecomment-589531625

**Comment by SuryanarayanaY** [comment]
Hi @CanK93 ,

We are in the process of going through backlogs. I found this is not an issue now. I have tried executing the Tutorial with TF2.12v and executes fine with `Conv1DTranspose` layer also.Please refer the attached [gist](https://colab.research.google.com/gist/SuryanarayanaY/77325f9062cdc37f7b4f91f3fe03f3b0/keras_io-224-timeseries_anomaly_detection.ipynb).

Please cross check and feel free to close the issue. Thanks!
