### ISSUE TITLE
Error in notebook https://github.com/keras-team/keras-io/blob/master/examples/vision/forwardforward.py

### ISSUE THREAD

**Issue by karencfisher** [keras-team/keras-io#1241]
Trying to run through the example forward-forward image classifier (https://github.com/keras-team/keras-io/blob/master/examples/vision/forwardforward.py) without change on Google Colab produces error during model training:

StagingError                              Traceback (most recent call last)
[<ipython-input-6-fb5b36d9bea8>](https://localhost:8080/#) in <module>
      9 
     10 epochs = 250
---> 11 history = model.fit(train_dataset, epochs=epochs)

1 frames
[/usr/local/lib/python3.8/dist-packages/keras/utils/traceback_utils.py](https://localhost:8080/#) in error_handler(*args, **kwargs)
     68             # To get the full stack trace, call:
     69             # `tf.debugging.disable_traceback_filtering()`
---> 70             raise e.with_traceback(filtered_tb) from None
     71         finally:
     72             del filtered_tb

[/usr/local/lib/python3.8/dist-packages/tensorflow/python/framework/func_graph.py](https://localhost:8080/#) in autograph_handler(*args, **kwargs)
   1267           except Exception as e:  # pylint:disable=broad-except
   1268             if hasattr(e, "ag_error_metadata"):
-> 1269               raise e.ag_error_metadata.to_exception(e)
   1270             else:
   1271               raise

StagingError: in user code:

    File "/usr/local/lib/python3.8/dist-packages/keras/engine/training.py", line 1249, in train_function  *
        return step_function(self, iterator)
    File "/usr/local/lib/python3.8/dist-packages/keras/engine/training.py", line 1222, in run_step  *
        outputs = model.train_step(data)
    File "<ipython-input-4-e4b5d64935d8>", line 106, in train_step  *
        h_pos, h_neg, loss = layer.forward_forward(h_pos, h_neg)
    File "<ipython-input-3-d812be91e578>", line 72, in forward_forward  *
        self.optimizer.apply_gradients(zip(gradients, self.dense.trainable_weights))
    File "/usr/local/lib/python3.8/dist-packages/keras/optimizers/optimizer_experimental/optimizer.py", line 208, in _update_step_xla  *
        return self._update_step(gradient, variable)
    File "/usr/local/lib/python3.8/dist-packages/keras/optimizers/optimizer_experimental/optimizer.py", line 216, in _update_step  **
        raise KeyError(

    KeyError: 'The optimizer cannot recognize variable dense_1/kernel:0. This usually means you are trying to call the optimizer to update different parts of the model separately. Please call `optimizer.build(variables)` with the full list of trainable variables before the training loop or use legacy optimizer `tf.keras.optimizers.legacy.{self.__class__.__name__}.'

**Comment by sampathweb** [comment]
Thanks for reporting this issue.  This is a regression that has happened in TF 2.11 Release.  If you change to TF 2.10 (`!pip install tensorflow~=2.10.0`), the issue goes away. 

I tried switching to legacy optimizer and that didn't resolve the issue.  Going to follow-up to find the root of the issue.

**Comment by alisonpeard** [comment]
Looking for another solution to this since the legacy optimiser does not have features that I need.
