### ISSUE TITLE
'OxfordPets' object has no attribute 'ndim' Error

### ISSUE THREAD

**Issue by akare55** [keras-team/keras-io#125]
Hi everyone, 
When I try to run keras-io/examples/vision/oxford_pets_image_segmentation.py. I get 'OxfordPets' object has no attribute 'ndim' Error. 
Could you help me about this?

**Comment by pcoet** [comment]
Note: We should add a pip install command for KerasCV, so that the tutorial doesn't throw an error on the first cell.

**Comment by pcoet** [comment]
The notebook throws an error when you try to [create the training and validation sets](https://github.com/keras-team/keras-io/blob/65e769e2b51d6955f3dd364acc77f8e3ca59e065/examples/vision/oxford_pets_image_segmentation.py#L165-L181). Needs further investigation.

```
Error details:
        Tensor("sequential/rand_augment/cond/random_choice/switch_case/indexed_case/Identity_1:0", shape=(160, 160, 1), dtype=float32) and Tensor("sequential/rand_augment/cond/random_choice/switch_case/indexed_case/Identity_1:0", shape=(160, 160, 1), dtype=int64) have different types
    
    
    Call arguments received by layer 'random_choice' (type RandomChoice):
      • inputs={'images': 'tf.Tensor(shape=(160, 160, 3), dtype=float32)', 'segmentation_masks': 'tf.Tensor(shape=(160, 160, 1), dtype=int64)'}


Call arguments received by layer 'rand_augment' (type RandAugment):
  • inputs={'images': 'tf.Tensor(shape=(160, 160, 3), dtype=float32)', 'segmentation_masks': 'tf.Tensor(shape=(160, 160, 1), dtype=int64)'}
```

**Comment by sachinprasadhs** [comment]
Hi,

The example has been updated to Keras 3 with many changes and now it is running successfully, please find the Gist here for more details https://keras.io/examples/vision/oxford_pets_image_segmentation/
