### ISSUE TITLE
Hello, can this code be used to do time series forecasting

### ISSUE THREAD

**Issue by Llixiaoxin** [keras-team/keras-io#1270]
I want to use the transformer to make time series predictions, and I want to find a model that has already been written, because my own learning ability is really poor, sorry to disturb you

**Comment by mattdangerw** [comment]
This issue list is probably not the best place for open ended questions like this, maybe try the tensorflow forum? https://discuss.tensorflow.org/

Here's our full list of timeseries examples, but these will mainly be examples aimed at building understanding of concepts, not providing plug and play models. https://keras.io/examples/timeseries/
