### ISSUE TITLE
Adding more GANs to the examples

### ISSUE THREAD

**Issue by CleanPegasus** [keras-team/keras-io#128]
There are only examples of WGAN and DCGAN in Keras' examples. I would like to add more GANs like **LSGAN**, **ACGAN**, **InfoGAN**, etc. Please let me know if I can submit a pull request regarding this.

**Comment by sachinprasadhs** [comment]
Hi, Thanks for reporting the issue, please feel free to create a PR, Keras team would be happy to review.
