### ISSUE TITLE
ValueError: Weights for model sequential have not yet been created. Weights are created when the Model is first called on inputs or build() is called with an input_shape.

### ISSUE THREAD

**Issue by linfengYang** [keras-team/keras-io#1296]
How to fix the problem when I try to add Conv2D operations :ValueError: Weights for model sequential have not yet been created. Weights are created when the Model is first called on inputs or `build()` is called with an `input_shape`.

**Comment by Warlord-K** [comment]
You might be getting this error because you haven't provided the input shape, Could you please provide the code where you are getting this error?

**Comment by SuryanarayanaY** [comment]
Hi @linfengYang ,

If you are using a simple sequential model then you need to pass input_shape to the first layer.Refer a simple code snippet below.

```
model = keras.Sequential()
model.add(keras.layers.Dense(2, activation="relu"))

model.summary() 
```

> `#raises ValueError: This model has not yet been built. Build the model first by calling `build()` or by calling the model on a batch of data.
`
The below code works fine when added input_shape

```
model = keras.Sequential()
model.add(keras.layers.Dense(2, activation="relu", input_shape=(4,)))

model.summary()
```

Alternatively you can also call the model with some input value and model will infer the `input_shape` from the provided input automatically.

```
from keras import layers
model = keras.Sequential(
    [
        layers.Dense(2, activation="relu"),
        layers.Dense(3, activation="relu"),
        layers.Dense(4),
    ]
)  # No weights at this stage!

# At this point, you can't do this:
# model.weights

# You also can't do this:
# model.summary()

# Call the model on a test input
x = tf.ones((1, 4))
y = model(x)
print("Number of weights after calling the model:", len(model.weights)) 
model.summary()
```

Please refer the attached [gist](https://colab.research.google.com/gist/SuryanarayanaY/04775ca81212f081156087f092fa34af/keraio-1296.ipynb) also for verifying the results above.

Thanks!
