### ISSUE TITLE
Missing explanations

### ISSUE THREAD

**Issue by Guitalex** [keras-team/keras-io#1301]
==>    hidden_units = [8, 8]

Hello guys,

Is it possible to add explanations on the reasons for the choices for the hidden units values?   
it's not a real issue because everything work perfectly but I don't understand why you had choosen these values..

why not these possibilities :  [7, 7] [9, 9]  [7, 7, 7] [8,8,8] [9, 9, 9]  etc...    
(theses exemples are totaly random, sorry if they look to be "dumb values". I'm learning alone, without school, in my house with nobody to help me)

THANKS YOU VERY MUCH!!!!!

Alex

**Comment by SuryanarayanaY** [comment]
Hi @Guitalex ,

Could you please confirm which example/tutorial you are referring to ? Yeah sometimes some values work best based on lot of trails.Please provide more context to look into the issue.

Thanks!

**Comment by iAlexMG** [comment]
hello!

for this example :  https://keras.io/examples/keras_recipes/bayesian_neural_networks/

THX!  

Alex

**Comment by SuryanarayanaY** [comment]
Hi @Guitalex ,

Thanks for pointing out to exact tutorial. I have gone through the tutorial and the `hidden_units` are nothing but hidden dense layers with each unit in hidden_units representing no of neurons. Yeah you can alter these values as per your requirement.You can take of size=3 of you want 3 hidden dense layers etc.

To demonstrate the same I tried with `hidden_units = [10, 8, 4]` and attached [gist](https://colab.sandbox.google.com/gist/SuryanarayanaY/de4be869342192628a0abcf738bc30ff/keras_io-1301_bayesian_neural_networks_wine.ipynb) for results.

**Comment by SuryanarayanaY** [comment]
@Guitalex ,

I am not reopening the issue again as it is not an issue and my explanation above is enough to address the issue.

If you still have any query regarding this please let me know.

Thanks!
