### ISSUE TITLE
AttributeError: 'tuple' object has no attribute 'reshape'

### ISSUE THREAD

**Issue by fede72bari** [keras-team/keras-io#1313]
running the code I get this error:

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/tmp/ipykernel_134/1157790919.py in <module>
    266 
    267         # Get the logits, action, and take one step in the environment
--> 268         observation = observation.reshape(1, -1)
    269         logits, action = sample_action(observation)
    270         observation_new, reward, done, _ = env.step(action[0].numpy())

AttributeError: 'tuple' object has no attribute 'reshape'

Since I read that Gym was discontinued, I was importing Gymnasium instead. Is not this code compatible with Gymnasium?

**Comment by sachinprasadhs** [comment]
Could you please provide the code or the example which you are trying to execute. Thanks!
