### ISSUE TITLE
Small bug in tutobooks.py

### ISSUE THREAD

**Issue by mb16biswas** [keras-team/keras-io#1326]
Hi, while using this command
```
python tutobooks.py nb2py path_to_your_nb.ipynb ../examples/vision/script_name.py
```
its shows these error: 

```
  File "C:\Users\mb16b\keras2\scripts\tutobooks.py", line 592, in <module>
    nb_to_py(source, target)
  File "C:\Users\mb16b\keras2\scripts\tutobooks.py", line 78, in nb_to_py
    content = f.read()
              ^^^^^^^^
  File "C:\Python311\Lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 2458: character maps to <undefined>
```

I figure it out, that  adding encoding="utf8", in line 77 in scripts\tutobooks.py will fix the issue, 
```
f = open(nb_path,encoding="utf8")
```
**should I fix it?, Hope to hear from you guys soon.**

**Comment by SuryanarayanaY** [comment]
Hi @mb16biswas ,

Thanks for reporting. I agree that some files needed encoding correction. Please confirm which tutorial you are referring to with all required context so that I can go through and confirm.

Thanks!

**Comment by mb16biswas** [comment]
Actually I was using this command for one of my  tutorial's, which is currently under review phase. While using the mention command I got an error.  I figured that using  encoding="utf8", in line 77 in scripts\tutobooks.py will fix the problem

**Comment by SuryanarayanaY** [comment]
Hi @mb16biswas ,

You can use encoding='utf8' if its working fine for you. I am not getting in which tutorial of keras-io has that problem so that we can review and fix it also. Is that problem is only for your local repo or is it related to keras-io ?
