### ISSUE TITLE
Updated list for call for contributions

### ISSUE THREAD

**Issue by sarthak247** [keras-team/keras-io#1327]
I have been eager to contribute to the keras examples library and came across the call for contributions list which was available [here](https://github.com/keras-team/keras-io/blob/master/call_for_contributions.md).

I am just curious whether this guide is up to date and that work has already not been done on these examples as the last commit to this fill was on 11 September 2022 and it has been a long time since then. 

Also, can we restructure the document in the form of a table in such a way so that it is easy to keep track of what issues have been already assigned or under progress..

Something like this:
Example Required | Assigned/Not Assigned | If assigned, then link to PR etc

This way it will be easy for people like me who are eager to contribute to know beforehand which issues are already taken up by someone and they can look for something which isn't assigned or which doesn't have an open PR yet.

Cheers,
Sarthak

**Comment by sarthak247** [comment]
Also, I've been wanting to work on the Yoloact or Text-summarization topic available in this list (provided that it is not already taken up by someone) so I need help with that as well. 
Like, in the case of Text-summarization how does the keras team want it to be done. Should it be done with the help of some HuggingFace transformer model for Summarization or do we have something else planned in mind. Also, on what dataset the team wants it to be done. I would love to work on this but I do need a little bit of helping hand with laying down the specifications for this as to what the Keras team actually needs to be done for this task and how they would like me to proceed with it. 

Cheers, 
Sarthak

**Comment by sachinprasadhs** [comment]
Hi @sarthak247 ,

Thanks for reporting your concern.

We no longer actively update "call for contributions". 

If you are interested to contribute, feel free to create a PR directly. 

Make sure the example which you are creating is not listed already here https://keras.io/examples/. Thanks!
