### ISSUE TITLE
Typo in the Learnable Resizer example

### ISSUE THREAD

**Issue by IaBogdi** [keras-team/keras-io#1328]
Dear Sir or Madam,

there is a typo in the code of [Learnable Resizer](https://github.com/keras-team/keras-io/blob/master/examples/vision/learnable_resizer.py).  In the lines 155-156, it seems like residual blocks take input from bottleneck what contradicts with the architecture of original [paper](https://arxiv.org/pdf/2103.09950v1.pdf), where the residual blocks are connected in series. It works fine, when the number of residual blocks is 1, which is the case of this example ;)

I would change the lines 155-156  as follows:

```python
    x = res_block(bottleneck)
    # Residual passes.
    for _ in range(num_res_blocks - 1):
        x = res_block(x)
```

**Comment by SuryanarayanaY** [comment]
Hi @IaBogdi ,

Thanks for reporting the issue. I have gone through the source code and found that the way it is implemented makes first `res_block` to take inputs from bottleneck and subsequent outputs of resblocks again passed to bottleneck layer before feeding to next `res_block`. IMO, this is definitely contradicting to the architecture of standard `Resizer model`. 

In keras_io also the same picture used from that of paper which indicates there is no bottleneck layer in between `res_blocks`.
<img width="792" alt="Screenshot 2023-05-31 at 6 47 31 PM" src="https://github.com/keras-team/keras-io/assets/116063290/ec30e9c7-baef-4bf1-bf89-fbb9208176ea">


IMO as per the standard architecture the implementation seems wrong for me and your proposed code change will fit the standard architecture.However we need confirmation from Developer team whether they want to implement same architecture or they want to really add `bottleneck layer` after each `res_block`. So let's hear confirmation from Dev team.

Thanks!

**Comment by SuryanarayanaY** [comment]
@sayakpaul , Could you please have a look into this and comment your views. Thanks!
