### ISSUE TITLE
movielens_recommendations_transformers.py there is no an example of prediction

### ISSUE THREAD

**Issue by Alecsplus** [keras-team/keras-io#1331]
Dear all, 
I'm new to Keras ad this kind of programming.

When I try to follow the example https://keras.io/examples/structured_data/collaborative_filtering_movielens/ at the end of the example there is the command (clear for me)  "model.predict(user_movie_array)" that shows me the achievement of the goal.

I cannot find it (and I am not able to correctly write it) in the example with transformers. (https://keras.io/examples/structured_data/movielens_recommendations_transformers/)

Can someone please help me?

Thanks in advance

**Comment by SuryanarayanaY** [comment]
@Alecsplus ,

In the transformers tutorial the goal is to find the rating of the movie.In this Tutorial the author tested only model evaluation `model.evaluate(test_dataset)`. Here to predict the ratings there is no dataset like `user_movie_array` in the first link you have attached. But you can test the predictions on `test_dataset` itself using `model.predict(test_dataset)` and it will output the ratings of the movies.

Please refer to attached [gist](https://colab.research.google.com/gist/SuryanarayanaY/d88cf842ed112232a49a6946f439336e/movielens_recommendations_transformers.ipynb) for reference.
