### ISSUE TITLE
Add example - Keras Reproducibility Recipes

### ISSUE THREAD

**Issue by Frightera** [keras-team/keras-io#1332]
I am eager to write a tutorial for `Keras Reproducibility Recipes`. Here are some questions for this:
1) Do we always use the latest version of Keras in the examples? Because there will be some differences in reproducibility techniques between Keras versions (version <= Keras 2.7 and version > 2.7)

2) Does this fall under the category of quick recipes?i

When I have the confirmation, I can start writing this guide.

**Comment by hertschuh** [comment]
@Frightera , 

1. Yes, you should use the latest Keras. And 2.7 is really old now.

2. Can you provide more details on what you mean by `Keras Reproducibility Recipes`?

Thanks!

**Comment by Frightera** [comment]
@hertschuh 

I got the idea from: https://github.com/keras-team/keras-io/blob/master/call_for_contributions.md#keras-reproducibility-recipes

My goal is to provide a comprehensive guide that enables users to obtain consistent results in every run of their deep learning experiments. This issue is frequently raised in various Stackoverflow questions.

**Comment by hertschuh** [comment]
Ok, yeah, I think quick recipes makes sense, but we can see once it's ready if it fits better somewhere else.

Thank you for contributing!

**Comment by Frightera** [comment]
Hi @hertschuh, 

PR is ready.

**Comment by Frightera** [comment]
Closing as PR is merged.
