### ISSUE TITLE
Graph execution error while running on gpu

### ISSUE THREAD

**Issue by amritangshudey** [keras-team/keras-io#1340]
model.fit(
    [encoder_input_data, decoder_input_data],
    decoder_target_data,
    batch_size=batch_size,
    epochs=20,
    validation_split=0.2,
)

this code is part of the official code and runs fine on colab gpu or cpu in system device.
But it gives **graph execution error** while running on system gpu.

**Comment by Shubhamsg17** [comment]
any update on this im getting same error..any fix for this??

**Comment by amritangshudey** [comment]
still no update

**Comment by SuryanarayanaY** [comment]
Hi @amritangshudey ,

Could you please submit the code snippet to replicate the issue. Thanks!
