### ISSUE TITLE
Issue with BeamSampler

### ISSUE THREAD

**Issue by hakim770** [keras-team/keras-io#1373]
I'm trying to use BeamSampler (instead of GreedySampler) in this tutorial: https://keras.io/examples/nlp/neural_machine_translation_with_keras_nlp/

but I got this error:

```
InvalidArgumentError: Exception encountered when calling layer 'multi_head_attention' (type MultiHeadAttention).

{{function_node __wrapped__Einsum_N_2_device_/job:localhost/replica:0/task:0/device:CPU:0}} Expected dimension 1 at axis 0 of the input shaped [2,125,8,64] but got dimension 2 [Op:Einsum]

Call arguments received by layer 'multi_head_attention' (type MultiHeadAttention):
  • query=tf.Tensor(shape=(2, 125, 512), dtype=float32)
  • value=tf.Tensor(shape=(1, 125, 512), dtype=float32)
  • key=None
  • attention_mask=tf.Tensor(shape=(1, 1, 125), dtype=int32)
  • return_attention_scores=False
  • training=None
  • use_causal_mask=False
```

Can anyone help me fixing this issue?

**Comment by sachinprasadhs** [comment]
Hi, It is basically a shape mismatch error, when you replace GreedySampler with the BeamSampler, in the argument for `num_beams` prove value `1` as below.
```
generated_tokens = keras_nlp.samplers.BeamSampler(num_beams=1)(
        next,
        prompt,
        end_token_id=spa_tokenizer.token_to_id("[END]"),
        index=1,  # Start sampling after start token.
    ) 
```

[Here](https://gist.github.com/sachinprasadhs/e9a81e1738aeb1c0315c0c2df2b4d182) is the working Gist for reference. Thanks!

**Comment by hakim770** [comment]
@sachinprasadhs Thanks for the reply. But I want to use BeamSampler with num_beams > 1. how can I adjust the code to work with that?

**Comment by rchao** [comment]
@abheesht17 can you help with this error? Thanks

**Comment by abheesht17** [comment]
Hi, @rchao! I'll take a look

**Comment by mattdangerw** [comment]
Thanks @abheesht17 !

**Comment by mattdangerw** [comment]
Also just looked at the guide more closely. One guess at what is happening is that the `encoder_input_tokens` (which is passed by closure) and the `prompt` (which is passed by the sampler), have different batch axis shape, because we have to add beams to the `prompt` shape during sampling.

If that's the case, the simple fix would be to add a line like this before using `encoder_input_tokens` in the `next` callback....
```python
encoder_input_tokens = tf.repeat(encoder_input_tokens, num_beams, axis=0)
```

But I agree that's a bit of a tricky gotcha. I wonder if there is something more user friendly we can do here... Our next release is going to be focused on seq2seq cases so good time for this!

**Comment by abheesht17** [comment]
@mattdangerw - yeah, that should work!

Here is an old notebook which does something similar: https://colab.research.google.com/drive/1jtIRbIt0xqN-yqlfNUwlKAeavg4OO0WT#scrollTo=zdKyqn5goO2e. Please check the `token_probability_fn()`, that should help. @hakim770 - you can mirror the same changes in your `next()` function. Hope this helps!

**Comment by sachinprasadhs** [comment]
@hakim770, PTAL the above comments and spare some time to mark this issue as closed if you don't have any more questions. Thanks!

**Comment by hakim770** [comment]
Thank you so much. The issue is solved.
