### ISSUE TITLE
keras_cv.models.RetinaNet.from_preset fails under Windows 10 WSL Ubuntu anaconda

### ISSUE THREAD

**Issue by fiammante** [keras-team/keras-io#1382]
Hello, I am trying to use keras_cv/object_detection_keras_cv.py code in a Jupyter notebook running is Windows 10 WSL Ubuntu.
It fails to load the pretrained model which is at the beginning of the code.
Note that I remove "import resource" that does not exist under Windows. Here is the trace:

ValueError                                Traceback (most recent call last)
Cell In[8], line 1
----> 1 pretrained_model = keras_cv.models.RetinaNet.from_preset("retinanet_resnet50_pascalvoc", bounding_box_format="xywh")

File c:\users\admin-17417\appdata\local\programs\python\python39\lib\site-packages\keras_cv\models\task.py:164, in Task.__init_subclass__.<locals>.from_preset(calling_cls, *args, **kwargs)
    163 def from_preset(calling_cls, *args, **kwargs):
--> 164     return super(cls, calling_cls).from_preset(*args, **kwargs)

File c:\users\admin-17417\appdata\local\programs\python\python39\lib\site-packages\keras_cv\models\task.py:152, in Task.from_preset(cls, preset, load_weights, **kwargs)
    143     local_weights_path = "model.weights.h5"
    145 weights = keras.utils.get_file(
    146     local_weights_path,
    147     metadata["weights_url"],
    148     cache_subdir=os.path.join("models", preset),
    149     file_hash=metadata["weights_hash"],
    150 )
--> 152 model.load_weights(weights)
    153 return model

File c:\users\admin-17417\appdata\local\programs\python\python39\lib\site-packages\keras\utils\traceback_utils.py:70, in filter_traceback.<locals>.error_handler(*args, **kwargs)
     67     filtered_tb = _process_traceback_frames(e.__traceback__)
     68     # To get the full stack trace, call:
     69     # `tf.debugging.disable_traceback_filtering()`
---> 70     raise e.with_traceback(filtered_tb) from None
     71 finally:
     72     del filtered_tb

File c:\users\admin-17417\appdata\local\programs\python\python39\lib\site-packages\keras\engine\base_layer.py:3513, in Layer._load_own_variables(self, store)
   3511 all_vars = self._trainable_weights + self._non_trainable_weights
   3512 if len(store.keys()) != len(all_vars):
-> 3513     raise ValueError(
   3514         f"Layer '{self.name}' expected {len(all_vars)} variables, "
   3515         "but received "
   3516         f"{len(store.keys())} variables during loading. "
   3517         f"Expected: {[v.name for v in all_vars]}"
   3518     )
   3519 for i, v in enumerate(all_vars):
   3520     # TODO(rchao): check shapes and raise errors.
   3521     v.assign(store[f"{i}"])

ValueError: Layer 'conv1_conv' expected 1 variables, but received 0 variables during loading. Expected: ['conv1_conv/kernel:0']

**Comment by sachinprasadhs** [comment]
import resource does not have any dependency, you can run it without that as well.
[Here](https://gist.github.com/sachinprasadhs/84978f40bacb2d61e978dd82d271af3d) is the working colab Gist.

Your issue seems to be specific about WSL build. 
Could you please follow the instructions here https://www.tensorflow.org/install/pip#windows-wsl2 and try with the tensorflow version 2.12 or 2.13rc0

**Comment by fiammante** [comment]
I uninstalled my WSL distro and reinstalled everything as instructed. I added Jupyter to the tf miniconda environment.
Trying from ubuntu command line I get a different error than above. From jupyter environment I get the same error as above.

**Command line tst**
(tf) fiammante@DESKTOP-3AQ037Q:~$python3 -c "import tensorflow as tf; print(tf.config.list_physical_devices('GPU'))"
[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]
(tf) fiammante@DESKTOP-3AQ037Q:~$  python3 -c "import keras_cv; pretrained_model = keras_cv.models.RetinaNet.from_preset("retinanet_resnet50_pascalvoc", bounding_box_format="xywh")"
2023-05-25 17:01:14.076029: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-05-25 17:01:14.947677: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'retinanet_resnet50_pascalvoc' is not defined

**Jupyter notebook cell test**
Num GPUs Available:  0

And same problem reported above initially. It seems the environment in a Jupyter notebook lauched from Ubuntu is not the same than from command line.

**Comment by fiammante** [comment]
Reinstalled notebook and then added missing packages to miniconda one by one. I finally got it to work. There seems to be 2 versions of notebook available when running under WSL even if anaconda has not been installed under Windows. Had to install several packages on top of miniconda to get it to work.
