### ISSUE TITLE
`transformer_asr.py`: positional embedding unutilized in source CNN downsampler.

### ISSUE THREAD

**Issue by MicahDoo** [keras-team/keras-io#1394]
# Issue
As stated in the title, the positional embedding `self.pos_emb` in the class `SpeechFeatureEmbedding` is initialized but not used, apparently. This is a curious case, though, as it seems the model is still able to perform well without the positional embedding. Makes me wonder if CNNs are able to extract certain positional information into their outputs.

# Problem Code

```python
class SpeechFeatureEmbedding(layers.Layer):
    def __init__(self, num_hid=64, maxlen=100):
        super().__init__()
        self.conv1 = tf.keras.layers.Conv1D(
            num_hid, 11, strides=2, padding="same", activation="relu"
        )
        self.conv2 = tf.keras.layers.Conv1D(
            num_hid, 11, strides=2, padding="same", activation="relu"
        )
        self.conv3 = tf.keras.layers.Conv1D(
            num_hid, 11, strides=2, padding="same", activation="relu"
        )
        self.pos_emb = layers.Embedding(input_dim=maxlen, output_dim=num_hid)

    def call(self, x):
        x = self.conv1(x)
        x = self.conv2(x)
        return self.conv3(x)
```
Lastly, I would like to extend a thank you to @apoorvnandan for creating this code example. It has been a great resource for leaning.

**Comment by SuryanarayanaY** [comment]
Hi @MicahDoo ,

I hope you are referring to this [transformer_asr](https://keras.io/examples/audio/transformer_asr/) tutorial right ?

I have gone through the code and observed that positional embedding initialized but not utilized for `SpeechFeatureEmbedding` as you have reported.

CC'ing the author @apoorvnandan for requesting more details.

**Comment by 6994bp** [comment]
Unsubscribe Sent from my iPhoneOn Jun 7, 2023, at 10:05 AM, SuryanarayanaY ***@***.***> wrote:﻿
Hi @MicahDoo ,
I hope you are referring to this transformer_asr tutorial right ?
I have gone through the code and observed that positional embedding initialized but not utilized for SpeechFeatureEmbedding as you have reported.
CC'ing the author @apoorvnandan for requesting more details.
