### ISSUE TITLE
Handwriting recognition link out of date (git.io is no longer available)

### ISSUE THREAD

**Issue by grasskin** [keras-team/keras-io#1399]
For the [handwriting recognition](https://keras.io/examples/vision/handwriting_recognition/) tutorial it seems that the dataset link (https://git.io/J0fjL) is no longer available since git.io shut down. @sayakpaul @AakashKumarNain would you be able to update the dataset instructions with a new link or happen to have the original file redirect available? Otherwise we could update instructions to reflect an alternative way of getting the data.

Thank you for the contribution!

**Comment by AakashKumarNain** [comment]
Thank you for pointing it out @grasskin I will take a look into it tonight

**Comment by AakashKumarNain** [comment]
@sayakpaul ^

**Comment by sachinprasadhs** [comment]
It looks like user needs to login to download the data, here is the link to it https://fki.tic.heia-fr.ch/databases/download-the-iam-handwriting-database

**Comment by AakashKumarNain** [comment]
@grasskin @sachinprasadhs here is the new link: [https://github.com/sayakpaul/Handwriting-Recognizer-in-Keras/releases/download/v1.0.0/IAM_Words.zip](https://github.com/sayakpaul/Handwriting-Recognizer-in-Keras/releases/download/v1.0.0/IAM_Words.zip)

I can send a PR during the weekend but if you want to update it, I am okay with that as well

**Comment by sachinprasadhs** [comment]
Thanks for the link, I have created the PR.

**Comment by AakashKumarNain** [comment]
Thank you
