### ISSUE TITLE
Possible bug with TFT5MainLayer

### ISSUE THREAD

**Issue by seungjun-green** [keras-team/keras-io#1411]
Okay following this [Keras Tutorial](https://keras.io/examples/nlp/t5_hf_summarization/) I was fine-tuning T5 with my custom dataset:

Sometimes model get trained with no problems, but doing hyper parameter(with same dataset ) tuning sometimes I got this error message.(and sometimes I does not appear).

```
WARNING:root:No label_cols specified for KerasMetricCallback, assuming you want the 'labels' key.
Epoch 1/3
631/631 [==============================] - ETA: 0s - loss: 1.0853/usr/local/lib/python3.10/dist-packages/transformers/generation/tf_utils.py:854: UserWarning: Using `max_length`'s default (20) to control the generation length. This behaviour is deprecated and will be removed from the config in v5 of Transformers -- we recommend using `max_new_tokens` to control the maximum length of the generation.
  warnings.warn(
631/631 [==============================] - 281s 421ms/step - loss: 1.0853 - val_loss: 0.7765 - RougeL: 0.2928
Epoch 2/3
631/631 [==============================] - ETA: 0s - loss: 0.8717
---------------------------------------------------------------------------
InvalidArgumentError                      Traceback (most recent call last)
[<ipython-input-67-b4919f62089f>](https://localhost:8080/#) in <cell line: 10>()
      8 
      9 # For now we will use our test set as our validation_data
---> 10 model.fit(
     11     train_dataset, validation_data=test_dataset, epochs=MAX_EPOCHS, callbacks=callbacks
     12 )

6 frames
[/usr/local/lib/python3.10/dist-packages/transformers/tf_utils.py](https://localhost:8080/#) in check_embeddings_within_bounds(tensor, embed_dim, tensor_name)
    159         tensor_name (`str`, *optional*): The name of the tensor to use in the error message.
    160     """
--> 161     tf.debugging.assert_less(
    162         tensor,
    163         tf.cast(embed_dim, dtype=tensor.dtype),

InvalidArgumentError: Exception encountered when calling layer 'encoder' (type TFT5MainLayer).

The maximum value of input_ids (31898) must be smaller than the embedding layer's input dimension (32128). The likely cause is some problem at tokenization time.
Condition x < y did not hold.
First 3 elements of x:
[21603    10  3318]
First 1 elements of y:
[32128]

Call arguments received by layer 'encoder' (type TFT5MainLayer):
  • input_ids=tf.Tensor(shape=(16, 512), dtype=int32)
  • attention_mask=tf.Tensor(shape=(16, 512), dtype=int32)
  • encoder_hidden_states=None
  • encoder_attention_mask=None
  • inputs_embeds=None
  • head_mask=None
  • encoder_head_mask=None
  • past_key_values=None
  • use_cache=None
  • output_attentions=False
  • output_hidden_states=False
  • return_dict=True
  • training=False
```

Could anyone check out this? Thanks

**Comment by SuryanarayanaY** [comment]
Hi @seungjun-green ,

Thanks you for reaching us. Could you please confirm which hyper parameter you are trying to tune ? Did the error happens at a particular state of hyper parameters. Needs more context to check the root cause. Thanks

**Comment by seungjun-green** [comment]
I tried changing `learning rate` and `batch size`. 
For example this parameter settings worked:
```
MAX_INPUT_LENGTH = 512  
MIN_TARGET_LENGTH = 10 
MAX_TARGET_LENGTH = 128  
BATCH_SIZE = 16 
LEARNING_RATE = 2e-5 
MAX_EPOCHS = 3  
```

But just changing batch size like this

```
MAX_INPUT_LENGTH = 512  
MIN_TARGET_LENGTH = 10 
MAX_TARGET_LENGTH = 128  
BATCH_SIZE = 8
LEARNING_RATE = 2e-5 
MAX_EPOCHS = 3  
```


cased error like above

**Comment by hertschuh** [comment]
Seungjun,

What it looks like (but we would need to check your exact code) is that you're passing inputs that are too long. Those need to be truncated to the maximum length.

This is how this is done in the tutorial:
```python
MAX_INPUT_LENGTH = 1024  # Maximum length of the input to the model
...

def preprocess_function(examples):
    inputs = [prefix + doc for doc in examples["document"]]
    model_inputs = tokenizer(inputs, max_length=MAX_INPUT_LENGTH, truncation=True)
    ...
```
The tokenizer has a max length of 1024 and it truncates if it's longer.

Note that the changing of the batch size is not the root cause. It's just that the items from the dataset that are passed to the model are randomized, so whenever you encounter one that's too long, that's when it fails. So different runs of the same code can fail at different times.

Thanks,
Fabien

**Comment by seungjun-green** [comment]
Thanks for the comment, but I already did the truncation. Here's my full code https://colab.research.google.com/drive/1sXRgoYmPHm6IfQvMDTyeG-WcQ-ik-Fvq?usp=sharing

**Comment by seungjun-green** [comment]
I tried running the [Google Colab page](https://colab.research.google.com/github/keras-team/keras-io/blob/master/examples/nlp/ipynb/t5_hf_summarization.ipynb) in the Keras tutorial page, and got faced with this error.(Only some change I made is reducing the data size in to 1/10 to increase the training speed, and increasing the epoch to 3 from 1).

Seems like there's some bug in Keras API?

```
WARNING:root:No label_cols specified for KerasMetricCallback, assuming you want the 'labels' key.
Epoch 1/3
255/255 [==============================] - 338s 1s/step - loss: 3.2368 - val_loss: 2.8066 - RougeL: 0.1525
Epoch 2/3
255/255 [==============================] - 313s 1s/step - loss: 2.9727 - val_loss: 2.7293 - RougeL: 0.1595
Epoch 3/3
255/255 [==============================] - ETA: 0s - loss: 2.8985
---------------------------------------------------------------------------
InvalidArgumentError                      Traceback (most recent call last)
[<ipython-input-20-fcc4c399d17a>](https://localhost:8080/#) in <cell line: 10>()
      8 
      9 # For now we will use our test set as our validation_data
---> 10 model.fit(
     11     train_dataset, validation_data=test_dataset, epochs=MAX_EPOCHS, callbacks=callbacks
     12 )

11 frames
[/usr/local/lib/python3.10/dist-packages/transformers/models/t5/modeling_tf_t5.py](https://localhost:8080/#) in _relative_position_bucket(relative_position, bidirectional, num_buckets, max_distance)
    275         )
    276         relative_position_if_large = tf.math.minimum(relative_position_if_large, num_buckets - 1)
--> 277         relative_buckets += tf.where(is_small, relative_position, relative_position_if_large)
    278         return relative_buckets
    279 

InvalidArgumentError: Exception encountered when calling layer 'SelfAttention' (type TFT5Attention).

{{function_node __wrapped__AddV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} Incompatible shapes: [8,42] vs. [1024,1024] [Op:AddV2]

Call arguments received by layer 'SelfAttention' (type TFT5Attention):
  • hidden_states=tf.Tensor(shape=(8, 1024, 512), dtype=float32)
  • mask=tf.Tensor(shape=(8, 1, 1, 1024), dtype=float32)
  • key_value_states=None
  • position_bias=None
  • past_key_value=None
  • layer_head_mask=None
  • query_length=None
  • use_cache=False
  • training=False
  • output_attentions=False
```

**Comment by hertschuh** [comment]
Hi @seungjun-green ,

I ran the Colab for the original Keras tutorial using the full dataset. It succeeded multiple times and failed once in the way you posted above. This is very strange as it means the behavior is inconsistent despite the fact that we're using the whole dataset.

What is apparent though, is that the issue happens somewhere deep in the T5 transformer code from Huggingface. In this tutorial, Keras is merely used as a wrapper to perform the training. I'm not sure where to go from this as the Huggingface code is really not familiar to us.

Thanks, Fabien

**Comment by SuryanarayanaY** [comment]
Hi @seungjun-green ,

I think the issue might be with data loader API which in this case is from Hugging Face itself. Keras here only used that data loader API and tried to train the data it received. I also tried executing the tutorial as it is and its worked fine as per [gist](https://colab.sandbox.google.com/gist/SuryanarayanaY/b0d4f57d7a666671d79632d7f510b9fa/kerasio_1411-summarization.ipynb).

In `tf.data.Dataset.batch` we have option like `drop_reminder=True` which might fix the issue with variable batch_size. Could you please check the hugging face API for such options. AFAIK the issue is from Hugging face API. Could you please report the issue there and let us know the outcome.

Thanks!

**Comment by ayalaall** [comment]
I also encountered the same issue.
