### ISSUE TITLE
Broken image links in object_detection_keras_cv.py 

### ISSUE THREAD

**Issue by shuaixr** [keras-team/keras-io#1453]
The first two image link in [https://keras.io/guides/keras\_cv/object\_detection\_keras\_cv/](https://keras.io/guides/keras\_cv/object\_detection\_keras\_cv/) is broken.

**Comment by sachinprasadhs** [comment]
Hi, 

Thanks for reporting the issue.

I was able to see the image correctly populated in the tutorial and below is the screenshot of it.
![image](https://github.com/keras-team/keras-io/assets/73069040/e8852a40-4cf9-44b9-9650-07e1c50e9b3c)

If I have missed something, could you please point me to the broken link. Thanks!
