### ISSUE TITLE
Broken dataset download link in "Point cloud segmentation with PointNet"

### ISSUE THREAD

**Issue by CristianoPizzamiglio** [keras-team/keras-io#1472]
The dataset URL "https://git.io/JiY4i" of the [point cloud segmentation tutorial](https://keras.io/examples/vision/pointnet_segmentation/#downloading-dataset) seems to be broken.

Here is how to reproduce the error (running in [Google Colab](https://colab.research.google.com/github/keras-team/keras-io/blob/master/examples/vision/ipynb/pointnet_segmentation.ipynb)):

```python
dataset_url = "https://git.io/JiY4i"

dataset_path = keras.utils.get_file(
    fname="shapenet.zip",
    origin=dataset_url,
    cache_subdir="datasets",
    hash_algorithm="auto",
    extract=True,
    archive_format="auto",
    cache_dir="datasets",
)
```

```bash
Downloading data from https://git.io/JiY4i
---------------------------------------------------------------------------
HTTPError                                 Traceback (most recent call last)
[/usr/local/lib/python3.10/dist-packages/keras/utils/data_utils.py](https://localhost:8080/#) in get_file(fname, origin, untar, md5_hash, file_hash, cache_subdir, hash_algorithm, extract, archive_format, cache_dir)
    345             try:
--> 346                 urlretrieve(origin, fpath, DLProgbar())
    347             except urllib.error.HTTPError as e:

8 frames
HTTPError: HTTP Error 502: Bad Gateway

During handling of the above exception, another exception occurred:

Exception                                 Traceback (most recent call last)
[/usr/local/lib/python3.10/dist-packages/keras/utils/data_utils.py](https://localhost:8080/#) in get_file(fname, origin, untar, md5_hash, file_hash, cache_subdir, hash_algorithm, extract, archive_format, cache_dir)
    346                 urlretrieve(origin, fpath, DLProgbar())
    347             except urllib.error.HTTPError as e:
--> 348                 raise Exception(error_msg.format(origin, e.code, e.msg))
    349             except urllib.error.URLError as e:
    350                 raise Exception(error_msg.format(origin, e.errno, e.reason))

Exception: URL fetch failure on https://git.io/JiY4i: 502 -- Bad Gateway
```

**Comment by sachinprasadhs** [comment]
Hi, 

Thanks for reporting the issue.

`Shapenet` has the control over the dataset, To download `ShapeNet` data you need to be a registered user. 
Till we figure out the way to fix the dataset issue, could you please sign up here https://shapenet.org/ and download `ShapeNetCore` once your request is approved. Thanks

**Comment by CristianoPizzamiglio** [comment]
Hi, thank you! I have already signed up, but I am still waiting for the request to be approved, fingers crossed!

**Comment by CristianoPizzamiglio** [comment]
I was granted access to the Shapenet dataset!

**Comment by kunaltilaganji** [comment]
Does having an account on ShapeNet mean it is been approved or do I have to mail someone about it.
Cause I am not able to access the links provided on this page " https://shapenet.org/download/shapenetcore".

**Comment by CristianoPizzamiglio** [comment]
Hi @kunaltilaganji!
Having an account does not mean that you are granted access to the dataset. You need to wait for an e-mail by the website administrator.
