### ISSUE TITLE
The Example in Object Detection is broken

### ISSUE THREAD

**Issue by smoshie25** [keras-team/keras-io#1476]
The example [here](https://keras.io/guides/keras_cv/object_detection_keras_cv/) is broken 
Loading Image fails:

`filepath = tf.keras.utils.get_file(origin="https://i.imgur.com/gCNcJJI.jpg")
image = keras.utils.load_img(filepath)
image = np.array(image)

visualization.plot_image_gallery(
    [image],
    value_range=(0, 255),
    rows=1,
    cols=1,
    scale=5,
)`

with error: AttributeError: 'list' object has no attribute 'shape'

<img width="983" alt="Screenshot 2023-08-10 105919" src="https://github.com/keras-team/keras-io/assets/5700766/b3c4e0ba-0a02-4e04-ace0-ecdf4ab00706">

or this error: `plot_images_gallery()` requires you to batch your `np.array` samples together.

<img width="1002" alt="Screenshot 2023-08-10 105957" src="https://github.com/keras-team/keras-io/assets/5700766/92930237-930d-48bb-8e9e-060b709b14e9">

**Comment by rbardon** [comment]
Just an easy fix:

filepath = tf.keras.utils.get_file(origin="https://i.imgur.com/gCNcJJI.jpg")
image = keras.utils.load_img(filepath)

visualization.plot_image_gallery(
    image.reshape((1,3024, 4032, 3)),
    value_range=(0, 255),
    rows=1,
    cols=1,
    scale=5,
)

**Comment by sachinprasadhs** [comment]
Hi, 

Thanks for reporting the issue.

The issue has been fixed by the commit here https://github.com/keras-team/keras-io/pull/1478/commits/8d6039241d399db50cff7e9bdf8dff1ab91ff5a5. 
Could you please verify and close the issue.
