### ISSUE TITLE
Duplicate Image Search example with broken link

### ISSUE THREAD

**Issue by under-score** [keras-team/keras-io#1492]
The example [https://github.com/keras-team/keras-io/blob/master/examples/vision/near_dup_search.py](https://github.com/keras-team/keras-io/blob/master/examples/vision/near_dup_search.py)
does not work due to a broken link to the dataset
`!wget -q https://git.io/JuMq0 -O flower_model_bit_0.96875.zip`
Fortunately the model can be recreated here [https://github.com/sayakpaul/near-dup-parser/blob/main/bit-supervised-training.ipynb](https://github.com/sayakpaul/near-dup-parser/blob/main/bit-supervised-training.ipynb)

**Comment by sachinprasadhs** [comment]
Hi,

Thanks for reporting the issue.

I was able to make some changes like loading the pre-trained model from TF-Hub  and run the notebook successfully.

Please refer the below Colab till we make the changes in the example document.

https://gist.github.com/sachinprasadhs/d1672b5badfa9df9b07786ab2dfa3cc0

**Comment by under-score** [comment]
million thanks

**Comment by sachinprasadhs** [comment]
Hi, 

The PR has been merged with only change to the pre-trained model link https://github.com/keras-team/keras-io/pull/1508.
You can refer the PR and close the issue. Thanks!
