### ISSUE TITLE
AttributeError: module 'tensorflow.keras.layers.experimental.preprocessing' has no attribute 'StringLookup'

### ISSUE THREAD

**Issue by moje01konto** [keras-team/keras-io#150]
on 97 line error
./captcha_ocr.py

https://keras.io/examples/vision/captcha_ocr/

**Comment by cknotz** [comment]
Just stumbled over the same bug. 

I can `import from tensorflow.keras.layers import experimental`, but importing the `preprocessing` feature does not seem to work. I can accordingly also not import the `Normalization`, `StringLookup` and `CategoryEncoding` layers.

**Comment by hiteshcoder** [comment]
Same error , StringLookup doesnt seem to work

**Comment by gabriel-fsa** [comment]
It's working for me, I'm using TF 2.3.1.

**Comment by SuryanarayanaY** [comment]
Hi @moje01konto ,

We are in the process of clearing backlog issues. I have gone through this issue and this is no more a problem now. I have executed the code successfully and attached [gist](https://colab.research.google.com/gist/SuryanarayanaY/94207aea3c8e2f0c247845995c4d3303/captcha_ocr.ipynb) for reference.

Please verify and feel free to close the issue. Thanks!
