### ISSUE TITLE
[Question] Implementing one-to-many LSTM in Keras.

### ISSUE THREAD

**Issue by seungjun-green** [keras-team/keras-io#1517]
Hello, I'm learning Deep Learning and wondering is it possible to implement one-to-many LSTM in Keras.?

Thinking as follow I concluded it's not possible to do it, Could anyone know me whether I think correctly? :

LSTM in Keras have input shape of `(None, sequence_length, vocab_size)` and then it got splitted to `sequence_length` number of `(None, vocab_size)`, then each of these got feed into each cell of LSTM. But in one-to-many providing `(None, sequence_length, vocab_size)` is not possible in first place, since the input shape of one-to-many LSTM is `(None, 1, vocab_size)`.

**Comment by divyashreepathihalli** [comment]
Hi @seungjun-green!
here is a tutorial for using one to many LSTM in keras - https://wandb.ai/ayush-thakur/dl-question-bank/reports/LSTM-RNN-in-Keras-Examples-of-One-to-Many-Many-to-One-Many-to-Many---VmlldzoyMDIzOTM#what-are-many-to-one-sequence-problems?

I hope this is helpful!

**Comment by seungjun-green** [comment]
Thanks! :)
