### ISSUE TITLE
AttributeError: 'DataFrame' object has no attribute 'append'

### ISSUE THREAD

**Issue by mikechen66** [keras-team/keras-io#1518]
For masked_language_modeling.ipynb, there is the error.  My system is Python 3.10, TensorFlow 2.13 and pandas 2.03. 

It reminds the warning:  FutureWarning: The frame.append method is deprecated and will be removed from pandas  in a future version. Use pandas.concat instead.

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/tmp/ipykernel_97675/3156859266.py in ?()
     27 
     28 # FutureWarning: The frame.append method is deprecated and will be removed from pandas
     29 # in a future version. Use pandas.concat instead.
     30 # https://stackoverflow.com/questions/75956209/error-dataframe-object-has-no-attribute-append
---> 31 all_data = train_df.append(test_df)

~/miniconda3/envs/tf/lib/python3.10/site-packages/pandas/core/generic.py in ?(self, name)
   5985             and name not in self._accessors
   5986             and self._info_axis._can_hold_identifiers_and_holds_name(name)
   5987         ):
   5988             return self[name]
-> 5989         return object.__getattribute__(self, name)

AttributeError: 'DataFrame' object has no attribute 'append'

**Comment by sachinprasadhs** [comment]
Hi,

I was able to run `End-to-end Masked Language Modeling with BERT` without any error or warning. 
[Here](https://gist.github.com/sachinprasadhs/82341fc673c1e1de394b45a8964a6ca9) is the attached Gist for reference. Thanks!

**Comment by skon7** [comment]
I believe the error may be related to your Pandas version. However, in Pandas 2.0, the 'append' method has been deprecated. 
You have a few options to resolve this:
- You can install the Pandas version to one that supports the 'append' method.
- Or replace 'append' with '_append' if it's suitable for your code.
- Or use the 'concat' function instead. Please note that the syntax for 'concat' will change, and you'll need to modify your code to use it like this: 'pd.concat( [train_df, test_df], ignore_index=True).'

@qlzh727 @fchollet (i make a PR about this issue #1525 )
