### ISSUE TITLE
IndexError: index 1 is out of bounds for axis 0 with size 1

### ISSUE THREAD

**Issue by mikechen66** [keras-team/keras-io#1520]
xray_classification_with_tpus.ipynb

show_batch(image_batch.numpy(), label_batch.numpy())

---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
[<ipython-input-12-126ed6a30af5>](https://localhost:8080/#) in <cell line: 1>()
----> 1 show_batch(image_batch.numpy(), label_batch.numpy())

[<ipython-input-11-30f57ec49191>](https://localhost:8080/#) in show_batch(image_batch, label_batch)
      3     for n in range(25):
      4         ax = plt.subplot(5, 5, n + 1)
----> 5         plt.imshow(image_batch[n] / 255)
      6         if label_batch[n]:
      7             plt.title("PNEUMONIA")

IndexError: index 1 is out of bounds for axis 0 with size 1

**Comment by SuryanarayanaY** [comment]
Hi @mikechen66 ,

The example is working fine without any error. Please refer to the attached [gist](https://colab.sandbox.google.com/gist/SuryanarayanaY/1f8a9a072f95704982557179503bdece/kerasio_1520_xray_classification_with_tpus.ipynb) here.

Could you please confirm whether you have done any changes to the code ?
