### ISSUE TITLE
InvalidArgumentError

### ISSUE THREAD

**Issue by mikechen66** [keras-team/keras-io#1527]
simSiam.ipynb
Self-supervised contrastive learning with SimSiam

While I run the simsiam on Colab T4 16G graphical memory , ther is the error as follows.  Please help handle the issue. 

InvalidArgumentError                      Traceback (most recent call last)
[<ipython-input-5-664c62dc733a>](https://localhost:8080/#) in <cell line: 23>()
     23 for n in range(25):
     24     ax = plt.subplot(5, 5, n + 1)
---> 25     plt.imshow(sample_images_one[n].numpy().astype("int"))
     26     plt.axis("off")
     27 plt.show()

1 frames
[/usr/local/lib/python3.10/dist-packages/tensorflow/python/framework/ops.py](https://localhost:8080/#) in raise_from_not_ok_status(e, name)
   6654 def raise_from_not_ok_status(e, name):
   6655   e.message += (" name: " + str(name if name is not None else ""))
-> 6656   raise core._status_to_exception(e) from None  # pylint: disable=protected-access
   6657 
   6658 

InvalidArgumentError: {{function_node __wrapped__StridedSlice_device_/job:localhost/replica:0/task:0/device:GPU:0}} slice index 8 of dimension 0 out of bounds. [Op:StridedSlice] name: strided_slice/

**Comment by SuryanarayanaY** [comment]
Hi @mikechen66 ,

The tutorial works fine with TF2.13 on colab GPU environment. Please refer attached [gist](https://colab.sandbox.google.com/gist/SuryanarayanaY/87ce1df565facdd98c2af9116a29ec18/1527-simsiam.ipynb).

Either it might have fixed already or you might be changing some changes to the code that causing out of bounds error.

Could you please verify the gist and confirm? Thanks!
