### ISSUE TITLE
ValueError: Image data must be a sequence of ndimages.

### ISSUE THREAD

**Issue by mikechen66** [keras-team/keras-io#1528]
video_classification
video_classification.ipynb

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[11], line 36
     34 print(f"Test video path: {test_video}")
     35 test_frames = sequence_prediction(test_video)
---> 36 to_gif(test_frames[:MAX_SEQ_LENGTH])

Cell In[11], line 29, in to_gif(images)
     27 def to_gif(images):
     28     converted_images = images.astype(np.uint8)
---> 29     imageio.mimsave("animation.gif", converted_images, fps=10)
     30     return embed.embed_file("animation.gif")

File ~/miniconda3/envs/tf/lib/python3.10/site-packages/imageio/v2.py:490, in mimwrite(uri, ims, format, **kwargs)
    470 """mimwrite(uri, ims, format=None, **kwargs)
    471 
    472 Write multiple images to the specified file.
   (...)
    486     to see what arguments are available for a particular format.
    487 """
    489 if not is_batch(ims):
--> 490     raise ValueError("Image data must be a sequence of ndimages.")
    492 imopen_args = decypher_format_arg(format)
    493 imopen_args["legacy_mode"] = True

ValueError: Image data must be a sequence of ndimages.

**Comment by SuryanarayanaY** [comment]
Hi @mikechen66 ,

I have tested the video_classification tutorial in Tf21.3v and its working fine. Could you please verify the attached [gist](https://colab.sandbox.google.com/gist/SuryanarayanaY/1aa10c314c268a1a46b49b6f7eaa41ca/kerasio_1528_video_classification.ipynb) and confirm whether we mark it as closed?

Thank you!
