### ISSUE TITLE
Generator architecture flipped in the DCGAN?

### ISSUE THREAD

**Issue by jchwenger** [keras-team/keras-io#1543]
Hi,

This is less an issue than a technical question.

I notice that the [Generator in the DCGAN tutorial](https://keras.io/examples/generative/dcgan_overriding_train_step/#create-the-generator) example has the depth logic of its architecture reversed compared to the paper (with number of channels being 128, 256, 512), rather than being deep first (512, 256, 128), and was wondering what was the motivation behind it?

(I find "deep-first" examples in the [TensorFlow tutorial](https://www.tensorflow.org/tutorials/generative/dcgan#the_generator), or the [PyTorch one](https://pytorch.org/tutorials/beginner/dcgan_faces_tutorial.html#generator).)

I can imagine this follows one of the many tricks around GANs, I just haven't seen this before, any pointers would be greatly appreciated!
Thanks!

**Comment by fchollet** [comment]
There is no profound motivation behind it -- it's just a hyperparameter. You can do the reverse, or you can do constant depth as well. Just go with what works best for your dataset (which might be tricky to evaluate automatically in the case of a GAN -- you may want to look at the generated images and make your own decision).

**Comment by jchwenger** [comment]
Thanks for this!
