### ISSUE TITLE
Problem training EfficientNetB0 on CIFAR-10 with a minimal code (same code works with MobileNet)

### ISSUE THREAD

**Issue by dkobak** [keras-team/keras-io#1549]
I tried to make a simplified version of https://keras.io/examples/vision/image_classification_efficientnet_fine_tuning/ (@yixingfu) using the CIFAR-10 dataset. My problem is that my code works fine with `MobileNet` but fails with `EfficientNetB0` in a very strange way.

Here is my entire code (I tried to make it as bare-bones as possible):
```Python
from tensorflow import keras
from tensorflow.keras.applications import EfficientNetB0, MobileNet

# Get CIFAR-10 data
(x_train, y_train), (x_test, y_test) = keras.datasets.cifar10.load_data()
x_train = x_train.astype("float32") / 255
x_test = x_test.astype("float32") / 255
y_train = keras.utils.to_categorical(y_train, 10)
y_test = keras.utils.to_categorical(y_test, 10)

# Pipeline
def finetune(backbone):
    model = keras.Sequential(
        [
            keras.Input(shape=(32, 32, 3)),
            keras.layers.Resizing(224, 224),
            backbone,
            keras.layers.GlobalAveragePooling2D(),
            keras.layers.Dense(10, activation="softmax"),
        ]
    )

    model.compile(loss="categorical_crossentropy", optimizer="adam", metrics=["accuracy"])
    model.fit(x_train, y_train, batch_size=64, epochs=3, validation_split=0.1)

backbone = MobileNet(weights='imagenet', include_top=False, input_shape=(224, 224, 3))
finetune(backbone)

backbone = EfficientNetB0(weights='imagenet', include_top=False) 
finetune(backbone)
```
This works fine with `MobileNet` and reaches around ~90% validation accuracy.
```
Epoch 1/3
704/704 [==============================] - 77s 75ms/step - loss: 0.4693 - accuracy: 0.8449 - val_loss: 0.6687 - val_accuracy: 0.8218
Epoch 2/3
704/704 [==============================] - 51s 72ms/step - loss: 0.2463 - accuracy: 0.9148 - val_loss: 0.3480 - val_accuracy: 0.8856
Epoch 3/3
704/704 [==============================] - 51s 72ms/step - loss: 0.1771 - accuracy: 0.9393 - val_loss: 0.4632 - val_accuracy: 0.8570
```
However, with `EfficientNetB0` validation accuracy remains at chance level (10%) even though the training accuracy gets to 90% in 1 epoch. I don't understand how this is possible, as there can be no overfitting within 1 epoch. Can it be that `EfficientNetB0` does something differently for validation data?
```
Epoch 1/3
704/704 [==============================] - 174s 186ms/step - loss: 0.3619 - accuracy: 0.8788 - val_loss: 2.6939 - val_accuracy: 0.0986
Epoch 2/3
704/704 [==============================] - 129s 184ms/step - loss: 0.1826 - accuracy: 0.9386 - val_loss: 2.9033 - val_accuracy: 0.1504
Epoch 3/3
704/704 [==============================] - 127s 181ms/step - loss: 0.1379 - accuracy: 0.9520 - val_loss: 2.7110 - val_accuracy: 0.0786
```

This is not about fine-tuning the ImageNet weights. If I initialize all weights randomly (`weights=None` instead of `weights='imagenet'`), I get the same problem: `MobileNet` trains, `EfficientNetB0` keeps showing 10% validation (and test) accuracy even though training accuracy does keep growing. What am I doing wrong?

**Comment by innat** [comment]
You scale your data 

```
x_train = x_train.astype("float32") / 255
x_test = x_test.astype("float32") / 255
```

and import model from `applications import EfficientNetB0` which has [built-in rescale](https://github.com/keras-team/keras/blob/68f9af408a1734704746f7e6fa9cfede0d6879d8/keras/applications/efficientnet.py#L357-L358) method, (bad design).  All you need to do is to remove rescaling (div by 255), everything you use this model. Later, for the keras-cv-efficientnet, there probably would be available  `include_rescaling`, boolean param to control it.

**Comment by dkobak** [comment]
Wow. Thank you!!

I can confirm that deleting these two lines of code makes everything work as expected:
```
Epoch 1/3
704/704 [==============================] - 184s 188ms/step - loss: 0.3341 - accuracy: 0.8872 - val_loss: 0.2510 - val_accuracy: 0.9146
```

But I don't think I understand why I had those symptoms before: why was the training accuracy getting high while validation accuracy stayed low? Is the built-in rescaling somehow applied differently to the training set and to the validation set?

And why is it not an issue with MobileNet? It seems to work fine with explicit rescaling to [0,1] but also without explicit rescaling.

I now noticed that https://keras.io/api/applications/efficientnet/ does say
> EfficientNet models expect their inputs to be float tensors of pixels with values in the [0-255] range.
I just did not notice it before :-(

**Comment by innat** [comment]
It was reported but for some reason no action was taken 
https://github.com/keras-team/keras/issues/16081

> But I don't think I understand why I had those symptoms before: why was the training accuracy getting high while validation accuracy stayed low? Is the built-in rescaling somehow applied differently to the training set and to the validation set?

It's simply overfitting or whatever, don't waste time same as I did. There is no knowledge. 


You won't see this with other model, i.e. MobileNet. None of the preceding models have this issue. Also note, In [effnet-v2](https://keras.io/api/applications/efficientnet_v2/#efficientnetv2b0-function), there is an arg called `include_preprocessing` which controls this behaviour. 

Lastly, this `include_preprocessing` is added to every models in keras-cv models which will be only source to import vision models.

**Comment by dkobak** [comment]
> It's simply overfitting or whatever, don't waste time same as I did. There is no knowledge.

Hmm. It does not really look like overfitting to me because it happens after 1 single epoch... Strange effect.

I think maybe it's something related to the BatchNormalization layers that behave differently during training and in the inference mode (for validation)?.. No idea.

Anyway, I agree that it may be not worth trying to figure it out.

Thanks again for your help! I can close this issue now.

**Comment by mcagriaksoy** [comment]
Hello, I am using same model with similar config. When I remove the `"/255"` part I have faced an error on `model.fit` stage.
The error: `"ValueError: Images of type float must be between -1 and 1."`

Have you faced it? @dkobak

**Comment by dkobak** [comment]
@mcagriaksoy No I didn't. But I think I was using Keras 2 back then, you may be using Keras 3 now, so perhaps something changed.
