### ISSUE TITLE
Question about outer_model in end-to-end example(hypernetwork).

### ISSUE THREAD

**Issue by rickiepark** [keras-team/keras-io#156]
In intro_to_keras_for_researchers.py

```
Let's implement a really trivial hypernetwork: we'll use a small 2-layer network 
to generate the weights of a larger 3-layer network.
```

But outer_model actually has 2 layers.

```
outer_model = keras.Sequential(
    [keras.layers.Dense(64, activation=tf.nn.relu), keras.layers.Dense(classes),]
)
```

I think that it's better to change text(larger 3-layer --> 2-layer) or add a layer to outer_model like this:

```
outer_model = keras.Sequential(
    [keras.layers.Dense(64, activation=tf.nn.relu), 
     keras.layers.Dense(32, activation=tf.nn.relu), 
     keras.layers.Dense(classes),]
)
```

Thanks

**Comment by sachinprasadhs** [comment]
Hi,

Thanks for reporting the issue, could you please let us know which part are you referring to in the document here https://keras.io/getting_started/intro_to_keras_for_researchers/
