### ISSUE TITLE
browser saying: Your connection isn't private

### ISSUE THREAD

**Issue by Aydinhamedi** [keras-team/keras-io#1599]
When I go to https://keras.io its saying Your connection isn't private I tried it in the Chrome and Edge the same problem, but it works in Firefox I think because it uses a different search engine.

**Comment by sachinprasadhs** [comment]
Hi,

Thanks for reporting the issue.

I have tried it in my chrome browser, I don't see any issue.
Could you please try upgrading the chrome and check again.

**Comment by Aydinhamedi** [comment]
My chrome browser version:
Chrome is up to date
Version 119.0.6045.124 (Official Build) (64-bit)

**Comment by Aydinhamedi** [comment]
Some images:
![image](https://github.com/keras-team/keras-io/assets/108932477/739c5a20-bf24-4ee8-b095-885432b0df44)
![image](https://github.com/keras-team/keras-io/assets/108932477/0123cfc3-8cfd-4389-ae1e-e62e227a85a0)

**Comment by sachinprasadhs** [comment]
Thanks, did you try this in different system?

**Comment by sachinprasadhs** [comment]
@MarkDaoust , @pcoet , Do you think it is related to website SSL certificate?

**Comment by Aydinhamedi** [comment]
Thanks. I tried it on my laptop, and it worked, so what is the problem with my PC browser?

**Comment by sachinprasadhs** [comment]
This seems specific to your system browser or some certificate related issue, since we haven't seen any such reports before related to keras.io. 
To confirm the issue related to your browser, you can check some other website and validate if same issue persists.

**Comment by Aydinhamedi** [comment]
No its only on keras.io
the error: 
NET::ERR_CERT_AUTHORITY_INVALID

**Comment by sachinprasadhs** [comment]
Could you please verify your system date is set to current date?

**Comment by Aydinhamedi** [comment]
no its not the date i tried Clearing the SSL state too.

**Comment by Aydinhamedi** [comment]
I close the issue because it looks like to not be a keras.io problem its on my device i troubleshoot by my self.
