### ISSUE TITLE
Code example for unsupervised learning

### ISSUE THREAD

**Issue by anish9** [keras-team/keras-io#163]
@fchollet  Hi, I was just wondering whether we can showcase an example of image invariant clustering, totally in unsupervised fashion, requires just random noisy data, eventually learns to sort by feature wise.

**Comment by pcoet** [comment]
Hi @anish9, thanks for getting in touch. This request is pretty old at this point, and there's no bug involved, so I'm going to go ahead and close the issue. Please feel free to create another issue if this is still relevant.
