### ISSUE TITLE
There is no speed difference between LSTM and CuDNNLSTM according to the training log

### ISSUE THREAD

**Issue by MLightM** [keras-team/keras-io#165]
https://keras.io/guides/working_with_rnns/#rnn-state-reuse

![image](https://user-images.githubusercontent.com/22020620/88623220-1362a780-d0d7-11ea-93b6-1dd4947bb5ad.png)

This is no speed diff according to the training log.

**Comment by MLightM** [comment]
@fchollet @Scott Zhu

**Comment by fchollet** [comment]
Using `LSTM` will use CuDNN whenever possible. It is normal that you see the same timing since you are doing the same thing. Just use `LSTM` instead of the legacy `CuDNNLSTM` class.
