### ISSUE TITLE
Broken doc links: "Writing a custom train step with..."

### ISSUE THREAD

**Issue by choongng** [keras-team/keras-io#1653]
### Issue Type

Documentation Bug

### Source

source

### Keras Version

3.0

### Custom Code

No

### Current Behavior?

Broken links for "Writing a custom train step with..." as well as others going down the page.

### Standalone code to reproduce the issue or tutorial link

```shell
https://keras.io/guides/training_with_built_in_methods/
```

**Comment by sachinprasadhs** [comment]
Hi, Thanks for reporting the issue. 
The issue is fixed in the commit here https://github.com/keras-team/keras-io/commit/b05e4fea65398e2cf18f5380394ddddb377352d3. 
It will take time to reflect in the keras.io, meanwhile, can you verify this and close the issue.

**Comment by choongng** [comment]
Looks right to me.
