### ISSUE TITLE
The data_format in Conv2D need some fix

### ISSUE THREAD

**Issue by dugujiujian1999** [keras-team/keras-io#1686]
### Issue Type

Documentation Bug

### Source

source

### Keras Version

not a keras bug

### Custom Code

No

### Current Behavior?

at Arguments -> data_format
it is now **"channels_last"** corresponds to inputs with shape (batch_size, channels, height, width)
Something is wrong here. 

### Standalone code to reproduce the issue or tutorial link

```shell
https://keras.io/api/layers/convolution_layers/convolution2d/
```

**Comment by SuryanarayanaY** [comment]
Hi @dugujiujian1999 ,

This has been fixed at master already. Please refer the source code of master branch.

https://github.com/keras-team/keras/blob/d550552a0fff734b7b3ccdf3c12c02b5cd81605b/keras/layers/convolutional/conv2d.py#L27

**Comment by dugujiujian1999** [comment]
@SuryanarayanaY Thank you, but the errors on the website have not been fixed yet.

**Comment by SuryanarayanaY** [comment]
Hi @dugujiujian1999 ,

The documentation will get updated in next release. The changes has been fixed at Master only.Current stable release won't have these changes yet.
