### ISSUE TITLE
Incorrect Markdown Rendering of Double Hyphen in Installation Documentation

### ISSUE THREAD

**Issue by LakshmanKishore** [keras-team/keras-io#1696]
### Issue Type

Documentation Bug

### Source

source

### Keras Version

Keras 3

### Custom Code

Yes

## Description:
In the Keras documentation on [getting_started](https://keras.io/getting_started/), the installation command is written with a double hyphen before the "upgrade" option.

However, the double hyphen is being treated as a single hyphen in the rendered text. This might lead to confusion for users trying to copy and paste the command.

## Expected Behavior:
The installation command should render with a double hyphen as intended.

## Additional Information:
* I attempted to use Markdown code blocks (\```bash or ```python) to correct the rendering issue, but the problem persisted.
* Here is the attached screenshot of the issue, This is all over the documentation.:
![image](https://github.com/keras-team/keras-io/assets/61258323/dfabefef-4852-4f85-908e-3b5e8583a177)

Thank you!

### Standalone code to reproduce the issue or tutorial link

```shell
Steps to Reproduce:

1. Visit the installation documentation page on keras.io of getting started.
2. Observe the installation command section.
3. Notice that the double hyphen is not rendering correctly in the Installing Keras section.
```

**Comment by hertschuh** [comment]
It also breaks links in this page, for instance: [TensorFlow + Keras 2 backwards compatibility](https://keras.io/getting_started/#tensorflow--keras-2-backwards-compatibility).

**Comment by LakshmanKishore** [comment]
I'm still not able to see the -- in the documentation.
![image](https://github.com/keras-team/keras-io/assets/61258323/0957539c-bb04-4712-befb-c7e1b488a314)

**Comment by hertschuh** [comment]
@LakshmanKishore 

The site is now redeployed with the fix.

Thanks,
Fabien

**Comment by LakshmanKishore** [comment]
Yes, I am now able to see it.
Thanks!
