### ISSUE TITLE
Can I Use This Code With My Own Dataset?

### ISSUE THREAD

**Issue by enissimsir** [keras-team/keras-io#1700]
### Issue Type

Support

### Source

source

### Keras Version

2.14

### Custom Code

Yes

### Current Behavior?

Can I try this code with my own dataset? I wanna train a model with my dataset and it is not from TFDS

### Standalone code to reproduce the issue or tutorial link

```shell
How should I change here?:
dataset_name = "stanford_dogs"
(ds_train, ds_test), ds_info = tfds.load(
    dataset_name, split=["train", "test"], with_info=True, as_supervised=True
)
NUM_CLASSES = ds_info.features["label"].num_classes
```

**Comment by sachinprasadhs** [comment]
Yes,

You can use any other dataset which can be considered for a classification problem other than TFDS also.

Mae sure you prepare your dataset pipeline according to your dataset which can be feed into the model. 

You can refer this guide for some references: https://keras.io/api/data_loading/
