### ISSUE TITLE
`tf.keras.layers.Attention()` layer - arguments documentation

### ISSUE THREAD

**Issue by 8bitmp3** [keras-team/keras-io#171]
Hey Keras team, I've just discovered a potential Markdown rendering issue in the docs for the `Attention` class (`tf.keras.layers.Attention()`).

Link: https://keras.io/api/layers/attention_layers/attention/

See `Call # Arguments ...`:

<img width="500" alt="image" src="https://user-images.githubusercontent.com/19637339/88980718-34d0b880-d2bc-11ea-98b1-73ec92b2fbe0.png">

**Comment by sachinprasadhs** [comment]
Hi @8bitmp3 , Thanks for reporting the issue, the linked PR has been merged, could you please spare some time to close the issue as well. Thanks!
