### ISSUE TITLE
'Functional' object has no attribute 'parameters'

### ISSUE THREAD

**Issue by AbdelrahimKoura** [keras-team/keras-io#1738]
### Issue Type

Bug

### Source

source

### Keras Version

Keras 3

### Custom Code

No

### OS Platform and Distribution

windows 10 pro version 22H2

### Python version

3.11

### GPU model and memory

cpu

### Current Behavior?

A bug happened!when try to implement guides/writing_a_custom_training_loop_in_torch.py, I got error in line optimizer = torch.optim.Adam(model.parameters(), lr=1e-3)
the error message was" Attribute Error: 'Functional' object has no attribute 'parameters'"

### Standalone code to reproduce the issue or tutorial link

```shell
A bug happened!when try to implement guides/writing_a_custom_training_loop_in_torch.py, I got error in line optimizer = torch.optim.Adam(model.parameters(), lr=1e-3)
the error message was" Attribute Error: 'Functional' object has no attribute 'parameters'"
```

**Comment by sachinprasadhs** [comment]
Hi, 

Thanks for reporting the issue.

I tried it from my side, I was able to run the code successfully, without modifying anything. 
Make sure you have keras version >=3.0.0 installed in your system.

Here is the working Gist for reference [![](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.sandbox.google.com/gist/sachinprasadhs/d73557bd11348b83c475e1fa38075716/writing_a_custom_training_loop_in_torch.ipynb)

**Comment by AbdelrahimKoura** [comment]
Thanks sachinprasadhs i will try it

**Comment by AbdelrahimKoura** [comment]
Thanks
