### ISSUE TITLE
Add example Zero-shot Image Classification with SigLIP / CLIP from scratch using KerasCV and KerasNLP

### ISSUE THREAD

**Issue by awsaf49** [keras-team/keras-io#1752]
### Issue Type

Feature Request

### Source

source

### Keras Version

Keras 3

### Custom Code

Yes

### Current Behavior?

Having an example of Zero-shot Image Classification with SigLIP or CLIP from scratch using both KerasCV and KerasNLP would be a great addition.

I have already published a [notebook](https://www.kaggle.com/code/awsaf49/siglip-clip-from-scratch) on Kaggle using Keras 3.0. I would love to add this example to keras.io.

![Untitled](https://github.com/keras-team/keras-io/assets/36858976/e63fc431-dd3a-40ab-8316-a7e1e613c6a1)

> This example is only having an issue with `jax`, but runs fine with `tensorflow` and `torch`, so it's very close to becoming **backend-agnostic**.

## Reference:
* SigLIP: https://arxiv.org/abs/2303.15343
* CLIP: https://arxiv.org/abs/2103.00020

### Standalone code to reproduce the issue or tutorial link

```shell
```

**Comment by awsaf49** [comment]
cc: @fchollet

**Comment by sachinprasadhs** [comment]
@awsaf49 , Feel free to create a PR with the example, team would be happy to review it.
