### ISSUE TITLE
Questions: Concat, Raster (Satellite data): examples/vision/oxford_pets_image_segmentation.py

### ISSUE THREAD

**Issue by sehHeiden** [keras-team/keras-io#176]
Hi,

 first of all I have a question about the image segmentation example in: examples/vision/oxford_pets_image_segmentation.py.

So fast I understand the in The UNet the output of down sampling is concatenation in the to the up sampling? I just could not find this in the implementation.

I tried to adapt the example to Raster data (multi-band satellite images, but only rgb for the start) . Therefore I 
 adapted the __get_item__ method. To read the satellite image as X and transform the shape from cwh, to whc and normalize it. As y I use a vector file(ESRI Shape format- in this example including polygons for the same region), that has be converted to raster data:

```
    def __getitem__(self, idx):
        """Returns tuple (input, target) correspond to batch #idx."""
        i = idx * self.batch_size
        batch_input_img_paths = self.input_img_paths[i: i + self.batch_size]
        batch_target_img_paths = self.target_img_paths[i: i + self.batch_size]

        x = np.zeros((batch_size,) + img_size + (3,), dtype="float32")
        for j, path in enumerate(input_img_paths[0:batch_size]):
            img = rxa.open_rasterio(path).T.values
            x[j] = img
        x = x / np.iinfo(np.uint16).max
        
        y = np.zeros((self.batch_size,) + self.img_size + (1,), dtype="uint8")
        for j, path in enumerate(batch_target_img_paths):
            img = create_region_of_interest(path, batch_input_img_paths[j], 'class')
            y[j] = np.expand_dims(img, 2)
        return x, y
```
I get the error:

> tensorflow.python.framework.errors_impl.InvalidArgumentError:  logits and labels must have the same first dimension, got logits shape [65536,3] and labels shape [51984]

The lable shape makes sense for my, because it is n*w*h*1 (batch=4, w=h=114). But I cannot figure the dimension of the prediction which is: (UINT16_MAX, 3), with 3 probably being the number of classes. I think, I left everything else rather unchanged

**Comment by pranavjadhav001** [comment]
I agree with @Meresmata,I went across the papers and also some vanilla implementation in different repos, skip connections are an important part of unet which is not considered here

**Comment by pcoet** [comment]
@sehHeiden Thanks for reaching out. This kind of question is probably better suited to one of the forums below. I'll go ahead and close this issue.

* [TensorFlow forum](https://discuss.tensorflow.org/).
* [Keras mailing list](https://groups.google.com/forum/#!forum/keras-users).
