### ISSUE TITLE
kagglecatsanddogs_5340.zip not available to downoad - image_classification_from_scratch.py

### ISSUE THREAD

**Issue by 808vita** [keras-team/keras-io#1806]
### Issue Type

Others

### Source

source

### Keras Version

3.0.5

### Custom Code

Yes

### Python version

3.11

### Current Behavior?

[Image classification from scratch tutorial](https://keras.io/examples/vision/image_classification_from_scratch/)

Raw data download link provided is not working. Tried to visit microsoft site and download from there but still did not work. Issue is with Microsoft server.
![image](https://github.com/keras-team/keras-io/assets/97225946/c25c1f93-695c-40e7-b2b9-8f03ea7690a1)

Can someone provide an alternative link, if it exists.
thanks.

### Standalone code to reproduce the issue or tutorial link

```shell
curl -O https://download.microsoft.com/download/3/E/1/3E1C3F21-ECDB-4869-8368-6DEBA77B919F/kagglecatsanddogs_5340.zip
```

### Relevant log output

```shell
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
curl: (52) Empty reply from server
```

**Comment by sachinprasadhs** [comment]
I was able to successfully download using colab, below is the sample outcome 

![image](https://github.com/keras-team/keras-io/assets/73069040/57986b00-6216-4ec9-93a2-7d1e627f2a2c)
