### ISSUE TITLE
May found logic issue 

### ISSUE THREAD

**Issue by gcowen** [keras-team/keras-io#183]
>     classifier_input = keras.Input(shape=last_conv_layer.output.shape[1:])
>     print(classifier_input.shape)
>     x = classifier_input
>     for layer_name in classifier_layer_names:
>         x = model.get_layer(layer_name)(x)
>     classifier_model = keras.Model(classifier_input, x)

this part when the last layer is not the last convolution layer, the classifier can not connect to the layers before due the shape miss match.

**Comment by sachinprasadhs** [comment]
Hi,

Thanks for reporting the issue.

For better understanding and debugging purpose, could you please provide the link of the document/ example which you are referring to.
