### ISSUE TITLE
How to make individual predictions using the FNet example?

### ISSUE THREAD

**Issue by erickdp** [keras-team/keras-io#1833]
### Issue Type

Support

### Source

source

### Keras Version

Keras 2.14

### Custom Code

Yes

### OS Platform and Distribution

Linux Ubuntu

### Current Behavior?

Once I have used the script for the creation of an FNet network, I want to make predictions on individual entries, however, doing it this way generates an array with several values and there should only be 2. How to make individual predictions using the predict method?

reference: https://keras.io/examples/nlp/fnet_classification_with_keras_nlp/

### Standalone code to reproduce the issue or tutorial link

```shell
When I use predict, I got a vector with shape (32, 3)

fnet_classifier.predict(({"input_ids": [tokenizer("Hi, I'm Erick")]}))
```

**Comment by sachinprasadhs** [comment]
Using the same example when I predicted I got the shape 16,1

```
fnet_classifier.predict(({"input_ids": [tokenizer("Hi, I'm Erick")]})).shape
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
(16, 1)
```
