### ISSUE TITLE
Missing Documentation - `get_config` and serialisation

### ISSUE THREAD

**Issue by idofr** [keras-team/keras-io#184]
Following https://github.com/tensorflow/tensorflow/issues/42004, I have learnt that when righting custom layers and models the `get_config` function is need for better serialisation.
I've finally managed to get my model to work but I think the documentation here is really lacking.
Copying my comment from the original ticket:
```
I still don't really like the way this works. It's not properly documented anyway. Some places just vaguely say that "it's a good practice to implement get_config", but I didn't see any proper explanations.
Furthermore, there's no proper explanation on when a Layer should be used and when a Model would be better.
Finally, even when trying to write the get_config function, no documentation tells you what it should include.
```

Additionally, all examples show the most simplest case. Even when custom layers are explained, they always have a single variable with a predefined value.
I couldn't find a single example showing how to handle custom models, all examples focus on layers.

**Comment by fchollet** [comment]
Please see: https://keras.io/guides/serialization_and_saving/

On the difference between models and layers, see: https://keras.io/guides/making_new_layers_and_models_via_subclassing/#the-model-class
