### ISSUE TITLE
ValueError: The filepath provided must end in `.keras` (Keras model format). Received: filepath=Model_ckpt.h5

### ISSUE THREAD

**Issue by kishan042p** [keras-team/keras-io#1844]
### Issue Type

Support

### Source

source

### Keras Version

3.2.1

### Custom Code

Yes

### OS Platform and Distribution

Linux Ubuntu 22.04.4

### Python version

3.11.5

### GPU model and memory

16 gm

### Current Behavior?

please solve this error

### Standalone code to reproduce the issue or tutorial link

```shell
CKPT_path = "Model_ckpt.h5"
checkpointing_cb = tf.keras.callbacks.ModelCheckpoint(CKPT_path, save_best_only=True)

# Orginal train

EPOCHS = 30
VALIDATION_SET = (X_valid, y_valid)

history = model_clf.fit(X_train, y_train, epochs=EPOCHS,
                    validation_data=VALIDATION_SET, batch_size=32, callbacks=[tb_cb, early_stopping_cb,checkpointing_cb] )
```

### Relevant log output

```shell
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[37], line 2
      1 CKPT_path = "Model_ckpt.h5"
----> 2 checkpointing_cb = tf.keras.callbacks.ModelCheckpoint(CKPT_path, save_best_only=True)

File ~/anaconda3/lib/python3.11/site-packages/keras/src/callbacks/model_checkpoint.py:191, in ModelCheckpoint.__init__(self, filepath, monitor, verbose, save_best_only, save_weights_only, mode, save_freq, initial_value_threshold)
    189 else:
    190     if not self.filepath.endswith(".keras"):
--> 191         raise ValueError(
    192             "The filepath provided must end in `.keras` "
    193             "(Keras model format). Received: "
    194             f"filepath={self.filepath}"
    195         )

ValueError: The filepath provided must end in `.keras` (Keras model format). Received: filepath=Model_ckpt.h5
```

**Comment by AssiaBou** [comment]
I have the same problem in Kaggle notebook while executing the following code:
`history=model1.fit(train_img_datagen,
          steps_per_epoch=steps_per_epoch,
          epochs=100,
          verbose=1,
          callbacks = [
    keras.callbacks.ModelCheckpoint('UNet_100.h5', save_weights_only=False, save_best_only=True, monitor='val_loss', mode='min'),
    keras.callbacks.ReduceLROnPlateau(),
],
          validation_data=val_img_datagen,
          validation_steps=val_steps_per_epoch,
          )`

**Comment by AssiaBou** [comment]
@kishan042p I have just solved the problem by installing an older versio of keras:

!pip install keras==2.15.0
import keras
print(keras.__version__)

But you have to restart your kernel before using it,

Good luck

**Comment by kishan042p** [comment]
But i Want to save model in .h5 file not in .keras so please provide solution regarding it.

**Comment by kishan042p** [comment]
> @kishan042p I have just solved the problem by installing an older versio of keras:
> 
> !pip install keras==2.15.0 import keras print(keras.**version**)
> 
> But you have to restart your kernel before using it,
> 
> Good luck

But i Want to save model in .h5 file not in .keras so please provide solution regarding it.

**Comment by AssiaBou** [comment]
Yes I use my old code, where I save my model in .h5 file not .keras

**Comment by sachinprasadhs** [comment]
In Keras 3, for checkpoint filepath, you need to provide in `.keras` format only, if you're saving only weights file name should end with `.weights.h5`.

You can save and load the model in .h5 using below method 
https://keras.io/guides/migrating_to_keras_3/#saving-a-model-in-the-tf-savedmodel-format

**Comment by russell919** [comment]
In Keras 3, if you want to save your model in .h5 file, set "save_weights_only=True", and change your flie name to "xxx.weights.h5".

for your code:
`checkpointing_cb = tf.keras.callbacks.ModelCheckpoint(CKPT_path, save_best_only=True, save_weights_only=True)`

**Comment by helderdaniel** [comment]
https://keras.io/guides/migrating_to_keras_3/#saving-a-model-in-the-tf-savedmodel-format

"How to fix it: use model.export(filepath) instead of model.save(filepath)"

**Comment by diponkor-bala** [comment]
In Keras 3, if you want to save your model in .h5 file in any case, set "save_weights_only=True", and change your flie name to "xxx.weights.h5".

for your code:
CKPT_path = "Model_ckpt.weights.h5"
checkpointing_cb = tf.keras.callbacks.ModelCheckpoint(CKPT_path, save_best_only=True, save_weights_only=True)

**Comment by MariaLuize** [comment]
I wanted to share a clean update on how I successfully worked around this issue using a dynamic conversion bridge.

Instead of downgrading to Keras 2 to escape these format errors, you can manage the weight transitions programmatically across environments. Keras 3 dropped direct support for reading raw `.ckpt` weights but natively allows you to load weights from an older Keras 2 `.keras` file structure.

If you have legacy models or mixed pipelines, you can bypass the `ValueError` using this minimal fallback logic:

- When running in a Keras 2 environment:

> 1. Check if a standard `.keras` file exists. If it does, load it.
> 
> 2. If only the legacy `.ckpt` exists, instantiate the model, load the `.ckpt` weights, and explicitly save/export the model as a Keras 2 `.keras` file to establish an up-conversion baseline.

- When running in a Keras 3 environment:

> 1. If a native Keras 3 `.keras` file already exists, load it directly using `keras.models.load_model()`.
> 
> 2. If only the Keras 2 `.keras` file exists, instantiate your Keras 3 model architecture, load the Keras 2 weights into it (which Keras 3 natively supports via `load_weights`), and then save it out to disk as a native Keras 3 `.keras` file.
> 
> 3. If only a raw `.ckpt` file exists, fail gracefully or throw a clear error, as Keras 3 cannot interpret raw TensorFlow checkpoints without that intermediate Keras 2 extraction step.
