### ISSUE TITLE
Hardware requirement for examples/rl/deep_q_network_breakout.py?

### ISSUE THREAD

**Issue by haison8x** [keras-team/keras-io#1850]
May I ask the hardware requirements for examples/rl/deep_q_network_breakout.py?
I tried running this example in a server with 2GB RAM but it is corrupted after 2 hours, the virtual memory is 48 GB

**Comment by sachinprasadhs** [comment]
Hi, 

Could you try to reduce the numbers of these parameters and check if you're able to get improvement.

```
batch_size = 32 
max_steps_per_episode = 10000
max_episodes = 10
```

**Comment by haison8x** [comment]
Thanks
In case I want to run the full training session, which hardware specification should I use?

**Comment by sachinprasadhs** [comment]
> Thanks In case I want to run the full training session, which hardware specification should I use?

There is no benchmarking test or any other tests to guage the hardware requirement.

Usually, all the Keras tutorials are designed to work on the colab free runtime setup which is 12 GB ram.

You can try with 8-12 GB RAM setup and test it out.
