### ISSUE TITLE
Will it  be a good Idea to add a tutorial to train a Image Classification suing ViT using CLS token.

### ISSUE THREAD

**Issue by sineeli** [keras-team/keras-io#1862]
**Short Description**

Add possible tutorial on training basic architecture for Vision Transformer Using `CLS` token.

Also will it be a good idea to add ViT as a possible backbone, I can see keras already has ViT-DEIT and I am interested to contribute on writing the backbone.

Thanks

**Comment by sampathweb** [comment]
@sineeli - We already have a ViT DET Backbone in KerasCV. https://github.com/keras-team/keras-cv/blob/master/keras_cv/src/models/backbones/vit_det/vit_det_backbone.py#L35

Does this address what you are looking for?

**Comment by sineeli** [comment]
@sampathweb,

Yes the ViT DET exists but wanted to know if we can still include the other variation as well (ViT). If the same backbone solves the purpose then we can ignore ViT.

Thanks for letting me know.
