### ISSUE TITLE
Incorrect Links for Keras CV

### ISSUE THREAD

**Issue by trflorian** [keras-team/keras-io#1892]
### Issue Type

Documentation Bug

### Source

source

### Keras Version

Keras 3

### Custom Code

No

### Current Behavior?

All of the KerasCV links I tested on the keras.io website to the source code on the website are broken

On any keras-cv site of the keras.io website (e.g. https://keras.io/api/keras_cv/layers/augmentation/auto_contrast/)
When you click on the [source] on the top right, it will redirect you to the specific file in the keras_cv repo on github

https://github.com/keras-team/keras-cv/tree/v0.9.0/keras_cv/layers/preprocessing/auto_contrast.py#L24

However, this is an old link and results in a 404, the keraas_cv code has moved to a src/ directory. The  correct link should be

https://github.com/keras-team/keras-cv/blob/v0.9.0/keras_cv/src/layers/preprocessing/auto_contrast.py#L24

### Standalone code to reproduce the issue or tutorial link

```shell
https://keras.io/api/keras_cv/layers/augmentation/auto_contrast/
```

**Comment by sachinprasadhs** [comment]
Thanks for reporting the issue, it has been fixed in the commit here https://github.com/keras-team/keras-io/commit/22063cc30310f6bb409a7ca6ed410d08007a9f92
