### ISSUE TITLE
OCR end-to-end issue on dataset

### ISSUE THREAD

**Issue by anish9** [keras-team/keras-io#19]
what dataset should we use for OCR with CTC loss model, should it be generated on flow while training or any well established dataset.??

**Comment by fchollet** [comment]
We used to have an OCR example in the old multi-backend Keras. It was generated programmatically. You could reuse a similar dataset. https://github.com/keras-team/keras/blob/master/examples/image_ocr.py

Programmatic generation adds new dependencies though, so I would recommend generating a dataset programmatically *offline* then uploading it somewhere, and have your example code download it.
