### ISSUE TITLE
Dimension mismatch issues building a sequence-to-sequence model with attention

### ISSUE THREAD

**Issue by nahidalam** [keras-team/keras-io#193]
I am trying to create an example of sequence-to-sequence model with attention based on this [example](https://github.com/keras-team/keras-io/blob/master/examples/nlp/lstm_seq2seq.py). I am having some dimension mismatch issues although not sure exactly at which point it is happening or how to solve it.

Here is my model - 

```
latent_dim = 256
embedding_dim=100
batch_size  = 64

# Encoder
encoder_inputs = tf.keras.Input(shape=(None, num_encoder_tokens))
encoder_lstm = tf.keras.layers.LSTM(latent_dim, return_state=True)
encoder_output, state_h, state_c = encoder_lstm(encoder_inputs)

#decoder
decoder_inputs = tf.keras.Input(shape=(None, num_decoder_tokens))

decoder_lstm = tf.keras.layers.LSTM(latent_dim, return_sequences=True, return_state=True)
decoder_output,_, _ = decoder_lstm(decoder_inputs,initial_state=[state_h, state_c])

# Attention layer
attn_out = tf.keras.layers.Attention()([encoder_output, decoder_output])


# Concat attention input and decoder LSTM output
decoder_concat_input = tf.keras.layers.Concatenate(axis=1, name='concat_layer')([decoder_output, attn_out])

#dense layer
decoder_dense =  tf.keras.layers.Dense(num_decoder_tokens, activation='softmax')
decoder_outputs = decoder_dense(decoder_concat_input)

# Define the model 
attn_model = tf.keras.Model([encoder_inputs, decoder_inputs], decoder_outputs)

attn_model.summary()
```
The `plot_model` output here https://imgur.com/a/7CFPMnt

```
attn_model.compile(
    optimizer="rmsprop", loss="categorical_crossentropy", metrics=["accuracy"], run_eagerly=True
)
history = attn_model.fit(
    [encoder_input_data, decoder_input_data],
    decoder_target_data,
    batch_size=batch_size,
    epochs=5,
    validation_split=0.2,
)
```

I have below shape

`encoder_input_data.shape` is `(10000, 16, 71)`

`decoder_input_data.shape` is `(10000, 59, 92)`

`decoder_target_data.shape` is `(10000, 59, 92)`

When I train this, I get error 
`InvalidArgumentError: Incompatible shapes: [64,59,92] vs. [64,123,92] [Op:Mul] name: loss/dense_loss/mul/`

Please suggest.

**Comment by pcoet** [comment]
Hi @nahidalam, apologies for the belated response. This is not really a documentation issue. I'd suggestion posting to one of the forums below, if this is still relevant. Thanks!

* [TensorFlow forum](https://discuss.tensorflow.org/).
* [Keras mailing list](https://groups.google.com/forum/#!forum/keras-users).
