### ISSUE TITLE
warning while intalling requirements - depreciation 

### ISSUE THREAD

**Issue by EngrStudent** [keras-team/keras-io#1953]
### Issue Type

Others

### Source

source

### Keras Version

3.6.8

### Custom Code

No

### OS Platform and Distribution

Linux Ubuntu 20.04 focal

### Python version

3.18.9

### GPU model and memory

NVIDIA RTX A6080 rev a1

### Current Behavior?

I was installing in ubuntu from requirements and part of that was the following error:

![image](https://github.com/user-attachments/assets/526d94c3-1d52-46ce-94f5-558bde880701)
DERECATION: promise is being installed using the legacy setup.py install' method, because it does not have a 'pyproject.toml' and the wheel package is not installed.  Pip 23.1 will enforce this behavior change.  A possible replacement is to enable the --use-pep517 option.  Discussion can be found at ... 

### Standalone code to reproduce the issue or tutorial link

```shell
ubuntu --> venv --> activate --> git clone repo 

pip install -r requirements.txt
```

### Relevant log output

```shell
na.  pip doesn't naturally log, and by the time I wrote this, the installation process had completed.
```

**Comment by sachinprasadhs** [comment]
Could you please clarify on what package you are trying to install in Keras and which requirements.txt you are referring to?

`Keras` does not have 3.6.8 package yet, latest available as of now is 3.6.0
