### ISSUE TITLE
[Retinanet] Some trivial questions, about tf ops and selecting the dataset

### ISSUE THREAD

**Issue by srihari-humbarwadi** [keras-team/keras-io#2]
I am planning to make a notebook for retinanet, can you please let me know what dataset should I train on. Should I use a well known dataset or can it be a toy dataset thats easier to train on, like within 30 mins?
My another doubt is should I use the ops that are provided by keras only(tf.keras.backend) or using tf v2 ops is fine as well ?

**Comment by fchollet** [comment]
> My another doubt is should I use the ops that are provided by keras only(tf.keras.backend) or using tf v2 ops is fine as well ?

Any TF 2.0 functionality is fine. You can look at the existing code example to get an idea of what's expected.

For image segmentation, I would suggest MS COCO.
