### ISSUE TITLE
Issue with transformer for sentence classification notebook

### ISSUE THREAD

**Issue by Saichethan** [keras-team/keras-io#216]
When using [https://github.com/keras-team/keras-io/blob/master/examples/nlp/text_classification_with_transformer.py](https://github.com/keras-team/keras-io/blob/master/examples/nlp/text_classification_with_transformer.py). I am getting the following error, How to solve it?

    **TypeError: tf__call() missing 1 required positional argument: 'training'**

![trans](https://user-images.githubusercontent.com/34788026/90398497-2a356200-e0b7-11ea-9684-6b61b645e619.png)

**Comment by fchollet** [comment]
You can run the model successfully simply by opening the Colab link and running through the cells. I recommend upgrading to the latest TF version (2.3 at this time, which is what Colab uses).

**Comment by csolamx** [comment]
I am having this issue back again.  I am running in Colab, tensorflow version 2.17.  Did it reapper by any chance?
