### ISSUE TITLE
"GitHub Source" Links Broken

### ISSUE THREAD

**Issue by evilpegasus** [keras-team/keras-io#222]
https://keras.io/getting_started/intro_to_keras_for_engineers/

The GitHub Source button leads to a 404 page. The View in Colab link is also broken.

**Comment by kurianbenoy** [comment]
This issue is being faced in multiple guides like:

- Functional API
- Multi- GPU and distributed training
(and 5 more)

Basic issue is missing a `/` after guides in in all the links. It seems like an issue with autogen creation process

**Comment by kenorb** [comment]
- "GitHub source" gives 404 at <https://keras.io/guides/functional_api/>
- "Model subclassing" gives 404 at <https://keras.io/api/models/>

**Comment by fchollet** [comment]
This is fixed.

**Comment by kenorb** [comment]
> This is fixed.

"Model subclassing" link on <https://keras.io/api/models/> points to <https://keras.io/guides/model_subclassing> which still gives 404.
