### ISSUE TITLE
Broken Links in Optimizers Documentation

### ISSUE THREAD

**Issue by asukakenji** [keras-team/keras-io#23]
There are typos in the following links, the subdirectory should spell `optimizers` instead of `optimizer`:

https://github.com/keras-team/keras-io/blob/01f488dc4842eff792539e6185d1405e709bdd0b/templates/api/optimizers/index.md#L65

https://github.com/keras-team/keras-io/blob/01f488dc4842eff792539e6185d1405e709bdd0b/templates/api/optimizers/index.md#L76

**Comment by fchollet** [comment]
Fixed
