### ISSUE TITLE
Image classification model training produces error when hosted  

### ISSUE THREAD

**Issue by quantum-fusion** [keras-team/keras-io#234]
Hello,

I executed this Colab for Image classification in Keras (https://keras.io/examples/vision/image_classification_from_scratch/).  I am interested in using a custom model , and then hosting with Keras model hosting.

See the results when the model produced by this Colab was executed.

It is disappointing, but the custom model that was produced and hosted produces a model error.

ValueError: `decode_predictions` expects a batch of predictions (i.e. a 2D array of shape (samples, 1000)). Found array with shape: (1, 1)
I0825 06:39:13.114106 123145366908928 _internal.py:113] 127.0.0.1 - - [25/Aug/2020 06:39:13] "POST /predict HTTP/1.1" 500 -

---
curl -X POST -F image=@9999.jpg "http://127.0.0.1:5000/predict"
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>
(base) MacBook-Pro:~/simple-keras-rest-api/kagglecatsanddogs_3367a/PetImages/Cat quantum-fusion$ cd

See results from server that is running with Keras model.

# USAGE
# Start the server:
#       python run_keras_server.py
# Submit a request via cURL:
#       curl -X POST -F image=@dog.jpg 'http://localhost:5000/predict'
# Submita a request via Python:
#       python simple_request.py

# import the necessary packages
from keras.applications import ResNet50
from keras.preprocessing.image import img_to_array
from keras.applications import imagenet_utils
from keras.models import load_model# this is new hrh
from PIL import Image
# import autokeras as ak
import tensorflow as tf
import numpy as np
import flask
import io

# initialize our Flask application and the Keras model
app = flask.Flask(__name__)
model = None

def load_model():
    # load the pre-trained Keras model (here we are using a model
    # pre-trained on ImageNet and provided by Keras, but you can
    # substitute in your own networks just as easily)
    global model

    #model = ResNet50(weights="imagenet")# this was commented out hrh
    model = tf.keras.models.load_model('save_at_40.h5')
    print(type(model.summary()))  # this is new hrh

def prepare_image(image, target):
    # if the image mode is not RGB, convert it
    if image.mode != "RGB":
        image = image.convert("RGB")

    # resize the input image and preprocess it
    image = image.resize(target)
    image = img_to_array(image)
    image = np.expand_dims(image, axis=0)
    image = imagenet_utils.preprocess_input(image)

    # return the processed image
    return image

@app.route("/predict", methods=["POST"])
def predict():
    # initialize the data dictionary that will be returned from the
    # view
    data = {"success": False}

    # ensure an image was properly uploaded to our endpoint
    if flask.request.method == "POST":
        if flask.request.files.get("image"):
            # read the image in PIL format
            image = flask.request.files["image"].read()
            image = Image.open(io.BytesIO(image))

            # preprocess the image and prepare it for classification
            image = prepare_image(image, target=(224, 224))

            # classify the input image and then initialize the list
            # of predictions to return to the client
            preds = model.predict(image)
            results = imagenet_utils.decode_predictions(preds)
            data["predictions"] = []

            # loop over the results and add them to the list of
            # returned predictions
            for (imagenetID, label, prob) in results[0]:
                r = {"label": label, "probability": float(prob)}
                data["predictions"].append(r)

            # indicate that the request was a success
            data["success"] = True

    # return the data dictionary as a JSON response
    return flask.jsonify(data)

# if this is the main thread of execution first load the model and
# then start the server
if __name__ == "__main__":
    print(("* Loading Keras model and Flask starting server..."
           "please wait until server has fully started"))
    load_model()
    app.run()

---
python run_keras_server.py 
* Loading Keras model and Flask starting server...please wait until server has fully started
2020-08-25 06:36:57.297345: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN)to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2020-08-25 06:36:57.328434: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7f8fb1c90110 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-08-25 06:36:57.328458: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
Model: "functional_1"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
==================================================================================================
input_1 (InputLayer)            [(None, 180, 180, 3) 0                                            
__________________________________________________________________________________________________
sequential (Sequential)         (None, 180, 180, 3)  0           input_1[0][0]                    
__________________________________________________________________________________________________
rescaling (Rescaling)           (None, 180, 180, 3)  0           sequential[0][0]                 
__________________________________________________________________________________________________
conv2d (Conv2D)                 (None, 90, 90, 32)   896         rescaling[0][0]                  
__________________________________________________________________________________________________
batch_normalization (BatchNorma (None, 90, 90, 32)   128         conv2d[0][0]                     
__________________________________________________________________________________________________
activation (Activation)         (None, 90, 90, 32)   0           batch_normalization[0][0]        
__________________________________________________________________________________________________
conv2d_1 (Conv2D)               (None, 90, 90, 64)   18496       activation[0][0]                 
__________________________________________________________________________________________________
batch_normalization_1 (BatchNor (None, 90, 90, 64)   256         conv2d_1[0][0]                   
__________________________________________________________________________________________________
activation_1 (Activation)       (None, 90, 90, 64)   0           batch_normalization_1[0][0]      
__________________________________________________________________________________________________
activation_2 (Activation)       (None, 90, 90, 64)   0           activation_1[0][0]               
__________________________________________________________________________________________________
separable_conv2d (SeparableConv (None, 90, 90, 128)  8896        activation_2[0][0]               
__________________________________________________________________________________________________
batch_normalization_2 (BatchNor (None, 90, 90, 128)  512         separable_conv2d[0][0]           
__________________________________________________________________________________________________
activation_3 (Activation)       (None, 90, 90, 128)  0           batch_normalization_2[0][0]      
__________________________________________________________________________________________________
separable_conv2d_1 (SeparableCo (None, 90, 90, 128)  17664       activation_3[0][0]               
__________________________________________________________________________________________________
batch_normalization_3 (BatchNor (None, 90, 90, 128)  512         separable_conv2d_1[0][0]         
__________________________________________________________________________________________________
max_pooling2d (MaxPooling2D)    (None, 45, 45, 128)  0           batch_normalization_3[0][0]      
__________________________________________________________________________________________________
conv2d_2 (Conv2D)               (None, 45, 45, 128)  8320        activation_1[0][0]               
__________________________________________________________________________________________________
add (Add)                       (None, 45, 45, 128)  0           max_pooling2d[0][0]              
                                                                 conv2d_2[0][0]                   
__________________________________________________________________________________________________
activation_4 (Activation)       (None, 45, 45, 128)  0           add[0][0]                        
__________________________________________________________________________________________________
separable_conv2d_2 (SeparableCo (None, 45, 45, 256)  34176       activation_4[0][0]               
__________________________________________________________________________________________________
batch_normalization_4 (BatchNor (None, 45, 45, 256)  1024        separable_conv2d_2[0][0]         
__________________________________________________________________________________________________
activation_5 (Activation)       (None, 45, 45, 256)  0           batch_normalization_4[0][0]      
__________________________________________________________________________________________________
separable_conv2d_3 (SeparableCo (None, 45, 45, 256)  68096       activation_5[0][0]               
__________________________________________________________________________________________________
batch_normalization_5 (BatchNor (None, 45, 45, 256)  1024        separable_conv2d_3[0][0]         
__________________________________________________________________________________________________
max_pooling2d_1 (MaxPooling2D)  (None, 23, 23, 256)  0           batch_normalization_5[0][0]      
__________________________________________________________________________________________________
conv2d_3 (Conv2D)               (None, 23, 23, 256)  33024       add[0][0]                        
__________________________________________________________________________________________________
add_1 (Add)                     (None, 23, 23, 256)  0           max_pooling2d_1[0][0]            
                                                                 conv2d_3[0][0]                   
__________________________________________________________________________________________________
activation_6 (Activation)       (None, 23, 23, 256)  0           add_1[0][0]                      
__________________________________________________________________________________________________
separable_conv2d_4 (SeparableCo (None, 23, 23, 512)  133888      activation_6[0][0]               
__________________________________________________________________________________________________
batch_normalization_6 (BatchNor (None, 23, 23, 512)  2048        separable_conv2d_4[0][0]         
__________________________________________________________________________________________________
activation_7 (Activation)       (None, 23, 23, 512)  0           batch_normalization_6[0][0]      
__________________________________________________________________________________________________
separable_conv2d_5 (SeparableCo (None, 23, 23, 512)  267264      activation_7[0][0]               
__________________________________________________________________________________________________
batch_normalization_7 (BatchNor (None, 23, 23, 512)  2048        separable_conv2d_5[0][0]         
__________________________________________________________________________________________________
max_pooling2d_2 (MaxPooling2D)  (None, 12, 12, 512)  0           batch_normalization_7[0][0]      
__________________________________________________________________________________________________
conv2d_4 (Conv2D)               (None, 12, 12, 512)  131584      add_1[0][0]                      
__________________________________________________________________________________________________
add_2 (Add)                     (None, 12, 12, 512)  0           max_pooling2d_2[0][0]            
                                                                 conv2d_4[0][0]                   
__________________________________________________________________________________________________
activation_8 (Activation)       (None, 12, 12, 512)  0           add_2[0][0]                      
__________________________________________________________________________________________________
separable_conv2d_6 (SeparableCo (None, 12, 12, 728)  378072      activation_8[0][0]               
__________________________________________________________________________________________________
batch_normalization_8 (BatchNor (None, 12, 12, 728)  2912        separable_conv2d_6[0][0]         
__________________________________________________________________________________________________
activation_9 (Activation)       (None, 12, 12, 728)  0           batch_normalization_8[0][0]      
__________________________________________________________________________________________________
separable_conv2d_7 (SeparableCo (None, 12, 12, 728)  537264      activation_9[0][0]               
__________________________________________________________________________________________________
batch_normalization_9 (BatchNor (None, 12, 12, 728)  2912        separable_conv2d_7[0][0]         
__________________________________________________________________________________________________
max_pooling2d_3 (MaxPooling2D)  (None, 6, 6, 728)    0           batch_normalization_9[0][0]      
__________________________________________________________________________________________________
conv2d_5 (Conv2D)               (None, 6, 6, 728)    373464      add_2[0][0]                      
__________________________________________________________________________________________________
add_3 (Add)                     (None, 6, 6, 728)    0           max_pooling2d_3[0][0]            
                                                                 conv2d_5[0][0]                   
__________________________________________________________________________________________________
separable_conv2d_8 (SeparableCo (None, 6, 6, 1024)   753048      add_3[0][0]                      
__________________________________________________________________________________________________
batch_normalization_10 (BatchNo (None, 6, 6, 1024)   4096        separable_conv2d_8[0][0]         
__________________________________________________________________________________________________
activation_10 (Activation)      (None, 6, 6, 1024)   0           batch_normalization_10[0][0]     
__________________________________________________________________________________________________
global_average_pooling2d (Globa (None, 1024)         0           activation_10[0][0]              
__________________________________________________________________________________________________
dropout (Dropout)               (None, 1024)         0           global_average_pooling2d[0][0]   
__________________________________________________________________________________________________
dense (Dense)                   (None, 1)            1025        dropout[0][0]                    
==================================================================================================
Total params: 2,782,649
Trainable params: 2,773,913
Non-trainable params: 8,736
__________________________________________________________________________________________________
<class 'NoneType'>
 * Serving Flask app "run_keras_server" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
WARNING: Logging before flag parsing goes to stderr.
I0825 06:36:57.925263 4562980288 _internal.py:113]  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
W0825 06:38:34.713990 123145366908928 ag_logging.py:146] AutoGraph could not transform <function Model.make_predict_function.<locals>.predict_function at 0x7f901a045820> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: module 'gast' has no attribute 'Constant'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
W0825 06:38:34.715279 123145366908928 functional.py:584] Model was constructed with shape (None, 180, 180, 3) for input Tensor("input_1:0", shape=(None, 180, 180, 3), dtype=float32), but it was called on an input with incompatible shape (None, 224, 224, 3).
W0825 06:38:34.715477 123145366908928 functional.py:584] Model was constructed with shape (None, 180, 180, 3) for input Tensor("random_flip_input:0", shape=(None, 180, 180, 3), dtype=float32), but it was called on an input with incompatible shape (None, 224, 224, 3).
E0825 06:38:34.982172 123145366908928 app.py:1891] Exception on /predict [POST]
Traceback (most recent call last):
  File "/Users/hottelet/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/hottelet/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/hottelet/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/hottelet/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/hottelet/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/hottelet/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "run_keras_server.py", line 71, in predict
    results = imagenet_utils.decode_predictions(preds)
  File "/Users/hottelet/venv/lib/python3.8/site-packages/tensorflow/python/keras/applications/imagenet_utils.py", line 148, in decode_predictions
    raise ValueError('`decode_predictions` expects '
ValueError: `decode_predictions` expects a batch of predictions (i.e. a 2D array of shape (samples, 1000)). Found array with shape: (1, 1)
I0825 06:38:34.987346 123145366908928 _internal.py:113] 127.0.0.1 - - [25/Aug/2020 06:38:34] "POST /predict HTTP/1.1" 500 -
E0825 06:38:39.890367 123145366908928 app.py:1891] Exception on /predict [POST]
Traceback (most recent call last):
  File "/Users/hottelet/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/hottelet/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/hottelet/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/hottelet/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/hottelet/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/hottelet/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "run_keras_server.py", line 71, in predict
    results = imagenet_utils.decode_predictions(preds)
  File "/Users/hottelet/venv/lib/python3.8/site-packages/tensorflow/python/keras/applications/imagenet_utils.py", line 148, in decode_predictions
    raise ValueError('`decode_predictions` expects '
ValueError: `decode_predictions` expects a batch of predictions (i.e. a 2D array of shape (samples, 1000)). Found array with shape: (1, 1)
I0825 06:38:39.890976 123145366908928 _internal.py:113] 127.0.0.1 - - [25/Aug/2020 06:38:39] "POST /predict HTTP/1.1" 500 -
E0825 06:39:13.113486 123145366908928 app.py:1891] Exception on /predict [POST]
Traceback (most recent call last):
  File "/Users/hottelet/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/hottelet/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/hottelet/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/hottelet/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/hottelet/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/hottelet/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "run_keras_server.py", line 71, in predict
    results = imagenet_utils.decode_predictions(preds)
  File "/Users/hottelet/venv/lib/python3.8/site-packages/tensorflow/python/keras/applications/imagenet_utils.py", line 148, in decode_predictions
    raise ValueError('`decode_predictions` expects '
ValueError: `decode_predictions` expects a batch of predictions (i.e. a 2D array of shape (samples, 1000)). Found array with shape: (1, 1)
I0825 06:39:13.114106 123145366908928 _internal.py:113] 127.0.0.1 - - [25/Aug/2020 06:39:13] "POST /predict HTTP/1.1" 500 -

**Comment by fchollet** [comment]
Sounds like you ran into a download error. Just download the data again.
