### ISSUE TITLE
Retinanet - box_variance

### ISSUE THREAD

**Issue by oattao** [keras-team/keras-io#248]
I don't understand the box_variance in classes LabelEncoder and DecoderPredictions. In the LabelEncoder, I saw (box_target = box_target / self._box_variance). In the DecoderPrediction, I saw (boxes = box_predictions * self._box_variance). Could you please explain why we need box_variance?

**Comment by srihari-humbarwadi** [comment]
I agree that the name `_box_variance` is confusing. AFAIU, it functions as a scaling factor that tries to make the bounding regression targets have unit variance. There is no mention of this in the RetinaNet paper, but many popular implementations of detection models like Faster RCNN, SSD etc that use a similar setup for encoding regression targets, tend to use it as well. I haven't seen a drastic change in the performance if we just skip this step.
