### ISSUE TITLE
Steps to run the autogen script are not uniform

### ISSUE THREAD

**Issue by pedro823** [keras-team/keras-io#25]
As stated in PR #21, I couldn't run the autogen command to generate all the types of documentation from the templates.

### Attempt ###
To try and run the autogen, i did the following steps:

1. Created a virtualenv and got a shell over there.
2. Got the list of dependencies that were declared in the header of `autogen.py` and installed them:
```
pip install pygments jinja2 markdown requests mdx_truly_sane_lists
```

3. Running it, I get an error of no module named `sphinx`. 
```
ModuleNotFoundError: No module named 'sphinx'
```

4. So I installed it with `pip install sphinx`, and ran it again. There's the same error with the `black` module, so I installed it as well.

5. At this point, `python3 autogen.py make` starts to do some output. However, at `api/models` we find another missing module, `tensorflow`:

```
...Processing api/models
Traceback (most recent call last):
  File "/Users/raz/web/keras-io/scripts/docstrings.py", line 113, in import_object
    last_object_got = importlib.import_module(".".join(seen_names))
  File "/Users/raz/web/keras-io/venv/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'tensorflow'
```

Installed it, next.

6. This is when I hit a wall: running it again, it stopped on `api/preprocessing`, which needs more than just module installation.

```
...Processing api/preprocessing
Traceback (most recent call last):
  File "/Users/raz/web/keras-io/scripts/docstrings.py", line 113, in import_object
    last_object_got = importlib.import_module(".".join(seen_names))
  File "/Users/raz/web/keras-io/venv/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'tensorflow.keras.preprocessing.image_dataset_from_directory'
```

Installing keras didn't help.

### Follow-up discussion ###

- The process of installation could probably use a `Pipfile` from [pipenv](https://pipenv-fork.readthedocs.io/en/latest/). Installation could be as easy as a `pipenv sync`. 
- The process of generating the files should be separated from the process of checking if the code of the files is correct. I didn't stop to read the code, but I assume that's it, since normally you wouldn't need tensorflow & keras to build a static page.
- With that made, we could even go a step further and make the CI verify that `autogen.py` was run before merging the PR by adding a `python autogen.py verify`. With that, the `master` branch will never have a mismatch between the templates and the generated documentation.

**Comment by gabrieldemarmiesse** [comment]
I'm working on that, see #14 

So far, the requirement.txt looks like this:
```
pygments
jinja2
markdown
requests
mdx_truly_sane_lists
sphinx
black
tf-nightly
```

That works out for the dependencies. I'm having another problem, but it's not related to external packages.

**Comment by pedro823** [comment]
@gabrieldemarmiesse What is your setup for running the autogen? It's strange for my machine to require more packages than yours.

should we create a container image that has all the python package requirements?

**Comment by gabrieldemarmiesse** [comment]
I think https://github.com/keras-team/keras-io/pull/27 fixes your problems. Can you take a look?

**Comment by pedro823** [comment]
It was merged and I can confirm that the docker version now works and renders fine. Awesome! I'm closing this.

**Comment by gabrieldemarmiesse** [comment]
Happy to hear it :)
