### ISSUE TITLE
A minor issue: Extra Activation Layer

### ISSUE THREAD

**Issue by mmalekzadeh** [keras-team/keras-io#254]
In this tutorial: 
https://github.com/keras-team/keras-io/blob/master/examples/vision/oxford_pets_image_segmentation.py#L119

This line of code is redundant and can be removed:
https://github.com/keras-team/keras-io/blob/678471522035c988f98c82ce86e4c892d40163a3/examples/vision/oxford_pets_image_segmentation.py#L119

Cause there is the following line right after the above line:
https://github.com/keras-team/keras-io/blob/678471522035c988f98c82ce86e4c892d40163a3/examples/vision/oxford_pets_image_segmentation.py#L125

So, there is an extra activation layer in the model.

**Comment by sachinprasadhs** [comment]
Thanks for reporting the issue.

You are right, it does not make any difference.
I have created PR to correct the issue.
