### ISSUE TITLE
Error in vae examples:ValueError:The model cannot be comiled because it has no loss to optimize

### ISSUE THREAD

**Issue by skgone** [keras-team/keras-io#278]
When i implement the vae.py, i got error below:
`ValueError:The model cannot be comiled because it has no loss to optimize`

I use tensorflow-gpu 2.0.0

**Comment by EngrStudent** [comment]
I also get this.

`ValueError: The model cannot be compiled because it has no loss to optimize.`

**Comment by Wangdai-0800** [comment]
Have you found the solution? I meet the same error too.

**Comment by EngrStudent** [comment]
I performed "conda clean -all" in the environment and it went away.

**Comment by Wangdai-0800** [comment]
> I performed "conda clean -all" in the environment and it went away.

Thanks for replying, but it seems not work with my code.

**Comment by sachinprasadhs** [comment]
Hi, 

I'm able to run the VAE tutorial without any issues.

Please find the relevant Gist here: https://gist.github.com/sachinprasadhs/545459a4c3f313177f7f87dc3077a305.

Please consider upgrading to latest Tensorflow package to resolve any environment related issues by following the steps here 
https://www.tensorflow.org/install/pip
