### ISSUE TITLE
Error in Code example: "Writing a training loop from scratch"

### ISSUE THREAD

**Issue by JannisFengler** [keras-team/keras-io#280]
![custom_loops](https://user-images.githubusercontent.com/20631393/95906373-53fac480-0d9a-11eb-9162-63340fcba3b3.png)

In the part "Low-level handling of metrics" of the "Writing a training loop from scratch" tutorial are a few errors.
The splitting of the Test and Training data is a little bit out of order and the training data is not imported.

https://keras.io/guides/writing_a_training_loop_from_scratch/

Maybe change:

```# Prepare the training dataset.
batch_size = 64
train_dataset = tf.data.Dataset.from_tensor_slices((x_train, y_train))
train_dataset = train_dataset.shuffle(buffer_size=1024).batch(batch_size)

# Prepare the validation dataset.
# Reserve 10,000 samples for validation.
x_val = x_train[-10000:]
y_val = y_train[-10000:]
x_train = x_train[:-10000]
y_train = y_train[:-10000]
val_dataset = tf.data.Dataset.from_tensor_slices((x_val, y_val))
val_dataset = val_dataset.batch(64)
```
to
```
# Prepare the dataset.
batch_size = 64
(x_train, y_train), (x_test, y_test) = keras.datasets.mnist.load_data()
x_train = np.reshape(x_train, (-1, 784))
x_test = np.reshape(x_test, (-1, 784))

# Reserve 10,000 samples for validation.
x_val = x_train[-10000:]
y_val = y_train[-10000:]
x_train = x_train[:-10000]
y_train = y_train[:-10000]

# Prepare the training dataset.
train_dataset = tf.data.Dataset.from_tensor_slices((x_train, y_train))
train_dataset = train_dataset.shuffle(buffer_size=1024).batch(batch_size)

# Prepare the validation dataset.
val_dataset = tf.data.Dataset.from_tensor_slices((x_val, y_val))
val_dataset = val_dataset.batch(batch_size)
```

**Comment by sachinprasadhs** [comment]
Hi,

Thanks for reporting the issue.

I see the ordering issue has been taken care with these commits https://github.com/keras-team/keras-io/commit/11bb5206e1545f0b8b3374a1d04d40cf4d298554, https://github.com/keras-team/keras-io/commit/45ff000fd248e74bd47aeeb2a3f09f0a79a30f1c and it is updated in the tutorial below.

https://keras.io/guides/writing_a_training_loop_from_scratch/

Let us know if you still have any questions or concerns. Thanks!

**Comment by JannisFengler** [comment]
LGTM :)
