### ISSUE TITLE
KeyError issue: in indices_char = dict((I, c) for c, i in enumerate(chars))

### ISSUE THREAD

**Issue by sidneyarcidiacono** [keras-team/keras-io#282]
Assigns the character as key and the index as value, which raises a key error in on_epoch_end function when training. For the following to work: 

                next_index = sample(preds, diversity)
                next_char = indices_char[next_index]
                sentence = sentence[1:] + next_char
                generated += next_char

indices_char[next_index] is looking for a numbered index as key value, and finds only a character string. If you switch the indices_char declaration to: indices_char = dict((c, i) for c, i in enumerate(chars)) the model is able to train and run as expected. 

No big issue or question here, just wanted to point this out so that it can be looked at. I welcome any feedback if there is a better place for me to raise such issues in the future. Thank you very much!

**Comment by sachinprasadhs** [comment]
Hi,

Thanks for reporting the issue.

In the below code for  `char_indices`

`char_indices = dict((c, i) for i, c in enumerate(chars))`

It basically means that the dictionary is ordered in a way that `key` as a `character` and `value` as `number`.

And in the below line for `indices_char`, 

`indices_char = dict((i, c) for i, c in enumerate(chars))`

The dictionary order has to be in `indices` as `key` and character as `value` and the same order has to be maintained for the model to work. 

Hope this clarifies your doubt. Thanks!
