### ISSUE TITLE
When training on full dataset, I get this warning on the second epoch

### ISSUE THREAD

**Issue by jcorrea2016** [keras-team/keras-io#285]
Not the best with Keras so apologies in advance.

WARNING:tensorflow:Your input ran out of data; interrupting training. Make sure that your dataset or generator can generate at least `steps_per_epoch * epochs` batches (in this case, 354846 batches). You may need to use the repeat() function when building your dataset.

could this be due to these data sets being incomplete? This is from the dataset's load
![image](https://user-images.githubusercontent.com/63206544/96938905-8cd12280-1499-11eb-8751-51249cea95ba.png)

If so what could be making the dataset not load fully?
Edit: forgot screenshot of the actual output of the warning that interrupted training

![image](https://user-images.githubusercontent.com/63206544/96939042-edf8f600-1499-11eb-86be-8f8ffc4f2ebc.png)

**Comment by sachinprasadhs** [comment]
As the error suggests _`Make sure that your dataset or generator can generate at least steps_per_epoch * epochs batches`_

To avoid the warning, you can follow the below steps.

`steps_per_epoch = len(X_train)//batch_size`

`validation_steps = len(X_test)//batch_size `
