### ISSUE TITLE
Speech Recognition Example

### ISSUE THREAD

**Issue by phananh1096** [keras-team/keras-io#287]
Hi, a group of friends and I would like to provide implementation documentation for the "Speech Recognition" Example mentioned in the Call for Code Contribution Example document. We are currently aiming to have a full working implementation by the end of December. Would this be okay?

**Comment by kubumiro** [comment]
Hi, I am looking for a suitable Keras Speech Recognition tutorial. Do you already have any accessible working implementation to look at?

**Comment by phananh1096** [comment]
Hi, we are currently still working on the implementation at the moment. 

> Hi, I am looking for a suitable Keras Speech Recognition tutorial. Do you already have any accessible working implementation to look at?

**Comment by sachinprasadhs** [comment]
Hi,

The tutorial for Speech Recognition is available now. 
You can use the below links to access.

https://keras.io/examples/audio/transformer_asr/

https://keras.io/examples/audio/ctc_asr/
