### ISSUE TITLE
grad-cam for cnn regression problem

### ISSUE THREAD

**Issue by zepmck** [keras-team/keras-io#295]
Hi all, I am trying to apply grad-cam to a regression problem using a 3D CNN (largely taking inspiration from AlexNet architecture) and wondering if anyone has ever tackled this kind of problem. Thanks!

**Comment by pcoet** [comment]
Hi @zepmck, thanks for the question. If it's still relevant, can you repost to one of these forums?

* [TensorFlow forum](https://discuss.tensorflow.org/)
* [Keras mailing list](https://groups.google.com/forum/#!forum/keras-users)

Thanks!
