### ISSUE TITLE
Adding examples for Text-to-Speech

### ISSUE THREAD

**Issue by markhalka** [keras-team/keras-io#296]
Hello,

I am working on the "Text-to-Speech" contribution (https://github.com/keras-team/keras-io/blob/master/call_for_contributions.md#Text-to-Speech) with a team of other students. Please let me know if there is anyone else working on this. 

Thank you!

**Comment by sachinprasadhs** [comment]
Hi,

Just checking if you have any update on the issue.

You can check the keras implementation of Text to speech here https://github.com/dathudeptrai/TensorflowTTS
