### ISSUE TITLE
img_path and labels in encoding_single_sample are not passed as argument or not initialized

### ISSUE THREAD

**Issue by gokul1099** [keras-team/keras-io#298]
While calling the encoding_single_sample functions using dataset object there facing a error that img_path and label is noet initialized. How can i initialize the img_path and label? even i pass those as parameters still showing the same error. 
![image](https://user-images.githubusercontent.com/42144106/98133446-9fa91580-1ee3-11eb-97f5-2ab8576a9bc6.png)

**Comment by sr0784359** [comment]
> While calling the encoding_single_sample functions using dataset object there facing a error that img_path and label is noet initialized. How can i initialize the img_path and label? even i pass those as parameters still showing the same error.
> ![image](https://user-images.githubusercontent.com/42144106/98133446-9fa91580-1ee3-11eb-97f5-2ab8576a9bc6.png)

**Comment by sr0784359** [comment]
#325 @sr0784359 #326 #197
