### ISSUE TITLE
Reset OU noise process

### ISSUE THREAD

**Issue by tristan-deep** [keras-team/keras-io#299]
Hi,

I see that the DDPG paper states the random process is initialized every episode. Does this mean the OU noise precess needs to be reset every episode as well? As of now, I do not see this anywhere.

https://github.com/keras-team/keras-io/blob/410191d8ca2c716c2578fe9d8462f1f0b8791537/examples/rl/ddpg_pendulum.py#L116

Thank you!

**Comment by sachinprasadhs** [comment]
@amifunny , Could you please look into the issue about the Tutorial which you have authored. Thanks!

**Comment by pcoet** [comment]
It looks like this is a support question. @tristan-deep can you repost to one of the forums below, if this is still relevant?

* [TensorFlow forum](https://discuss.tensorflow.org/)
* [Keras mailing list](https://groups.google.com/forum/#!forum/keras-users)

Thanks!
