### ISSUE TITLE
I love your examples but I hope more notes could be added 

### ISSUE THREAD

**Issue by heyanyidui** [keras-team/keras-io#302]
I love your examples very much !

Thanks !

But in fact I found that for some examples that are not so easy as to I can get the idea in 10 min, and I hope some more notes for some examples could be added.

Thank you very much !

**Comment by sachinprasadhs** [comment]
Hi @heyanyidui ,

Thanks for opening the issue. 

For us to understand better could you please point to the specific example which are referring to. 

In general, we add note or explanation to the tutorials where we feel it is necessary.

For domain related knowledge on Machine Learning, you can refer to our crash course here https://developers.google.com/machine-learning/crash-course. Thanks!
