### ISSUE TITLE
TypeError: float() argument must be a string or a number, not 'PiecewiseConstantDecay'

### ISSUE THREAD

**Issue by siriusmehta** [keras-team/keras-io#303]
@srihari-humbarwadi 

Tried running the retinanet notebook and found the below erroe:

100/100 [==============================] - ETA: 0s - loss: 2.6164
Epoch 00023: val_loss did not improve from 3.44182
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-19-1106288ed04f> in <module>
     17     epochs=epochs,
     18     callbacks=callbacks_list,
---> 19     verbose=1,
     20 )

~/anaconda3/envs/tf2.3/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py in _method_wrapper(self, *args, **kwargs)
    106   def _method_wrapper(self, *args, **kwargs):
    107     if not self._in_multi_worker_mode():  # pylint: disable=protected-access
--> 108       return method(self, *args, **kwargs)
    109 
    110     # Running inside `run_distribute_coordinator` already.

~/anaconda3/envs/tf2.3/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py in fit(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, validation_batch_size, validation_freq, max_queue_size, workers, use_multiprocessing)
   1135           epoch_logs.update(val_logs)
   1136 
-> 1137         callbacks.on_epoch_end(epoch, epoch_logs)
   1138         training_logs = epoch_logs
   1139         if self.stop_training:

~/anaconda3/envs/tf2.3/lib/python3.6/site-packages/tensorflow/python/keras/callbacks.py in on_epoch_end(self, epoch, logs)
    414         if numpy_logs is None:  # Only convert once.
    415           numpy_logs = tf_utils.to_numpy_or_python_type(logs)
--> 416         callback.on_epoch_end(epoch, numpy_logs)
    417 
    418   def on_train_batch_begin(self, batch, logs=None):

~/anaconda3/envs/tf2.3/lib/python3.6/site-packages/tensorflow/python/keras/callbacks.py in on_epoch_end(self, epoch, logs)
   2376         self.wait += 1
   2377         if self.wait >= self.patience:
-> 2378           old_lr = float(K.get_value(self.model.optimizer.lr))
   2379           if old_lr > self.min_lr:
   2380             new_lr = old_lr * self.factor

**TypeError: float() argument must be a string or a number, not 'PiecewiseConstantDecay'**

**Comment by srihari-humbarwadi** [comment]
Looking at your logs, are you trying to use `tf.keras.callbacks.ReduceLROnPlateau`? IIUC this is probably happening because the example is using a learning rate schedule - `PiecewiseConstantDecay`. 
@fchollet

**Comment by sachinprasadhs** [comment]
Hi @siriusmehta ,

I was able to run the tutorial using the latest Tensorflow without any errors.
Please find the below Gist for reference. Thanks!

https://gist.github.com/sachinprasadhs/1f6e4c79c128c1aa59e2bb0dbf19e0cf
