### ISSUE TITLE
batch_size wrong in example?

### ISSUE THREAD

**Issue by stefan-falk** [keras-team/keras-io#316]
The example, referenced [here](https://keras.io/guides/distributed_training/#singlehost-multidevice-synchronous-training) looks like it contains a slight error.

In particular, the dataset gets created with a batch-size of 32, instead of 512. If we have 8 GPUs and we want each of them receive 32 samples, shouldn't `batch_size` be set to `512` and not `32`?

https://github.com/keras-team/keras-io/blob/cd0fccfbcd0fbc1ec813a60c7fe5d523ba29117f/guides/distributed_training.py#L134

**Comment by sachinprasadhs** [comment]
Hi, 

As per the explanation provided here for sample batch size 512

> The current batch of data (called global batch) is split into 8 different sub-batches (called local batches). For instance, if the global batch has 512 samples, each of the 8 local batches will have 64 samples.

` batch_size = 32 ` in the example refers to global batch, if the number of replica is 8, then the local batch size will become 4.
Below is the example for the scenario which I have explained.

```
BATCH_SIZE_PER_REPLICA = 4
BATCH_SIZE = BATCH_SIZE_PER_REPLICA * strategy.num_replicas_in_sync
BATCH_SIZE = 32 ( 4* 8)
```
