### ISSUE TITLE
try to use GPU train the WGAN-GP

### ISSUE THREAD

**Issue by Hsin-HanChen** [keras-team/keras-io#319]
i'd like to use gpu to boost the training time of wgan-gp, but the program only pass my code of using gpu but it didn't work.
following is my version's
cuda:10.0
cuDNN:7.6.5
tensorflow:2.3.0
tensorflow-gpu:2.3.1

**Comment by 8bitmp3** [comment]
Hello, are you in Google Colab or running the code locally?

Just to make sure, I'd recommend checking that the GPU device(s) are used by TensorFlow by:

```python
import tensorflow as tf
tf.config.experimental.list_physical_devices('GPU')
```

Example output (Colab):

```
[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]
[ ]
```

(From https://www.tensorflow.org/guide/gpu)

**Comment by Hsin-HanChen** [comment]
Hi.I am running the code locally by pycharm.But the TF version need to be upon 2.2.0 or it will bump up error.I’ve tried if I lower my TF version to 2.1.0,the GPU will work, but face this error“ TypeError: compile() got an unexpected keyword argument 'optimizer' ” SincerelyHsin-Han Chen 寄件者: 8bitmp3傳送時間: 2020年12月2日 上午 02:43收件者: keras-team/keras-io副本: Hsin-HanChen; Author主旨: Re: [keras-team/keras-io] try to use GPU train the WGAN-GP (#319) Hello, are you in Google Colab or running the code locally?Just to make sure, I'd recommend checking that the GPU device(s) are used by TensorFlow by:import tensorflow as tftf.config.experimental.list_physical_devices('GPU')Example output (Colab):[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')][ ](From https://www.tensorflow.org/guide/gpu)—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by Hsin-HanChen** [comment]
Hi.
I am running the code locally by pycharm.
But the TF version need to be upon 2.2.0 or it will bump up error.
I’ve tried if I lower my TF version to 2.1.0,the GPU will work, but face this error
“ TypeError: compile() got an unexpected keyword argument 'optimizer' ”

**Comment by 8bitmp3** [comment]
OK 👍 Can you confirm you can train other models locally on your GPU with TF 2.3.1 (GPU)?

**Comment by Hsin-HanChen** [comment]
![未命名](https://user-images.githubusercontent.com/74956847/100784632-6fa15380-344a-11eb-8e3e-8f6dfa8946f2.png)

**Comment by Hsin-HanChen** [comment]
i can show you it isn't work....
i used to use the version lower than 2.3.0 to process. it can always train by my gpu, but this wgan-gp code, once i use the tf version lower than 2.2.0, it will error...

**Comment by 8bitmp3** [comment]
OK. I noticed that rebooting the PC helped some users and/or check if your cuDNN and CUDA versions are compatible: https://stackoverflow.com/questions/44829085/tensorflow-not-running-on-gpu

I've also run the code unchanged in Colab using the default TF (v2.3) and NVIDIA Tesla T4 and all seemed to be as expected. 

Another thing: there's a TF Profiler you could try installing at some point to help with debugging
https://www.tensorflow.org/guide/profiler#install_the_profiler_and_gpu_prerequisites

**Comment by 8bitmp3** [comment]
> following is my version's
> cuda:10.0
> cuDNN:7.6.5
> tensorflow:2.3.0
> tensorflow-gpu:2.3.1

Have you considered upgrading CUDA to 10.1?

The official TF requirements suggest you need 10.1: https://www.tensorflow.org/install/gpu#software_requirements

Also: https://stackoverflow.com/questions/63602327/gpu-problem-for-cuda-11-0-and-cudnn-8-0-2

**Comment by Hsin-HanChen** [comment]
OMG....i am really fool....
Thanks a lot giving me all the information and also helping me find out my problem.
Have a nice day!

**Comment by sachinprasadhs** [comment]
Hi @Hsin-HanChen ,

If your issue is resolved, could you please spare some time to close this issue.

To install the latest Tensorflow version, please refer the document here https://www.tensorflow.org/install/pip

For the Tested build configuration, please refer: https://www.tensorflow.org/install/source#tested_build_configurations
