### ISSUE TITLE
Reference Paper Missing in NasNet

### ISSUE THREAD

**Issue by asukakenji** [keras-team/keras-io#32]
While there is a "Reference" or "Reference Paper" section in every Keras Application, that for "NasNet" is missing.

See this for NasNet:
https://keras.io/api/applications/nasnet/

Compared with this for Xception:
https://keras.io/api/applications/xception/

**Comment by swghosh** [comment]
The documentation for Keras Applications is built directly from docstrings of tf.keras.applications.* I believe.

/cc: @fchollet any leads?

**Comment by asukakenji** [comment]
@swghosh Yes, this is exactly why I could not point out where the error is, and could not fix it. I search through the source code of both `keras`, `keras-applications`, and `keras-io`, but I still could not find where to fix it.

Apparently the reference is there. The only finding I got was that, in other models, the code says `# Reference paper` or `# Reference`, while in NASNet, it says `# References` in the docstring. I am not sure how and whether this makes a difference since I could not find anything related to the word "Reference", except this:

https://github.com/keras-team/keras-io/blob/165d3b3c708b987b367c41c4d8340553cdd8b028/scripts/docstrings.py#L32

But it seems this is not related to this issue.

Besides, would you please take a look at:

https://github.com/keras-team/keras-applications/pull/189

and

https://github.com/keras-team/keras-applications/pull/188

Both are small fixes (one documentation related, one unused import related) and I supposed they could be merged. Thanks!

**Comment by sachinprasadhs** [comment]
I can see the reference link mentioned for NasNet now at https://keras.io/api/applications/nasnet/
![image](https://github.com/keras-team/keras-io/assets/73069040/627ef81e-9d20-43cb-b187-61525b15e199)

Could you please verify and close the issue. Thanks!
