### ISSUE TITLE
Retina net code example fails downloading coco2017 dataset

### ISSUE THREAD

**Issue by lee-grand** [keras-team/keras-io#322]
Windows
Python 3.7
tensorflow                2.1.0           gpu_py37h7db9008_0
tensorflow-base           2.1.0           gpu_py37h55f5790_0
tensorflow-datasets       1.2.0                    py37_0
tensorflow-estimator      2.1.0              pyhd54b08b_0
tensorflow-gpu            2.1.0                h0d30ee6_0
tensorflow-metadata       0.14.0             pyhe6710b0_1

**At first it says:**
```
WARNING:absl:Found a different version 1.1.0 of dataset coco in data_dir data. Using currently defined version 1.0.0.
```
**Then it starts to download gigabytes of data and then gives error like:**
```
tensorflow_datasets.core.download.download_manager.NonMatchingChecksumError: Artifact http://images.cocodataset.org/zips/train2017.zip, downloaded to data\downloads\images.cocodataset.org_zips_train2017kf8fi7FBG8CRFD5M_1iGISWHMGlxy31RoQYQAApVnVY.zip.tmp.66f7816305924502ac131ec44a5243bf\train2017.zip, has wrong checksum.
```
It happens every time. There is enough disk space (162GB)

So it is not clear, as according to the code the download of full coco2017 dataset shouldn't happen at all, but looks like small dataset downloaded by:
```python
url = "https://github.com/srihari-humbarwadi/datasets/releases/download/v0.1.0/data.zip"
filename = os.path.join(os.getcwd(), "data.zip")
keras.utils.get_file(filename, url)
```
is not being liked by `tensorflow_datasets`, and then `tensorflow_datasets` tries downloading the full dataset and fails:
```python
(train_dataset, val_dataset), dataset_info = tfds.load(
    "coco/2017", split=["train", "validation"], with_info=True, data_dir="data"
)
```

It is also not clear why to use tensorflow tools for dataset at all (we have **keras** tutorial), it is not clear what this tools is doing with data, no way to control anything. Especially having in mind that tensorlfow itself is very cryptic and not user friendly thing for debugging and studying. Documentation for tensorflow is minimal (lacking good examples) and useless too (my recommendation is to avoid tensorflow as much as possible in keras tutorials)

**Comment by srihari-humbarwadi** [comment]
Please try to run the code with `tensorflow==2.4.0`

**Comment by sachinprasadhs** [comment]
Hi, I was able to download and run the notebook using latest Tensorflow version. 
Please find the below Gist for reference. Thanks!
https://gist.github.com/sachinprasadhs/1f6e4c79c128c1aa59e2bb0dbf19e0cf
