### ISSUE TITLE
error when running the notebook

### ISSUE THREAD

**Issue by rajae-Bens** [keras-team/keras-io#324]
Hi,

I tried to run the notebook _semantic_similarity_with_bert_ but I got this error

![Screen Shot 2020-12-05 at 8 10 18 PM](https://user-images.githubusercontent.com/58187895/101261225-eb92e880-3735-11eb-800f-6bd92d0b3331.png)

could someone help plz 

Thank u

**Comment by andybelov** [comment]
You are probably using a newer version of transformers than the author.
`bert_model` retruns dict so the values of sequence_output, pooled_output becomes keys of this dict (i.e. strings). Adding `return_dict=False` helps:
`
sequence_output, pooled_output = bert_model(
    input_ids, attention_mask=attention_masks, token_type_ids=token_type_ids, return_dict=False
)
`

See details here: https://stackoverflow.com/questions/64901831/huggingface-transformer-model-returns-string-instead-of-logits

**Comment by Lpourchot** [comment]
Hello Andy, sorry but I changed the line with yours and gets still : TypeError: Inputs to a layer should be tensors. Got: last_hidden_state

**Comment by OzgeOzkaya** [comment]
Hello,

I am having the same trouble. Did you find any solution?

**TypeError: Inputs to a layer should be tensors. Got: last_hidden_state**

Thank you

**Comment by OzgeOzkaya** [comment]
pip install transformers==3.0.0 worked for me.

**Comment by Lpourchot** [comment]
Yes ! correct it works, thank you ;-)

**Comment by OzgeOzkaya** [comment]
@Lpourchot Hi again. Could please look at [here](https://github.com/keras-team/keras-io/issues/346)? I'm getting another error in this project. I wonder if you deal with it or know how to solve.

**Comment by Lpourchot** [comment]
Hi, 
I don't know if it will help but I have just changed max_length = 256 (not 128). So it has increased the input shape.
The first step with Bert untrainable has worked for the 2 epochs. The fine tuning is still on going with trainable parameters it is very long even with GPU with 109,909,507 :-))

**Comment by Lpourchot** [comment]
it seems, that use_multiprocessing leads to some instabilities, sometimes the fit runs well, sometimes not...
So my suggestion 
1) add truncation = True in the tokenizer.batch_encode_plus (..) 
2) delete use_multiprocessing in the model.fit
3) define the number of rows with 
Total train samples : 10000
Total validation samples: 3000
Total test samples: 3000

This morning, it worked many times from SNLI Corpus and provided :
146s 469ms/step - loss: 0.7820 - acc: 0.6557 - val_loss: 0.6456 - val_acc: 0.7310

**Comment by sachinprasadhs** [comment]
Hi,

This example has been updated to Keras 3 and it is working fine without any issues.

Could you please find the example here and close this issue https://keras.io/examples/nlp/semantic_similarity_with_bert/. Thanks
