### ISSUE TITLE
[semantic_similarity_with_bert.py] Is it possible to solve the AttributeError problem?

### ISSUE THREAD

**Issue by kwon14** [keras-team/keras-io#328]
Hi.
I am studying and testing semantic_similarity_with_bert.py.
However, when creating a model, an AttributeError is raised.

Please wait for your answer to this question.

Thank you!!

Here is the error code.
---------------------------------------------------------------------
Some layers from the model checkpoint at bert-base-uncased were not used when initializing TFBertModel: ['nsp___cls', 'mlm___cls']
- This IS expected if you are initializing TFBertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFBertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
All the layers of TFBertModel were initialized from the model checkpoint at bert-base-uncased.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertModel for predictions without further training.
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-14-46653d782cd7> in <module>()
     26     bi_lstm = tf.keras.layers.Bidirectional(
     27         tf.keras.layers.LSTM(64, return_sequences=True)
---> 28     )(sequence_output)
     29     # Applying hybrid pooling approach to bi_lstm sequence output.
     30     avg_pool = tf.keras.layers.GlobalAveragePooling1D()(bi_lstm)

3 frames
/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/input_spec.py in assert_input_compatibility(input_spec, inputs, layer_name)
    164         spec.min_ndim is not None or
    165         spec.max_ndim is not None):
--> 166       if x.shape.ndims is None:
    167         raise ValueError('Input ' + str(input_index) + ' of layer ' +
    168                          layer_name + ' is incompatible with the layer: '

AttributeError: 'str' object has no attribute 'shape'

**Comment by MohamadMerchant** [comment]
Hi, 

Sorry for the late reply.

The error is due to some new changes in the huggingface transformers version. Please try running it with version=2.11.0 and it will not show the error.
!pip install transformers==2.11.0

Thanks.

**Comment by giangdip2410** [comment]
Hi @MohamadMerchant : do you have another solution for this issue ? I also face this issue with transformers==4.6.  But I can not back to transformers==2.11 due to some module I use only available at transformers==4.6. Hope to receive your answer , thank you.
