### ISSUE TITLE
[timeseries_anomaly_detection.py] Small error

### ISSUE THREAD

**Issue by eppane** [keras-team/keras-io#329]
Hello!

I believe there is a small error in timeseries_anomaly_detection.py. The create_sequences()-function defined at lines 108-112 leaves the last index out, returning an array of shape (3744, 288, 1), while the correct shape is (3745, 288, 1). The missing value can be verified: the last observation with value 18.6826..., from art_daily_small_noise.csv, gets left out.

Writing

`for i in range(len(values) - time_steps + 1):`

at line 110 should fix the issue.

Thanks!

**Comment by sachinprasadhs** [comment]
Hi, 

I see the issue has been fixed in the latest code here

https://github.com/keras-team/keras-io/blob/8f49b3ec63c7d959b9457ab7cc961ce4ca922d2f/examples/timeseries/timeseries_anomaly_detection.py#L110-L114

Could you please verify and close the issue. Thanks!
