### ISSUE TITLE
Unsecure random Path

### ISSUE THREAD

**Issue by Anselmoo** [keras-team/keras-io#331]
Hence, there is generated the random path via `random`, it might be better to use `from secrets import token_hex` for generating safer random path and files.

https://github.com/keras-team/keras-io/blob/7adc426c4cfa4871bcf380f8a48446f4459768c1/scripts/tutobooks.py#L223

**Comment by sachinprasadhs** [comment]
Hi, 

Thanks for opening the issue.

As reviewed in the PR, we don't have any plan to change the path format, feel free to close the PR. Thanks!
