### ISSUE TITLE
Adding example: Extend a Image classification model to classification and localization model

### ISSUE THREAD

**Issue by krn-sharma** [keras-team/keras-io#336]
Can I work on adding example for Image classification and localization using the idea from [OverFeat](https://arxiv.org/abs/1312.6229)?

**Comment by sachinprasadhs** [comment]
Hi @krn-sharma , 

Just checking if you have any update on the issue.
Check our Computer vision based examples here for all the latest examples https://keras.io/examples/vision/
 Thanks!
