### ISSUE TITLE
Retinanet - a small clarification needed

### ISSUE THREAD

**Issue by vijaygill** [keras-team/keras-io#337]
Apologies for a may be silly question....I am trying to understand the code for this nice little implementation of RetinaNet (thanks s @srihari-humbarwadi ).

In the class RetinaNet, the method call has following code:

In the loop (for feature in features), does that code mean that same box head and class head are getting connected with all outputs of the FPN (p3_output, p4_output, p5_output, p6_output, p7_output)?

```

def call(self, image, training=False):
        features = self.fpn(image, training=training)
        N = tf.shape(image)[0]
        cls_outputs = []
        box_outputs = []
        for feature in features:
            box_outputs.append(tf.reshape(self.box_head(feature), [N, -1, 4]))
            cls_outputs.append(
                tf.reshape(self.cls_head(feature), [N, -1, self.num_classes])
            )
        cls_outputs = tf.concat(cls_outputs, axis=1)
        box_outputs = tf.concat(box_outputs, axis=1)
        return tf.concat([box_outputs, cls_outputs], axis=-1)
```

**Comment by srihari-humbarwadi** [comment]
Yes, that's correct. The box and classification heads are shared between all the levels of the FPN

**Comment by vijaygill** [comment]
Thanks @srihari-humbarwadi!
