### ISSUE TITLE
Captcha OCR.  How to stop zeros from leaving the network.

### ISSUE THREAD

**Issue by gabriel-fsa** [keras-team/keras-io#339]
I am changing the [sample ](https://keras.io/examples/vision/captcha_ocr/) code on the keras website. With some adaptations made, it is starting to learn to recognize my captchas, but as they have different sizes (different from the images in the example) zeros are appearing at the network output, for example: 
`[{'result:': 'kurz00', 'value:': 'kurz'}, 
 {'result:': 'kxjd90', 'value:': 'kxjd9'},
 {'result:': 'kyxoa00', 'value:': 'kyxoa'},
 {'result:': 'm3b830', 'value:': 'm3b83'},
 {'result:': 'n3u2b0', 'value:': 'm3u2b'},
 {'result:': 'me490', 'value:': 'mee49'},
 {'result:': 'mfkt00', 'value:': 'mfkt'},
 {'result:': 'mhien00', 'value:': 'mhien'},
 {'result:': 'mj3660', 'value:': 'mj3i66'},
 {'result:': 'mjhbo0', 'value:': 'mjhbk'}]`

 I suppose that this problem is in the `num_to_char` and` char_to_num` part, but I have already made countless modifications and the error still persists.

`	
characters = ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z']

char_to_num = layers.experimental.preprocessing.StringLookup(vocabulary=list(characters), num_oov_indices=0, mask_token=None
	)

num_to_char = layers.experimental.preprocessing.StringLookup(vocabulary=char_to_num.get_vocabulary(), mask_token=None, invert=True, oov_token='')
    `

**Comment by Angelus1383** [comment]
Could you show the changes made to the code to try to manage different lengths. The zero looks like a placeholder used to fill the string.

**Comment by pcoet** [comment]
Hi @gabriel-fsa, thanks for getting in touch. This question would be a better fit for one of the forums below. Can you repost? 

* [TensorFlow forum](https://discuss.tensorflow.org/)
* [Keras mailing list](https://groups.google.com/forum/#!forum/keras-users)

Thanks!
