### ISSUE TITLE
InvalidArgumentError in semantic_similarity_with_bert example

### ISSUE THREAD

**Issue by OzgeOzkaya** [keras-team/keras-io#346]
Hello,

I'm having a trouble while running "semantic_similarity_with_bert". Anyone having the same error? Do you have any solution? Thank you.

**InvalidArgumentError:  Incompatible shapes: [32,53,768] vs. [1,128,768]**
	 [[node model/tf_bert_model/bert/embeddings/add (defined at /local/lib/python3.6/dist-packages/transformers/modeling_tf_bert.py:192) ]] [Op:__inference_train_function_31438]

Errors may have originated from an input operation.
Input Source operations connected to node model/tf_bert_model/bert/embeddings/add:
 model/tf_bert_model/bert/embeddings/GatherV2 (defined at /local/lib/python3.6/dist-packages/transformers/modeling_tf_bert.py:188)	
 model/tf_bert_model/bert/embeddings/position_embeddings/embedding_lookup/Identity (defined at /local/lib/python3.6/dist-packages/transformers/modeling_tf_bert.py:189)

Function call stack:
train_function

**Comment by Lpourchot** [comment]
it seems there is a problem when you feed the bert model. maybe you should check the shape of the tensors you give to the model. it should be = (None, 256) or (None, 128) if max_length = 128
print(input_ids.shape)
print(attention_masks.shape)
print(token_type_ids.shape)

**Comment by Lpourchot** [comment]
Better idea : add truncation = True in the tokenizer (def_getitem...)
encoded = self.tokenizer.batch_encode_plus(
            sentence_pairs.tolist(),
            add_special_tokens=True,
            max_length=max_length,
            truncation = True,
            return_attention_mask=True,
            return_token_type_ids=True,
            pad_to_max_length=True,
            return_tensors="tf",

**Comment by OzgeOzkaya** [comment]
I tried your suggestions. Now I am waiting. Thank a lot!

**Comment by OzgeOzkaya** [comment]
Hi again. I just wanted to say thank you again. Your suggestions worked for me. You made my day!

**Comment by Lpourchot** [comment]
Thank you for your feedback, I'm happy it works :-)
