### ISSUE TITLE
Entity embeddings example

### ISSUE THREAD

**Issue by sayakpaul** [keras-team/keras-io#362]
@fchollet do you think an example on [entity embeddings](https://arxiv.org/abs/1604.06737) for modeling structured data would be good? 

We use the standard `Embedding` layer of Keras to represent the categorical variables to a prefixed dimensional space. This also helps us to visualize how the categorical features interact with each other in a higher-dimensional space.

Here's a [Colab Notebook](https://colab.research.google.com/gist/sayakpaul/e728c9dc804c9b7b4a3d50e23ae79cd1/skin_cancer_mnist_model_i.ipynb) I wrote to demo the concept. 

Happy to work on it if I have your green signal.

**Comment by sachinprasadhs** [comment]
Hi Sayak,

Are you still working on this and waiting an update from Keras team?
