### ISSUE TITLE
Object Detection with RetinaNet : preprocess_data

### ISSUE THREAD

**Issue by sonpero** [keras-team/keras-io#373]
When running the code, the function preprocess_data raise an error : 
OperatorNotAllowedInGraphError: using a `tf.Tensor` as a Python `bool` is not allowed in Graph execution. Use Eager execution or decorate this function with @tf.function

caused by :if tf.random.uniform(())

i primary use tensor flow 2.4 version and then downgrade to 2.3 with the same error.

[R-CNN.zip](https://github.com/keras-team/keras-io/files/5967146/R-CNN.zip)

**Comment by srihari-humbarwadi** [comment]
I ran the notebook on colab and it works fine for me. Please let me know if you can run this script.
https://github.com/keras-team/keras-io/blob/master/examples/vision/retinanet.py

You could also try running it in colab using this 
https://colab.research.google.com/github/keras-team/keras-io/blob/master/examples/vision/ipynb/retinanet.ipynb

**Comment by sonpero** [comment]
this link working fine :
https://colab.research.google.com/github/keras-team/keras-io/blob/master/examples/vision/ipynb/retinanet.ipynb

This link does not work (both in windows ans macos) using tensorflow 2.4 :
https://github.com/keras-team/keras-io/blob/master/examples/vision/retinanet.py

Always the same error :
using a `tf.Tensor` as a Python `bool` is not allowed in Graph execution
________________________________
De : Srihari Humbarwadi <notifications@github.com>
Envoyé : jeudi 11 février 2021 21:43
À : keras-team/keras-io <keras-io@noreply.github.com>
Cc : sonpero <sonpero@hotmail.com>; Author <author@noreply.github.com>
Objet : Re: [keras-team/keras-io] Object Detection with RetinaNet : preprocess_data (#373)


I ran the notebook on colab and it works fine for me. Please let me know if you can run this script.
https://github.com/keras-team/keras-io/blob/master/examples/vision/retinanet.py

You could also try running it in colab using this
https://colab.research.google.com/github/keras-team/keras-io/blob/master/examples/vision/ipynb/retinanet.ipynb

**Comment by sachinprasadhs** [comment]
Hi,

The notebook is working fine with Tensorflow 2.13. 
Below is the working Gist. 
Keras recently introduced new optimizer, this notebook is not compatible with the new optimizer, it has to be changed to legacy optimizer like `optimizer = tf.keras.optimizers.legacy.SGD`.
I will create a PR for this fix, till then refer the Gist here https://gist.github.com/sachinprasadhs/1f6e4c79c128c1aa59e2bb0dbf19e0cf
