### ISSUE TITLE
Error when running inference on custom sentences section in semantic simmilarity with BERT.ipynb

### ISSUE THREAD

**Issue by sansanai** [keras-team/keras-io#387]
Hi, 
I am sorry but I am not good at engllish.
I am a newbie in bert. 
I tried to run the semantic_simmilarity_with_bert.ipynb on my gpu server, but I got an error, especially inference on custom sentences section after fine-tuning and evaluating model on the test set.
My GPU Server configuration is as follows.
- OS - Ubuntu 18.04
- GPU - RTX 2080 Super X 2
- tensoflow-gpu : 2.3.0
- transformers version: 3.1.0
- CUDA Toolkit : 10.0
- cudnn library : 7.6.4

I ran the cell 

sentence1 = "Two women are observing something together."
sentence2 = "Two women are standing with their eyes closed."
check_similarity(sentence1, sentence2) 

but I got error messages as follows.
 ---------------------------------------------------------------------------
CancelledError                            Traceback (most recent call last)
<timed exec> in <module>

<ipython-input-22-652753a1680e> in check_similarity(sentence1, sentence2)
      5     )
      6 
----> 7     proba = model.predict(test_data)[0]
      8     idx = np.argmax(proba)
      9     proba = f"{proba[idx]: .2f}%"

~/.conda/envs/tf23hf/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py in _method_wrapper(self, *args, **kwargs)
    128       raise ValueError('{} is not supported in multi-worker mode.'.format(
    129           method.__name__))
--> 130     return method(self, *args, **kwargs)
    131 
    132   return tf_decorator.make_decorator(

~/.conda/envs/tf23hf/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py in predict(self, x, batch_size, verbose, steps, callbacks, max_queue_size, workers, use_multiprocessing)
   1597           for step in data_handler.steps():
   1598             callbacks.on_predict_batch_begin(step)
-> 1599             tmp_batch_outputs = predict_function(iterator)
   1600             if data_handler.should_sync:
   1601               context.async_wait()

~/.conda/envs/tf23hf/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py in __call__(self, *args, **kwds)
    778       else:
    779         compiler = "nonXla"
--> 780         result = self._call(*args, **kwds)
    781 
    782       new_tracing_count = self._get_tracing_count()

~/.conda/envs/tf23hf/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py in _call(self, *args, **kwds)
    844               *args, **kwds)
    845       # If we did not create any variables the trace we have is good enough.
--> 846       return self._concrete_stateful_fn._filtered_call(canon_args, canon_kwds)  # pylint: disable=protected-access
    847 
    848     def fn_with_cond(*inner_args, **inner_kwds):

~/.conda/envs/tf23hf/lib/python3.7/site-packages/tensorflow/python/eager/function.py in _filtered_call(self, args, kwargs, cancellation_manager)
   1846                            resource_variable_ops.BaseResourceVariable))],
   1847         captured_inputs=self.captured_inputs,
-> 1848         cancellation_manager=cancellation_manager)
   1849 
   1850   def _call_flat(self, args, captured_inputs, cancellation_manager=None):

~/.conda/envs/tf23hf/lib/python3.7/site-packages/tensorflow/python/eager/function.py in _call_flat(self, args, captured_inputs, cancellation_manager)
   1922       # No tape is watching; skip to running the function.
   1923       return self._build_call_outputs(self._inference_function.call(
-> 1924           ctx, args, cancellation_manager=cancellation_manager))
   1925     forward_backward = self._select_forward_and_backward_functions(
   1926         args,

~/.conda/envs/tf23hf/lib/python3.7/site-packages/tensorflow/python/eager/function.py in call(self, ctx, args, cancellation_manager)
    548               inputs=args,
    549               attrs=attrs,
--> 550               ctx=ctx)
    551         else:
    552           outputs = execute.execute_with_cancellation(

~/.conda/envs/tf23hf/lib/python3.7/site-packages/tensorflow/python/eager/execute.py in quick_execute(op_name, num_outputs, inputs, attrs, ctx, name)
     58     ctx.ensure_initialized()
     59     tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
---> 60                                         inputs, attrs, num_outputs)
     61   except core._NotOkStatusException as e:
     62     if name is not None:

CancelledError:  [_Derived_]RecvAsync is cancelled.
	 [[{{node GroupCrossDeviceControlEdges_0/Identity_3/_849}}]]
	 [[functional_1/dense/Softmax/_845]] [Op:__inference_predict_function_371428]

Function call stack:
predict_function

-----------------------------
please let me know what is wrong with it and how to fix it...
thank you in advance.

**Comment by sachinprasadhs** [comment]
Hi, I was able to run Semantic Similarity with BERT without any error, since it is a large model, check your memory usage and limit, if it reaches the max memory limit then consider reducing the batch size.

Below is the working Gist attached for reference.

https://gist.github.com/sachinprasadhs/e5ff2c01e75c780fbebeca39c1848c9c
