### ISSUE TITLE
Error on save model

### ISSUE THREAD

**Issue by doritnap** [keras-team/keras-io#388]
Hi,
I try to save the model, but i get error: 'The two structures don't have the same nested structure' (see attached) while loading the model.
![image](https://user-images.githubusercontent.com/73097555/109624023-66f21380-7b46-11eb-842d-0960187c6037.png)

can you advise?

Thanks,
Dorit

**Comment by sansanai** [comment]
check this issue page https://github.com/huggingface/transformers/issues/3627

**Comment by doritnap** [comment]
> check this issue page [huggingface/transformers#3627](https://github.com/huggingface/transformers/issues/3627)

Seems that it helped... but now I'm gettting 'Some Python objects were not bound to checkpointed value... (
![image](https://user-images.githubusercontent.com/73097555/109768819-104a0f80-7c02-11eb-9cfb-29c80be8bda0.png)

I'm using tf.keras.models.save_model to save the model and tf.keras.models.load_model to load it.

Thanks in advance!

**Comment by doritnap** [comment]
> > check this issue page [huggingface/transformers#3627](https://github.com/huggingface/transformers/issues/3627)
> 
> Seems that it helped... but now I'm gettting 'Some Python objects were not bound to checkpointed value... (
> ![image](https://user-images.githubusercontent.com/73097555/109768819-104a0f80-7c02-11eb-9cfb-29c80be8bda0.png)
> 
> I'm using tf.keras.models.save_model to save the model and tf.keras.models.load_model to load it.
> 
> Thanks in advance!

Finally it works! I had to add checkpoint (in addition to the first suggestion).
Thanks!
