### ISSUE TITLE
Grad-CAM how to define the classification layer in case of layer concatenation?

### ISSUE THREAD

**Issue by Jimut123** [keras-team/keras-io#391]
So here is my model, I want to visualise the activation on the layer conv_64, what should I do?

![Keras Model](https://i.stack.imgur.com/lAw8m.png)

```python3
last_conv_layer_name = "conv_64"
classifier_layer_names = [      
    "concatenate_17", 
    "conv_64_2",              
    "max_pool3",                  
    "conv_64_3",                
    "conv_64_31",                
    "concatenate_18",                  
    "conv_64_32",             
    "max_pool4",                
    "conv_64_4",                  
    "conv_64_41",                  
    "concatenate_19",                  
    "conv_64_42",             
    "max_pool5", 
    "conv_64_5", 
    "max_pool6", 
    "flatten", 
    "dropout_3", 
    "dense_64", 
    "output_layer", 
]


# Generate class activation heatmap
heatmap = make_gradcam_heatmap(
    img_array, model, last_conv_layer_name, classifier_layer_names
)
```

This is what I am doing, but getting the following error when running The problem lies when we are concatenating two different layers and it is confusing the classifier of the GRAD CAM module...

```
(1, 360, 360, 3)
preds :  [[5.7032428e-16 1.0479534e-33 0.0000000e+00 1.0243782e-23 1.0000000e+00
  0.0000000e+00 0.0000000e+00 0.0000000e+00]]
Model: "model_11"
_________________________________________________________________
Layer (type)                 Output Shape              Param   No
=================================================================
input_9 (InputLayer)         [(None, 360, 360, 3)]     0         
_________________________________________________________________
conv_32 (Conv2D)             (None, 360, 360, 16)      448       
_________________________________________________________________
conv_64 (Conv2D)             (None, 360, 360, 1)       145       
=================================================================
Total params: 593
Trainable params: 593
Non-trainable params: 0
_________________________________________________________________

------------------------------------------------------------------------

/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/layers/merge.py in call(self, inputs)
    120   def call(self, inputs):
    121     if not isinstance(inputs, (list, tuple)):
--> 122       raise ValueError('A merge layer should be called on a list of inputs.')
    123     if self._reshape_required:
    124       reshaped_inputs = []

ValueError: A merge layer should be called on a list of inputs.
```

**Comment by YassineYousfi** [comment]
I believe the implementation in the example assumes there is no shortcut/new input to the next layers other than the output of  `last_conv_layer_name`.
I am currently working on contributing with a small extension of the notebook, and my version of grad cam would not raise this issue. Can you share a minimal code to reproduce?
Keep in mind that the grad cam at such early layers might not be very good, c.f. footnote 3 in the [grad cam paper](https://arxiv.org/pdf/1610.02391.pdf).

**Comment by Jimut123** [comment]
Hi @YassineYousfi,

Here is the minimal version for reproducing the error.
https://colab.research.google.com/drive/1nnnHlyGbuOgNGEDvF1DY9l0vlVzgu291?usp=sharing

Looks like it will be tough when we are using concat layer and focusing on an intermediate layer...

**Comment by Jimut123** [comment]
@YassineYousfi Just out of curiosity, when will it be ready?

**Comment by YassineYousfi** [comment]
I will try to submit a PR early next week. 

BTW in your minimal code, if you set the last layer's activation function to `None`, you can pick `conv_64_5` and it will give you this.

![minimal_grad_cam_conv_64_5](https://user-images.githubusercontent.com/29985433/110130782-669c8700-7d97-11eb-8ca0-af5b56cfa397.png)

**Comment by Jimut123** [comment]
Could you please share with me the notebook you modified?

**Comment by YassineYousfi** [comment]
https://colab.research.google.com/drive/1nnKQVnoeCu9x0AHCV7r5UU7hUyaOA5yd?usp=sharing

**Comment by Jimut123** [comment]
Thanks a lot!
