### ISSUE TITLE
Incorrect dot product in CF Example

### ISSUE THREAD

**Issue by Praful932** [keras-team/keras-io#397]
In [this ](https://keras.io/examples/structured_data/collaborative_filtering_movielens/) example of Collaborative Filtering, The shape of output of the dot product of `user_vector` & `movie_vector` for a batch should be `(batch_dim, 1)` currently `tf.tensordot(user_vector, movie_vector, 2)` returns a single value collapsing all batch dimensions

[Collab](https://colab.research.google.com/drive/1mI_Wig6AaxsIJuHQ6_zlXknIQZ6-b6m0?usp=sharing) reproducing the bug

**Comment by sachinprasadhs** [comment]
Hi,

Thanks for reporting the issue. 

In this case the batching is done at the `history = model.fit`.
When you print x.shape it will output TensorShape([64, 1]).

But the training samples are not batched, `x_train.shape` will output `(90752, 2)`.

So the current implementation holds good.

[Here](https://gist.github.com/sachinprasadhs/1182080d5ad35daaafa2326b8fc9bbf3) is the working Gist. Thanks
