### ISSUE TITLE
Loading the model after save give different predictions

### ISSUE THREAD

**Issue by doritnap** [keras-team/keras-io#400]
Using semantic_similarity_with_bert.py - 
I am saving the trained model using tensorflow: tf.saved_model.save(model, model_save_path) and then read it using tf.keras.models.load_model. Unfortunaetly, the predicted values are different.
While using the in-mem model, predictions are as exepcted. when loading it from file, the predictions are pretty random.
Any suggestion? 
Thanks in advance!

**Comment by sachinprasadhs** [comment]
Hi,

Could you please try saving with the new `keras` format using the Tensorflow version 2.13 and let us know if you still face an issue.
https://www.tensorflow.org/guide/keras/serialization_and_saving

Below is the working Gist of Semantic Similarity with BERT.

https://gist.github.com/sachinprasadhs/e5ff2c01e75c780fbebeca39c1848c9c
