### ISSUE TITLE
AttributeError: 'BertTokenizer' object has no attribute 'batch_encode_plus' in semantic_similarity_with_bert.ipynb

### ISSUE THREAD

**Issue by azizcu** [keras-team/keras-io#402]
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-88-06e7db75838d> in <module>()
      4     epochs=epochs,
      5     use_multiprocessing=True,
----> 6     workers=-1,
      7 )

5 frames
/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/training.py in fit(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, validation_batch_size, validation_freq, max_queue_size, workers, use_multiprocessing)
   1062           use_multiprocessing=use_multiprocessing,
   1063           model=self,
-> 1064           steps_per_execution=self._steps_per_execution)
   1065 
   1066       # Container that configures and calls `tf.keras.Callback`s.

/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/data_adapter.py in __init__(self, x, y, sample_weight, batch_size, steps_per_epoch, initial_epoch, epochs, shuffle, class_weight, max_queue_size, workers, use_multiprocessing, model, steps_per_execution)
   1110         use_multiprocessing=use_multiprocessing,
   1111         distribution_strategy=ds_context.get_strategy(),
-> 1112         model=model)
   1113 
   1114     strategy = ds_context.get_strategy()

/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/data_adapter.py in __init__(self, x, y, sample_weights, shuffle, workers, use_multiprocessing, max_queue_size, model, **kwargs)
    907         max_queue_size=max_queue_size,
    908         model=model,
--> 909         **kwargs)
    910 
    911   @staticmethod

/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/data_adapter.py in __init__(self, x, y, sample_weights, workers, use_multiprocessing, max_queue_size, model, **kwargs)
    777     # Since we have to know the dtype of the python generator when we build the
    778     # dataset, we have to look at a batch to infer the structure.
--> 779     peek, x = self._peek_and_restore(x)
    780     peek = self._standardize_batch(peek)
    781     peek = _process_tensorlike(peek)

/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/data_adapter.py in _peek_and_restore(x)
    911   @staticmethod
    912   def _peek_and_restore(x):
--> 913     return x[0], x
    914 
    915   def _handle_multiprocessing(self, x, workers, use_multiprocessing,

<ipython-input-85-37262cc6765a> in __getitem__(self, idx)
     48         # With BERT tokenizer's batch_encode_plus batch of both the sentences are
     49         # encoded together and separated by [SEP] token.
---> 50         encoded = self.tokenizer.batch_encode_plus(
     51             sentence_pairs.tolist(),
     52             add_special_tokens=True,

AttributeError: 'BertTokenizer' object has no attribute 'batch_encode_plus'

I have also try transformer version like this, !pip install transformers==2.11.0           but not worked

**Comment by MohamadMerchant** [comment]
Hi azizcu,

Please try by restarting your kernel after installing transformers==2.11.0 version as you may have a newer version already in your session and this might have caused an issue. So restart your kernel, install and import transformers. Hopefully this will work.

Thanks.

**Comment by azizcu** [comment]
Thank you it worked. I used it for the sentence pair regression task. But 'mae' is so large also validation loss and validation score is unchanged. can you suggest me what should I do for effective regression? 
I also try the output layer activation function as 'relu' but 'mae' is still larger.
