### ISSUE TITLE
Grad-Cam with Inceptionv3. TypeError: unhashable type: 'Dimension'.

### ISSUE THREAD

**Issue by Luca1236a** [keras-team/keras-io#403]
Hi, I'm trying to follow the GradCam code but I got an error: TypeError: unhashable type: 'Dimension'. 

Here is my model:
```
cnn_vec3 = InceptionV3(input_shape = (224,224,3), include_top = False, weights = 'imagenet', input_tensor=None)
x = cnn_vec3.output
x = GlobalAveragePooling2D()(x)
x = Dropout(0.2)(x)
inp1 = cnn_vec3.input
dense_layer = Dense(1024, activation = 'relu')(x)
dense_layer = Dropout(0.3)(dense_layer)
dense_layer = Dense(1024,activation='relu')(dense_layer)
dense_layer = Dropout(0.3)(dense_layer)
output_layer = Dense(1, activation = 'linear', name ='predict')(dense_layer) # linear is what 16bit did
model = Model(inputs=inp1,outputs=output_layer)
```

here is the error:
```
Traceback (most recent call last):

  File "<ipython-input-18-8ae3fe8aeecf>", line 2, in <module>
    x = bone_age_model.get_layer(layer_name)(x)

  File "C:\Users\Cong\Anaconda3\envs\py36_2\lib\site-packages\keras\engine\base_layer.py", line 434, in __call__
    self.assert_input_compatibility(inputs)

  File "C:\Users\Cong\Anaconda3\envs\py36_2\lib\site-packages\keras\engine\base_layer.py", line 339, in assert_input_compatibility
    x_shape[int(axis)] not in {value, None}):

TypeError: unhashable type: 'Dimension'
```

Is there any suggestion?

**Comment by YassineYousfi** [comment]
I can't reproduce your error, can you share a minimal example raising this error?

**Comment by SuryanarayanaY** [comment]
Hi @Luca1236a ,

I have tried replicating the error with the provided code snippet. The error can't be reproducible now. Either this is resolved in latest versions or the code snippet is not enough to replicate it. 

Could you please check the attached [gist](https://colab.research.google.com/gist/SuryanarayanaY/6f35b6a8c5954185dbd5b6b9e1b62821/kerasio_403.ipynb) and let us know if it resolved already.If not please submit a reproducible code snippet. Thanks!
