### ISSUE TITLE
Question about code example

### ISSUE THREAD

**Issue by marcospgp** [keras-team/keras-io#41]
In the following code example:

https://github.com/keras-team/keras-io/blob/master/examples/nlp/text_classification_from_scratch.py

Why is the training dataset divided into training and validation, if there is a test folder?

Why is there a need for a training, validation, and a test dataset? Wouldn't training & test suffice?

Isn't the 20% of training data we're throwing away valuable to improve the model's performance?

**Comment by fchollet** [comment]
> Why is there a need for a training, validation, and a test dataset? Wouldn't training & test suffice?

The goal is to let you use the validation data to tune hyperparameters such as model architecture, etc. You shouldn't use the test dataset for this.

> Isn't the 20% of training data we're throwing away valuable to improve the model's performance?

Yes, it is. In the real world, once you've achieved a good architecture, you would retrain it on all available data (minus the test dataset).
