### ISSUE TITLE
Example image_classification_efficientnet_fine_tuning fails due to TPU/local file system problem

### ISSUE THREAD

**Issue by LanceNorskog** [keras-team/keras-io#414]
This is the same problem as in #223.

https://colab.research.google.com/github/keras-team/keras-io/blob/master/examples/vision/ipynb/image_classification_efficientnet_fine_tuning.ipynb

Apparently it is possible to rewrite these tutorials to use the local files correctly.

This is really a process issue... how did this example get checked in? The 'View in Colab' button does not yield a running notebook. It could never have worked in Colab.

Cheers!

**Comment by sayakpaul** [comment]
Cc: @yixingfu

**Comment by yixingfu** [comment]
If I understand correctly you are seeing (https://cloud.google.com/tpu/docs/troubleshooting#cannot_use_local_filesystem)? The notebook works with GPU as-is, but in general to use TPU you need to have a GCS bucket ready. In the notebook it is noted:

> For TPU: if using TFDS datasets, a [GCS bucket](https://cloud.google.com/storage/docs/key-terms#buckets) location is required to save the datasets. For example: 
> `tfds.load(dataset_name, data_dir="gs://example-bucket/datapath")`
> Also, both the current environment and the TPU service account have proper [access](https://cloud.google.com/tpu/docs/storage-buckets#authorize_the_service_account) to the bucket. Alternatively, for small datasets, you may try loading data into the memory and use `tf.data.Dataset.from_tensor_slices()`.

I am not sure if there is a better solution for this today.

**Comment by LanceNorskog** [comment]
Right, it's not a problem at the level of this notebook. I was too harsh. My apologies.
I will close the issue.
