### ISSUE TITLE
WGAN-GP Example uses normal noise instead of uniform noise as it is detailed in the paper

### ISSUE THREAD

**Issue by loris2222** [keras-team/keras-io#415]
`line 273        alpha = tf.random.normal([batch_size, 1, 1, 1], 0.0, 1.0)`

Interpolation is done using `tf.random.normal` as alpha instead of `tf.random.uniform`.
Is this an error or is there some reasoning? The paper clearly states uniform noise in the algorithm.
![image](https://user-images.githubusercontent.com/1367018/111766061-60cd9800-88a5-11eb-8256-775ae0902740.png)

**Comment by sachinprasadhs** [comment]
@AakashKumarNain , Could you please confirm if using `tf.random.normal` was intentional in your tutorial here https://keras.io/examples/generative/wgan_gp/.

Else, I can go ahead and create a PR to use `tf.random.uniform`.  Thanks!

**Comment by AakashKumarNain** [comment]
@sachinprasadhs you can make a PR, though it won't make much of a difference on the quality
