### ISSUE TITLE
Running vae.py throws error

### ISSUE THREAD

**Issue by DaemonNet** [keras-team/keras-io#420]
Hi, 

when trying to run vae.py (by copy/paste) with Keras 2.4.3 I get the error "When subclassing the `Model` class, you should implement a `call` method.".

I have tried to implement the call method and integrate the architecture, but then more errors appear. Can you help?

**Comment by sachinprasadhs** [comment]
Hi, I was able to successfully run `Variational Autoencoder` https://keras.io/examples/generative/vae/ using Tensorflow/Keras 2.13.1.

[Here](https://gist.github.com/sachinprasadhs/8f68b2e4c1e15db333d8beaf55392cfd) is the attached Gist for reference. Thanks!
