### ISSUE TITLE
CutMix Implementation with Keras 

### ISSUE THREAD

**Issue by sayannath** [keras-team/keras-io#421]
Hello Keras Team! I want to contribute to the coding example at keras.io by implementing CutMix implementation for image classification with Keras. Can anyone assign me or may I directly work on it and send a PR.

Paper: https://arxiv.org/pdf/1905.04899.pdf

Thank You!

**Comment by sayakpaul** [comment]
You can start working on it and send over a PR.

**Comment by sayannath** [comment]
Ok @sayakpaul 👍
