### ISSUE TITLE
AttributeError: module 'tensorflow.keras.preprocessing' has no attribute 'image_dataset_from_directory'

### ISSUE THREAD

**Issue by MrBuggySan** [keras-team/keras-io#43]
Following the sample doc here: https://github.com/keras-team/keras-io/blob/master/examples/vision/image_classification_from_scratch.py

and I'm getting the following error:
`AttributeError: module 'tensorflow.keras.preprocessing' has no attribute 'image_dataset_from_directory'`

tensorflow version:
2.2.0
keras version:
2.3.0-tf

I was looking at the source itself: https://github.com/tensorflow/tensorflow/tree/master/tensorflow/python/keras/preprocessing
and there it looks good

but in my local I don't see image_dataset_from_directory, I have the up to date versions though.

Can anyone explain the gap?

I installed using pip on macOS

`pip3.7 install -U tensorflow==2.2.0`

**Comment by fchollet** [comment]
Use the nightly build:

`pip install tf-nightly`

**Comment by viswanath27** [comment]
Hi Team, 
I am also having same issue, while running the example in tensorflow tutorials "Basic text classification" under "ML basics with Keras". 

Traceback (most recent call last):
  File "main.py", line 77, in <module>
    text_classification()
  File "main.py", line 71, in text_classification
    load_dataset(train_dir)
  File "main.py", line 29, in load_dataset
    raw_train_ds = tf.keras.preprocessing.text_dataset_from_directory(
AttributeError: module 'tensorflow.keras.preprocessing' has no attribute 'text_dataset_from_directory'

tensorflow version = 2.2.0
Python version = 3.6.9

I tried installing tf-nightly also. But it did not solve the issue. 
Any more pointers to fix this issue.

**Comment by guayabas** [comment]
try tensorflow 2.3.0, that one contains text_dataset_from_directory ... at least on Windows
![image](https://user-images.githubusercontent.com/1096151/88957729-34043c00-d254-11ea-9193-e50c19562ebe.png)

**Comment by jyan83** [comment]
Following the problem. I also installed tf-nightly, but still showing 

AttributeError: module 'tensorflow_core.keras.preprocessing' has no attribute 'timeseries_dataset_from_array'

**Comment by GF-Huang** [comment]
Same issue, tf-2.3.1

**Comment by LabyrinthineLeo** [comment]
I have solved this problem by `pip install tf-nightly`. If you did it but it ditn't take effect, you should restart your IDE or Jupyter notebook. I hope this comment is helpful for you!

**Comment by Yami-Bitshark** [comment]
**FOR PEOPLE USING DOCKER TF FOR WSL2** and **dont want to update their image**:

1.  Go to https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/preprocessing
2. Download **datasets_utils.py** **and text_dataset.py**
3. make them as a module and call them within your project.

 **Note:**   text_datasets.py calls functions from datasets_utils.py. So you have to update the **text_datasets.py file (Line 23)** and make it **import the datasets_utils.py** properly.

**Comment by Lawrence-Krukrubo** [comment]
> Use the nightly build:
> 
> `pip install tf-nightly`

After installing the nightly build in Kaggle, it still fails with no module found! Yet it works out of the box in Colab, why do we have all these inconsistencies? And how exactly can I use the image-dataset-from-directory function in Kaggle?

Has anyone successfully tried this in Kaggle?

Please I need to know urgently.

**Comment by ReyCJ** [comment]
> Use the nightly build:
> 
> `pip install tf-nightly`

Thanks, but this didn't work for me.
I solved the problem with upgrading the TensorFlow, you may go with:
`pip install --upgrade tensorflow`

**Comment by sudobum** [comment]
pip install tf-nightly   

RESTART
worked for me.

**Comment by Dinesh-Mali** [comment]
I have created environment via "conda create workspace"

There I installed all necessary packages via conda, where tensorflow2.0.0 installed.

while importing 

from Tensorflow.keras.layers import TextVectorization giving me import error that can not import TextVectorization and  I'm getting the following error:
AttributeError: module 'tensorflow.keras.preprocessing' has no attribute 'image_dataset_from_directory'

when trying to solve:  https://github.com/keras-team/keras-io/blob/master/examples/vision/image_classification_from_scratch.py

my TensorFlow version: 2.0.0
python version: 3.7.12

I tried pip3 install tf-nightly: got error zsh: illegal hardware instruction and module "tensorflow not found".

please help.

**Comment by prsatyal** [comment]
Try using 

tf.keras.applications.vgg16.preprocess_input(X, Dtype)
tf.keras.applications.resnet50.preprocess_input(x, data_format=None)

**Comment by benbezzina4** [comment]
make sure you are importing keras from tensorflow

import tensorflow as tf
from tensorflow import keras

**Comment by UDshadow** [comment]
> 

This works for me.
tf.__version__ = '2.12.0'
keras.__version__ = '2.12.0'

**Comment by UDshadow** [comment]
> make sure you are importing keras from tensorflow
> 
> import tensorflow as tf from tensorflow import keras

This works for me.
tf.version = '2.12.0'
keras.version = '2.12.0'

**Comment by UDshadow** [comment]
> make sure you are importing keras from tensorflow
> 
> import tensorflow as tf from tensorflow import keras

This answer works for me.
my version is:
tf.version = '2.12.0'
keras.version = '2.12.0'
