### ISSUE TITLE
Tensorflow Cloud Run - entry_point - File Not Found

### ISSUE THREAD

**Issue by vasilkosturski** [keras-team/keras-io#433]
I am following the guide for training a TF model in GCP from a local Jupyter Notebook.

I have a project with multiple documents so I decided I need to go with the entrypoint approach.

Here is how my `tfc.run` command looks like:
```
import tensorflow_cloud as tfc
tfc.run(
    docker_image_bucket_name='bucket_name',
    requirements_txt="requirements.txt",
    entry_point="entrypoint.py"
)
```
The file `entrypoint.py` is in the same directory as the notebook.

Still, when the after the GCP build I get the following error in the logs:
**"FileNotFoundError: [Errno 2] No such file or directory: 'entrypoint.py'"**

Please suggest what I might be missing here.

**Comment by sachinprasadhs** [comment]
Hi,

For tensorflow_cloud related topic, please follow the detailed guide here https://colab.research.google.com/github/tensorflow/cloud/blob/master/g3doc/tutorials/distributed_training_nasnet_with_tensorflow_cloud.ipynb
Thanks!
