### ISSUE TITLE
what is the best way to classify multivariate(5-10 features) time series data of variable length 50-100 into classes(10-20)

### ISSUE THREAD

**Issue by aafaqin** [keras-team/keras-io#434]
what is the best way to classify multivariate(5-10 features) time series data of variable length 50-100 into classes(10-20)
example-
https://keras.io/examples/timeseries/timeseries_classification_from_scratch/#introduction

but this is just a single feature classifier

**Comment by omrylcn** [comment]
hi aafaqin 
you can try some state of art time series classification algorihms like ROCKET, Those links  can help your problem

- https://towardsdatascience.com/a-brief-introduction-to-time-series-classification-algorithms-7b4284d31b97
- https://pub.towardsai.net/rocket-fast-and-accurate-time-series-classification-f54923ad

**Comment by sachinprasadhs** [comment]
Hi @aafaqin ,

Could you please refer the above comment and also refer https://www.analyticsvidhya.com/blog/2020/10/multivariate-multi-step-time-series-forecasting-using-stacked-lstm-sequence-to-sequence-autoencoder-in-tensorflow-2-0-keras/ which could help you. Thanks!
