### ISSUE TITLE
Training RetinaNet on TPU is stuck

### ISSUE THREAD

**Issue by awsaf49** [keras-team/keras-io#435]
I tried training **RetinaNet** using **TPU** but the training is stuck. I'm guessing this is due to **GCS** path. Any idea how to add **GCS** path on training for **TPU** ?

**Comment by srihari-humbarwadi** [comment]
TPUs require you to store your tfrecords in a GCS bucket, you will have to transfer them and point `tensorflow_datasets` to load them from the GCS bucket.
