### ISSUE TITLE
Link doesn't exist in KeratTuner guide

### ISSUE THREAD

**Issue by rustypython** [keras-team/keras-io#516]
This page [ https://keras.io/keras_tuner/ ] says:

To learn more about KerasTuner, check out [this starter guide](url).

The link doesn't exist though, shows 404: Page not found

**Comment by dheerajrp** [comment]
![Screenshot from 2022-04-12 12-50-39](https://user-images.githubusercontent.com/12818055/162903880-45dca95e-3fe4-4765-9f0d-5363fc21cc7d.png)
It is working

**Comment by SuryanarayanaY** [comment]
Hi @rustypython ,

I have checked the mentioned link here To learn more about KerasTuner, check out [this starter guide](https://keras.io/guides/keras_tuner/getting_started/) and its working fine now.


<img width="1512" alt="Screenshot 2023-07-28 at 7 14 01 PM" src="https://github.com/keras-team/keras-io/assets/116063290/6d5f356d-0971-45eb-944e-afaf8402db46">







You can also verify opening the link attached above. Thanks!
