### ISSUE TITLE
Image_captioning: How to save the model?

### ISSUE THREAD

**Issue by Ebimsv** [keras-team/keras-io#518]
Hello
I get this error when I try to save the model:

cannot be saved because the input shapes have not been set. Usually, input shapes are automatically determined from calling `.fit()` or `.predict()`. To manually set the shapes, call `model.build(input_shape)`.

please help me if you know how to resolve this Error

**Comment by krishnaraj-sr** [comment]
Did you get any solution to this issue?

**Comment by shaunaa126** [comment]
I think this is also referenced in this issue https://github.com/keras-team/keras-io/issues/1364

**Comment by sachinprasadhs** [comment]
Hi, In order to save the model with custom object using Keras saving format `.keras` you need to override the `get_config() `method, for detailed steps follow the guide here https://keras.io/guides/serialization_and_saving/#custom-objects
