### ISSUE TITLE
How to correctly save and load a model with custom CTC layer (Keras example)

### ISSUE THREAD

**Issue by amirh0ss3in** [keras-team/keras-io#532]
I am following this tutorial on Keras :
https://keras.io/examples/vision/captcha_ocr/
but I don't know how to correctly save this model with custom layer after the training; and then load it separately. Can anyone point me in the right direction?

**Comment by ajohnson49** [comment]
You might try calling model.save_weights() to save just the weights and then load those into a new instance of the model definition

**Comment by amirh0ss3in** [comment]
The method you mentioned, simply just doesn't work.

**Comment by SuryanarayanaY** [comment]
For saving and reloading a custom layer in subclassed model we need to implement get_config() and from_config() methods. Consider an example below.

```
class CustomLayer(keras.layers.Layer):
    def __init__(self, sublayer, **kwargs):
        super().__init__(**kwargs)
        self.sublayer = layer

    def call(self, x):
        return self.sublayer(x)

    def get_config(self):
        base_config = super().get_config()
        config = {
            "sublayer": keras.saving.serialize_keras_object(self.sublayer),
        }
        return {**base_config, **config}

    @classmethod
    def from_config(cls, config):
        sublayer_config = config.pop("sublayer")
        sublayer = keras.saving.deserialize_keras_object(sublayer_config)
        return cls(sublayer, **config)
```

For more details on custom objects please refer to attached [resource](https://www.tensorflow.org/guide/keras/serialization_and_saving#registering_the_custom_object) here.
