### ISSUE TITLE
oriented Output for RetinaNet? 

### ISSUE THREAD

**Issue by whoisibooo** [keras-team/keras-io#539]
Hi guys, 

is it possible to implement rotated anchor boxes for a oriented output like this example ? 

![image](https://user-images.githubusercontent.com/84685424/123955348-cacc0200-d9a9-11eb-8576-ec50e4f18787.png)

best regards, 
whoisibooo

**Comment by sachinprasadhs** [comment]
Hi, 

Unfortunately, I could not find any implementation done using Tensorflow to predict the oriented bonding boxes.

In practical, it can be done by providing the training samples accordingly to predict the last value as rotation angle.

I was able to get some references to the research paper which should give you good understanding to start implementing.

https://arxiv.org/pdf/2008.07043.pdf

https://arxiv.org/pdf/2109.10187.pdf
