### ISSUE TITLE
Old documentation style was better on the eyes.

### ISSUE THREAD

**Issue by may-son** [keras-team/keras-io#55]
New style documentation problems:
1. All page is pure white without light gray and dark gray elements as was in the old style.
2. All the way "black" code blocks. Just look at YouTube's nice gray color (In the dark mode of course).

If the new style is going to be as is, please add dark or dim theme.

**Comment by yaroslav-semeniuk** [comment]
### This is Dark Reader plugin for Chrome:
![image](https://user-images.githubusercontent.com/49318488/83328815-92319480-a28e-11ea-9333-63730cd9eca0.png)

Very beautiful. Added just for example and inspiration.

**Comment by sachinprasadhs** [comment]
Hi, 

Thanks for reporting the issue, while the look and styling preference changes from each individual.

We try to provide the best experience to the user community, Keras team is not having any plan to make any changes to the existing design.
Based on the internal team decision, we will update the website accordingly.

Thanks for understanding.

**Comment by MimoHasPurpose** [comment]
make the keras website darkk, it hurts my eyessssssssssssssssssssss

**Comment by MimoHasPurpose** [comment]
make the keras website darkk, it hurts my eyessssssssssssssssssssss
