### ISSUE TITLE
Clarify Keras Version in API Docs

### ISSUE THREAD

**Issue by dleve123** [keras-team/keras-io#577]
## Problem:

It seems like the [API documentation at keras.io](https://keras.io/api) documents a version of the codebase that is more recent than the latest stable release of keras that installed upon `pip install tensorflow`.

Let's take the documentation for [`StringLookup` ](https://keras.io/api/layers/preprocessing_layers/categorical/string_lookup/). One cool feature of `StringLookup` is `'one_hot'` `output_mode`. Here's an example from the documentation page:

```blockquote
One-hot output

Configure the layer with output_mode='one_hot'. Note that the first num_oov_indices dimensions in the ont_hot encoding represent OOV values.


>>> vocab = ["a", "b", "c", "d"]
>>> data = tf.constant(["a", "b", "c", "d", "z"])
>>> layer = StringLookup(vocabulary=vocab, output_mode='one_hot')
>>> layer(data)
<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
  array([[0., 1., 0., 0., 0.],
         [0., 0., 1., 0., 0.],
         [0., 0., 0., 1., 0.],
         [0., 0., 0., 0., 1.],
         [1., 0., 0., 0., 0.]], dtype=float32)>
```

Without given any more information, I think it's reasonable to expect that the official Keras docs document the latest stable release of the package, but I don't think it does. Consider the following developer journey.

### Developer Journey:

- `pip install tensorflow` installs, at latest, TF v2.5.0 (https://pypi.org/project/tensorflow/#history)
- Developer googles arounds regarding one-hot encoding layers for TF and ends up on the [`StringLookup` docs](https://keras.io/api/layers/preprocessing_layers/categorical/string_lookup/) and learns about the one_hot output mode
- TF 2.5.0's version of [`StringLookup`](https://github.com/tensorflow/tensorflow/blob/v2.5.0/tensorflow/python/keras/layers/preprocessing/string_lookup.py) does not include the `one_hot` `output_mode` as it was added in a [commit](https://github.com/tensorflow/tensorflow/commit/4620f01208b6787e8886381ffbb07619e8c7d00b) post cutting the 2.5 release
- Confusion/surprise!

## Possible Solutions:

- [probably hard] Document latest stable release of keras at keras.io -- I appreciate this might be tricky at the moment considering the evolving code structure between TF and Keras.
- [hopefully less hard] State the version of the dependency being documented.

I think Rails does a particularly good job of this hard problem. Their docs (https://www.google.com/search?q=rails+api+docs&safe=active&ssui=on):

1. Include the version in the website header
2. Persist older documentation releases which are accessible via a URL path (e.g. https://api.rubyonrails.org/v5.1/)

---

Thanks for the awesome library and let me know if/how I can be helpful here!

**Comment by SuryanarayanaY** [comment]
Hi @dleve123 ,

We are in the process of going through backlogs. I think this is not an issue now with latest release not sure how it was when this issue was opened.I think the documentation now have enough information regarding `output_mode` parameter.

> **output_mode**: Specification for the output of the layer. Values can be "int", "one_hot", "multi_hot", "count", or "tf_idf" configuring the layer as follows: - "int": Return the raw integer indices of the input tokens. - "one_hot": Encodes each individual element in the input into an array the same size as the vocabulary, containing a 1 at the element index. If the last dimension is size 1, will encode on that dimension. If the last dimension is not size 1, will append a new dimension for the encoded output. - "multi_hot": Encodes each sample in the input into a single array the same size as the vocabulary, containing a 1 for each vocabulary term present in the sample. Treats the last dimension as the sample dimension, if input shape is (..., sample_length), output shape will be (..., num_tokens). - "count": As "multi_hot", but the int array contains a count of the number of times the token at that index appeared in the sample. - "tf_idf": As "multi_hot", but the TF-IDF algorithm is applied to find the value in each token slot. For "int" output, any shape of input and output is supported. For all other output modes, currently only output up to rank 2 is supported. Defaults to "int"

The document will be updated with each major release and will contain the information related to latest release only.

If still missing anything here please let us know.

Thanks!

**Comment by dleve123** [comment]
@SuryanarayanaY The real intent of this GH issue is to make the version of Keras being documented clear in the documentation webpage – that doesn't seem to have happened, but I might be missing something. Either way, not a priority on my side, so feel free to close this if you want to clear up the backlog!

**Comment by SuryanarayanaY** [comment]
Keras maintaining the documentation of latest stable release. For every API there is a SOURCE link which will redirect to the version of Keras in case if anyone have doubt one can click the SOURCE and it will confirm the version of Keras.
