### ISSUE TITLE
Regarding adding examples of semi-supervised image classification with GANs

### ISSUE THREAD

**Issue by sayakpaul** [keras-team/keras-io#59]
Now that the fields of semi-supervised and self-supervised learning are becoming more and more important, I wish to cover an example showing how to train GANs for semi-supervised image classification (can be referred to as weakly supervised learning too). 

I have a [Colab Notebook](https://colab.research.google.com/drive/1mwc_r6UuuH_lfWjNOO7OgGwaHaihHM7h?usp=sharing) that might be useful. If this proposal is accepted I will, of course, adhere to the Keras blog format. I used `tf.GradientTape` (did not override `train_step`) as I found it was actually more readable that way. 

**Note**: In order to show the full potential of using GANs in this context, one might need to train longer than shown here.

**Comment by sayakpaul** [comment]
@fchollet did you have the chance to consider it? If not I can definitely understand you might have been swamped :)

**Comment by fchollet** [comment]
What's the TL;DR of what the code does?

**Comment by sayakpaul** [comment]
It shows how to use a vanilla DCGAN for image classification in a semi-supervised way. The benefit we get here is this technique can really shine when we don't have access to a lot of labeled data. It's, in fact, a minimal implementation of [this paper](https://arxiv.org/abs/1606.01583).

**Comment by fchollet** [comment]
I think it's somewhat too experimental and not practical enough to be featured as a code example. But a state-of-the-art semi-supervised classification example would be great I think.

**Comment by sayakpaul** [comment]
When proposing this idea, my understanding was that a lot of people would be interested in the workflow that uses GANs for semi-supervised learning problems. I will drop it if it does not reflect that thought. 

> But a state-of-the-art semi-supervised classification example would be great I think.
Any recommendations?

**Comment by sachinprasadhs** [comment]
Hi @sayakpaul , Just checking if this is issue is still valid. 
If not, could you please close the issue. Thanks!
