### ISSUE TITLE
Saving the best model according to best val accuracy.

### ISSUE THREAD

**Issue by QuickLearner171998** [keras-team/keras-io#61]
I have a multi-output model. I need to save the model checkpoints according to the best mean val accuracy. I think the best way is to write a custom loop. But can I do this by overriding test_step like in - https://github.com/keras-team/keras-io/blob/ed9a296ae7c00ea79eb7a5b6f15ce57a2ed8b38f/guides/customizing_what_happens_in_fit.py#L232

**Comment by fchollet** [comment]
The simplest way to do this is actually to use a Callback. In fact, the `ModelCheckpoint` callback already enables exactly this use case.

**Comment by QuickLearner171998** [comment]
Actually I have a multi-output model, so there is a different metric for each output. ModelCheckpoint monitors only a single metric at a time, right?
