### ISSUE TITLE
about keras-io/examples/nlp/semantic_similarity_with_bert.py

### ISSUE THREAD

**Issue by xmcs111** [keras-team/keras-io#611]
from 1 to 269 line,print(f"Strategy: {strategy}")
model.summary()
After execution, the following error is reported:
`2021-08-29 00:16:22.311887: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
WARNING:tensorflow:Not all devices in `tf.distribute.Strategy` are visible to TensorFlow.
Traceback (most recent call last):
  File "D:/.../PycharmProjects/.../Semantic Similarity with BERT.py", line 190, in <module>
    bert_model = transformers.TFBertModel.from_pretrained("bert-base-uncased")
AttributeError: module 'transformers' has no attribute 'TFBertModel'
`tensorflow==1.13.0rc1,python=3.7

**Comment by batermj** [comment]
Traceback (most recent call last): 
        File "semantic_similarity_with_bert.py", line 250, in <module> 
        )(sequence_output)         

TypeError: Inputs to a layer should be tensors. Got: last_hidden_state 


keras                         2.6.0        
torch                         1.9.1   
tensorflow                    2.6.0

**Comment by SuryanarayanaY** [comment]
Hi @xmcs111 ,

Starting from TF1.6 versions tensorflow prebuilt binaries built with AVX instructions set. If your CPU does not support AVX then you may get such error and tensorflow prebuilt binaries will not work. In such scenario you need to build from source or use community supported prebuilt binaries that don't have AVX instructions. 

Please refer to the tensorflow ticket #[19584 ](https://github.com/tensorflow/tensorflow/issues/19584) for more details.

I hope this will answer your query. Please let us know if this is still an issue for you.
Thanks!
