### ISSUE TITLE
Bug - "Timeseries classification with a Transformer model" example is duplicated

### ISSUE THREAD

**Issue by ddofer** [keras-team/keras-io#615]
The timeseries classification example is duplicated:
(There are 2 example for it on the site, near identical except for the URL): 
https://keras.io/examples/timeseries/timeseries_classification_transformer/
https://keras.io/examples/timeseries/timeseries_transformer_classification/

**Comment by Qcosmo** [comment]
+1

**Comment by sachinprasadhs** [comment]
Hi,

Thanks for reporting the issue.

Now the duplicate section has been removed, now both the URLs will lead to the same tutorial page.
