### ISSUE TITLE
Question about using pre-exisitng code for Text-To-Speech example

### ISSUE THREAD

**Issue by DarshanDeshpande** [keras-team/keras-io#618]
I am planning to add an end-to-end text-to-speech example to Keras using Tacotron2 and MelGAN(custom). The issue I am facing is that the Tacotron2 model code from the TensorFlowTTS library is in itself 1000+ lines, with other networks like FastSpeech spanning much more than that. I have tried to shrink this code to the barebones and can only manage to get it to ~700 lines. This is clearly not acceptable so I just wanted to confirm if it is okay if I could just import the architecture directly from the TensorFlowTTS repository (pip installable). I have seen an example using the BERT architecture from the transformers library so I wanted to make sure it is okay for me to do something similar. It is written with the latest version of tensorflow and tf.keras so I can assure you that there will be no issues with compatibility.  

Thanks in advance!

@fchollet

**Comment by SuryanarayanaY** [comment]
Hi @DarshanDeshpande ,

Some of keras tutorials imports some libraries like transformers. If you are still working on this and interested to contribute maybe you can submit a proposal for review.

Thanks!
