### ISSUE TITLE
Probably a typo in the Multi-GPU guide notebook

### ISSUE THREAD

**Issue by salah3x** [keras-team/keras-io#62]
I think this is a mistake, and it should be `since it runs on a single machine and does **not** need to communicate with other machines` instead of `since it runs on a single machine and does need to communicate with other machines`

https://github.com/keras-team/keras-io/blob/6e6ffd12e95c068f0290c9589aa1d6ce721fcb64/guides/distributed_training.py#L367

**Comment by fchollet** [comment]
Indeed! Please submit a PR to fix it.
