### ISSUE TITLE
Broken compatibility with h5 model export and Java

### ISSUE THREAD

**Issue by Samurus** [keras-team/keras-io#633]
Hi, 
i was trying to run this example and use the output model with Java:
https://github.com/keras-team/keras-io/blob/master/examples/structured_data/structured_data_classification_from_scratch.py

These were my last approaches:
When importing new h5 model with DL4j I get this error message:
"org.deeplearning4j.nn.modelimport.keras.exceptions.InvalidKerasConfigurationException: Expected model class name Model (found Functional)."
Related issues:
https://github.com/keras-team/keras/issues/14360
Used guide: https://deeplearning4j.konduit.ai/deeplearning4j/how-to-guides/keras-import

When downgrading TensorFlow to 2.2.2 and removing all pre-processing since that wasn't available I can use the model within Java but the training doesnt work well enough.  I want to use it similar to this old h5-compatible version:
ComputationGraph kerasModelGraph = KerasModelImport.importKerasModelAndWeights(
    "path/model.h5");
kerasModelGraph.init();

org.nd4j.linalg.api.ndarray.INDArray[] kerasInput = mapKerasInput(someInputData);
INDArray[] predicted = kerasModelGraph.output(kerasInput);
if (predicted[0].data().asDouble()[0] > 0.5D) {     return 1; } 

I cannot find any working example but only errors with import. 
https://www.baeldung.com/tensorflow-java not up-to-date
https://www.tensorflow.org/jvm/api_docs/java/org/tensorflow/package-summary no good examples yet
https://www.tensorflow.org/api_docs/java/org/tensorflow/package-summary deprecated and not working examples

How can I use model for above example with Java?

**Comment by pcoet** [comment]
Hi @Samurus, thanks for reaching out. For support questions, please use one of the resources below. Your question will have better visibility that way.

* [TensorFlow forum](https://discuss.tensorflow.org/)
* [Keras mailing list](https://groups.google.com/forum/#!forum/keras-users)

Thanks!
