### ISSUE TITLE
Best Optimizers Ever

### ISSUE THREAD

**Issue by thchi** [keras-team/keras-io#652]
I have just developed a new optimizer that gives me the best results of all the algorithms included in keras .

The evalutions is made on MNIST and IMBD datasets running
![114](https://user-images.githubusercontent.com/38048537/135756859-507a399f-64f1-49ca-9355-c8ebd333def1.png)
![113](https://user-images.githubusercontent.com/38048537/135756863-067f03a4-f1ac-4ff0-bbc7-558c71d80b3c.png)
![112](https://user-images.githubusercontent.com/38048537/135756865-e98ed7c2-8fc0-4a9a-a42c-bf143a8edf71.png)
![111](https://user-images.githubusercontent.com/38048537/135756867-ddb8f16d-4820-4db7-a279-84a1a57a2ea4.png)
 on a local machine.

I want to try my optimizers in large scale but I don't have a GPU.

I tried to use google colab but it may not allow it or there is a problem with the code. 

any help could be provided.

thanks

**Comment by SuryanarayanaY** [comment]
Hi @thchi ,

Congrats for your work. But this platform is for supporting `keras.io` documentation and tutorials. Google colab do have free GPU support(for limited time) which you may explore.

Please feel free to close the issue. Thanks!
