### ISSUE TITLE
Question about calculating the spectrogram

### ISSUE THREAD

**Issue by ZhuPan2016** [keras-team/keras-io#654]
@rbouadjenek @fchollet 
Thanks for your great tutorials which I learned a lot from.

I have a small question about this line [code](https://github.com/keras-team/keras-io/blob/master/examples/audio/ctc_asr.py#L162).

The tf.abs() do the computation that:
![](https://render.githubusercontent.com/render/math?math=\sqrt{real^{2}%20%2B%20imaginary^{2}})

Why did you do the sqrt again in this line of [code](https://github.com/keras-team/keras-io/blob/master/examples/audio/ctc_asr.py#L162)?

**Comment by ZhuPan2016** [comment]
@rbouadjenek 
Thanks for your timely reply.

But the `tf.signal.stft()` returns the tensor of complex64 type.
![](https://raw.githubusercontent.com/ZhuPan2016/pic_bed/master/stfy.PNG)

So I'm not sure the necessity of doing the sqrt operation after the `tf.abs()`.

**Comment by rbouadjenek** [comment]
@ZhuPan2016 
Thanks for pointing that out. Check this tutorial:
https://www.tensorflow.org/tutorials/audio/simple_audio
they have used `tf.abd()` after `tf.signal.stft`
They have also used the same in this example:
https://keras.io/examples/audio/transformer_asr/
`x = tf.math.pow(tf.abs(stfts), 0.5)`
Finally, this example also:
https://keras.io/examples/audio/speaker_recognition_using_cnn/
`return tf.math.abs(fft[:, : (audio.shape[1] // 2), :])`

**Comment by ZhuPan2016** [comment]
Thank you, I will check these tutorials.
