### ISSUE TITLE
Image classification from scratch example 

### ISSUE THREAD

**Issue by SystemZ** [keras-team/keras-io#66]
Hi, I don't have much experience with Python, Tensorflow and Keras.
I wanted to learn more about keras by using example that got my attention.

I downloaded [notebook from colab](https://colab.research.google.com/github/keras-team/keras-io/blob/master/examples/vision/ipynb/image_classification_from_scratch.ipynb) linked @ https://keras.io/examples/vision/image_classification_from_scratch/ and imported it in Jupyter based on official TF container with TF 2.1.0:
```bash
docker run --rm -it -p 8888:8888 tensorflow/tensorflow:latest-py3-jupyter
```
All i modified in this container was

```bash
apt-get install unzip
```
to allow downloading example image set.

Unfortunately on this step:

```python
image_size = (180, 180)
batch_size = 32

train_ds = tf.keras.preprocessing.image_dataset_from_directory(
    "PetImages",
    validation_split=0.2,
    subset="training",
    seed=1337,
    image_size=image_size,
    batch_size=batch_size,
)
val_ds = tf.keras.preprocessing.image_dataset_from_directory(
    "PetImages",
    validation_split=0.2,
    subset="validation",
    seed=1337,
    image_size=image_size,
    batch_size=batch_size,
)
```

I have this error:

```plain
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-6-818e7bae4d07> in <module>
      2 batch_size = 32
      3 
----> 4 train_ds = tf.keras.preprocessing.image_dataset_from_directory(
      5     "PetImages",
      6     validation_split=0.2,

AttributeError: module 'tensorflow_core.keras.preprocessing' has no attribute 'image_dataset_from_directory'
```

Just to be sure I also tried `pip install keras` in container but I didn't saw any difference.

I'm not sure if it's my fault or it's some mistake in code.  
Docs should probably be more detailed about env (like TF or keras version) in which it should be launched. Generally as a newcomer I didn't see any Keras install instructions on official website at all :frowning_face:

**Comment by fchollet** [comment]
You should install the nightly build: `sudo pip install tf-nightly --upgrade`

**Comment by SystemZ** [comment]
Awesome, now it works :)
Thanks!

**Comment by saida11000** [comment]
hello , i started to learn python, tensorflow and keras and i didn't understant the geneartion dataset code .
i need some help and comments to better understand the instructions [https://keras.io/examples/vision/image_classification_from_scratch/](url)

Generate a Dataset
image_size = (180, 180)
batch_size = 32

train_ds = tf.keras.preprocessing.image_dataset_from_directory(
    "PetImages",
    validation_split=0.2,
    subset="training",
    seed=1337,
    image_size=image_size,
    batch_size=batch_size,
)
val_ds = tf.keras.preprocessing.image_dataset_from_directory(
    "PetImages",
    validation_split=0.2,
    subset="validation",
    seed=1337,
    image_size=image_size,
    batch_size=batch_size,
)
