### ISSUE TITLE
examples/nlp/text_generation_fnet.py

### ISSUE THREAD

**Issue by FanYaning** [keras-team/keras-io#664]
@DarshanDeshpande 

https://github.com/keras-team/keras-io/blob/master/examples/nlp/text_generation_fnet.py#L135
"outputs = tf.pad(inputs, [[0, 1]])"  is here a mistake?

should it be "outputs = tf.pad(outputs , [[0, 1]])"?

**Comment by DarshanDeshpande** [comment]
Good catch! I must have overlooked it. I'll create a fix immediately.
