### ISSUE TITLE
reproducibility convlstm2D

### ISSUE THREAD

**Issue by shalkya** [keras-team/keras-io#667]
I tried to replicate what was displayed here : https://keras.io/examples/vision/conv_lstm/
https://github.com/keras-team/keras-io/blob/master/examples/vision/conv_lstm.py

I set up an environment following what was imported, for example i've these library versions:
tensorflow 2.4.1
numpy 1.20.3
keras 2.4.3

then I copy-pasted the code into a jupyter notebook, and run it (trained the neural network on CPU). As a result I got that:
![image](https://user-images.githubusercontent.com/11618427/137498669-91ed1f8e-ad58-4946-8d0f-16f8c0119de0.png)

when it was expected to obtain that:
![image](https://user-images.githubusercontent.com/11618427/137498713-d5d75027-476b-48ac-a25d-92b76cd4ae7b.png)

apart from the first image, all the other are blurry and this isn't showing what was expected.
Why did I get those ? Is it due to incompatible environment ? Or reproducibility is limited ?

**Comment by pcoet** [comment]
Hi folks, thanks for the question and discussion. For support issues, please use one of the resources below. The discussion will have better visibility that way.

* [TensorFlow forum](https://discuss.tensorflow.org/)
* [Keras mailing list](https://groups.google.com/forum/#!forum/keras-users)

Thanks!
