### ISSUE TITLE
image_classification_with_vision_transformer: AttributeError: module 'tensorflow.keras.layers' has no attribute 'Normalization'

### ISSUE THREAD

**Issue by StephanElter** [keras-team/keras-io#680]
Hello!
I get an Error if i run image_classification_with_vision_transformer.jpynb. the Normalization layer is unknown.
- AttributeError: module 'tensorflow.keras.layers' has no attribute 'Normalization'

I use 
-Windows 10 
- Anaconda
- Tensorflow 2.5 
- tensorflow-addons 0.13.0

i try to use layers.experimental.preprocessing.Normalization 
but then i get later an other error:
- NotImplementedError: Cannot convert a symbolic Tensor (data_augmentation/random_rotation/rotation_matrix/strided_slice:0) to a numpy array. This error may indicate that you're trying to pass a Tensor to a NumPy call, which is not supported

How i can solve this problem? Thanks

The requirements for this Example are: 'This example requires TensorFlow 2.4 or higher, as well as TensorFlow Addons, '

my conda version list is as follow:

# Name                    Version                   Build  Channel
_tflow_select             2.1.0                       gpu
abseil-cpp                20210324.2           h0e60522_0    conda-forge
absl-py                   0.13.0           py38haa95532_0
aiohttp                   3.7.4.post0      py38h2bbff1b_2
argon2-cffi               20.1.0           py38h2bbff1b_1
astor                     0.8.1            py38haa95532_0
astunparse                1.6.3                      py_0
async-timeout             3.0.1            py38haa95532_0
async_generator           1.10               pyhd3eb1b0_0
attrs                     21.2.0             pyhd3eb1b0_0
backcall                  0.2.0              pyhd3eb1b0_0
blas                      1.0                         mkl
bleach                    4.0.0              pyhd3eb1b0_0
blinker                   1.4              py38haa95532_0
brotli                    1.0.9                ha925a31_2
brotlipy                  0.7.0           py38h2bbff1b_1003
ca-certificates           2021.10.8            h5b45459_0    conda-forge
cached-property           1.5.2                hd8ed1ab_1    conda-forge
cached_property           1.5.2              pyha770c72_1    conda-forge
cachetools                4.2.2              pyhd3eb1b0_0
certifi                   2021.10.8        py38haa244fe_0    conda-forge
cffi                      1.14.6           py38h2bbff1b_0
chardet                   4.0.0           py38haa95532_1003
charset-normalizer        2.0.4              pyhd3eb1b0_0
click                     8.0.1              pyhd3eb1b0_0
colorama                  0.4.4              pyhd3eb1b0_0
coverage                  5.5              py38h2bbff1b_2
cryptography              3.4.8            py38h71e12ea_0
cudatoolkit               11.3.1               h280eb24_9    conda-forge
cudnn                     8.2.1.32             h754d62a_0    conda-forge
cycler                    0.10.0                   py38_0
cython                    0.29.24          py38hd77b12b_0
dataclasses               0.8                pyh6d0b6a4_7
debugpy                   1.4.1            py38hd77b12b_0
decorator                 5.1.0              pyhd3eb1b0_0
defusedxml                0.7.1              pyhd3eb1b0_0
dill                      0.3.4              pyhd3eb1b0_0
entrypoints               0.3                      py38_0
flatbuffers               2.0.0                h0e60522_0    conda-forge
fonttools                 4.25.0             pyhd3eb1b0_0
freetype                  2.10.4               hd328e21_0
future                    0.18.2                   py38_1
gast                      0.4.0              pyhd3eb1b0_0
giflib                    5.2.1                h8d14728_2    conda-forge
google-auth               1.33.0             pyhd3eb1b0_0
google-auth-oauthlib      0.4.4              pyhd3eb1b0_0
google-pasta              0.2.0              pyhd3eb1b0_0
googleapis-common-protos  1.53.0           py38h2eaa2aa_0
grpcio                    1.36.1           py38hc60d5dd_1
h5py                      3.4.0           nompi_py38hde0384b_101    conda-forge
hdf5                      1.12.1          nompi_h2a0e4a3_100    conda-forge
icc_rt                    2019.0.0             h0cc432a_1
icu                       68.1                 h0e60522_0    conda-forge
idna                      3.2                pyhd3eb1b0_0
importlib-metadata        4.8.1            py38haa95532_0
importlib_metadata        4.8.1                hd3eb1b0_0
intel-openmp              2021.3.0          haa95532_3372
ipykernel                 6.4.1            py38haa95532_1
ipython                   7.27.0           py38hd4e2768_0
ipython_genutils          0.2.0              pyhd3eb1b0_1
jedi                      0.18.0           py38haa95532_1
jinja2                    3.0.1              pyhd3eb1b0_0
jpeg                      9d                   h2bbff1b_0
jsonschema                3.2.0              pyhd3eb1b0_2
jupyter_client            7.0.1              pyhd3eb1b0_0
jupyter_core              4.8.1            py38haa95532_0
jupyterlab_pygments       0.1.2                      py_0
keras-applications        1.0.8                      py_1
keras-base                2.4.3              pyhd3eb1b0_0
keras-gpu                 2.4.3                hd3eb1b0_0
keras-preprocessing       1.1.2              pyhd3eb1b0_0
kiwisolver                1.3.1            py38hd77b12b_0
krb5                      1.19.2               hbae68bd_2    conda-forge
libclang                  11.1.0          default_h5c34c98_1    conda-forge
libcurl                   7.79.1               h789b8ee_1    conda-forge
libpng                    1.6.37               h2a8f88b_0
libprotobuf               3.14.0               h7755175_0    conda-forge
libssh2                   1.10.0               h680486a_2    conda-forge
libtiff                   4.2.0                hd0e1b90_0
libwebp                   1.2.0                h2bbff1b_0
lz4-c                     1.9.3                h2bbff1b_1
m2w64-gcc-libgfortran     5.3.0                         6
m2w64-gcc-libs            5.3.0                         7
m2w64-gcc-libs-core       5.3.0                         7
m2w64-gmp                 6.1.0                         2
m2w64-libwinpthread-git   5.0.0.4634.697f757               2
markdown                  3.3.4            py38haa95532_0
markupsafe                2.0.1            py38h2bbff1b_0
matplotlib                3.4.3            py38haa95532_0
matplotlib-base           3.4.3            py38h49ac443_0
matplotlib-inline         0.1.2              pyhd3eb1b0_2
mistune                   0.8.4           py38he774522_1000
mkl                       2021.3.0           haa95532_524
mkl-service               2.4.0            py38h2bbff1b_0
mkl_fft                   1.3.1            py38h277e83a_0
mkl_random                1.2.2            py38hf11a4ad_0
msys2-conda-epoch         20160418                      1
multidict                 5.1.0            py38h2bbff1b_2
munkres                   1.1.4                      py_0
nbclient                  0.5.3              pyhd3eb1b0_0
nbconvert                 6.1.0            py38haa95532_0
nbformat                  5.1.3              pyhd3eb1b0_0
nest-asyncio              1.5.1              pyhd3eb1b0_0
notebook                  6.4.3            py38haa95532_0
numpy                     1.21.2           py38hfca59bb_0
numpy-base                1.21.2           py38h0829f74_0
oauthlib                  3.1.1              pyhd3eb1b0_0
olefile                   0.46               pyhd3eb1b0_0
openssl                   1.1.1l               h8ffe710_0    conda-forge
opt_einsum                3.3.0              pyhd3eb1b0_1
packaging                 21.0               pyhd3eb1b0_0
pandocfilters             1.4.3            py38haa95532_1
parso                     0.8.2              pyhd3eb1b0_0
pickleshare               0.7.5           pyhd3eb1b0_1003
pillow                    8.4.0            py38hd45dc43_0
pip                       21.0.1           py38haa95532_0
prometheus_client         0.11.0             pyhd3eb1b0_0
promise                   2.3              py38haa95532_0
prompt-toolkit            3.0.20             pyhd3eb1b0_0
protobuf                  3.14.0           py38h885f38d_1    conda-forge
psutil                    5.8.0            py38h2bbff1b_1
pyasn1                    0.4.8              pyhd3eb1b0_0
pyasn1-modules            0.2.8                      py_0
pycparser                 2.20                       py_2
pygments                  2.10.0             pyhd3eb1b0_0
pyjwt                     2.1.0            py38haa95532_0
pyopenssl                 20.0.1             pyhd3eb1b0_1
pyparsing                 2.4.7              pyhd3eb1b0_0
pyqt                      5.12.3           py38haa244fe_7    conda-forge
pyqt-impl                 5.12.3           py38h885f38d_7    conda-forge
pyqt5-sip                 4.19.18          py38h885f38d_7    conda-forge
pyqtchart                 5.12             py38h885f38d_7    conda-forge
pyqtwebengine             5.12.1           py38h885f38d_7    conda-forge
pyreadline                2.1                      py38_1
pyrsistent                0.17.3           py38he774522_0
pysocks                   1.7.1            py38haa95532_0
python                    3.8.12               h6244533_0
python-dateutil           2.8.2              pyhd3eb1b0_0
python-flatbuffers        1.12               pyhd8ed1ab_1    conda-forge
python_abi                3.8                      1_cp38    esri
pywin32                   228              py38hbaba5e8_1
pywinpty                  0.5.7                    py38_0
pyyaml                    5.4.1            py38h2bbff1b_1
pyzmq                     22.2.1           py38hd77b12b_1
qt                        5.12.9               h5909a2a_4    conda-forge
requests                  2.26.0             pyhd3eb1b0_0
requests-oauthlib         1.3.0                      py_0
rsa                       4.7.2              pyhd3eb1b0_1
scipy                     1.7.1            py38hbe87c03_2
send2trash                1.8.0              pyhd3eb1b0_1
setuptools                58.0.4           py38haa95532_0
sip                       4.19.13          py38ha925a31_0
six                       1.16.0             pyhd3eb1b0_0
snappy                    1.1.8                ha925a31_3    conda-forge
sqlite                    3.36.0               h2bbff1b_0
tensorboard               2.5.0              pyhd8ed1ab_1    conda-forge
tensorboard-data-server   0.6.0            py38haa244fe_0    conda-forge
tensorboard-plugin-wit    1.6.0                      py_0
tensorflow                2.5.0           gpu_py38h8e8c102_0
tensorflow-addons         0.13.0                   py38_2    esri
tensorflow-base           2.5.0           gpu_py38hb3da07e_0
tensorflow-datasets       1.2.0                    py38_0
tensorflow-estimator      2.5.0              pyh81a9013_1    conda-forge
tensorflow-gpu            2.5.0                h17022bd_0
tensorflow-metadata       0.14.0             pyhe6710b0_1
termcolor                 1.1.0            py38haa95532_1
terminado                 0.9.4            py38haa95532_0
testpath                  0.5.0              pyhd3eb1b0_0
tk                        8.6.11               h2bbff1b_0
tornado                   6.1              py38h2bbff1b_0
tqdm                      4.62.2             pyhd3eb1b0_1
traitlets                 5.1.0              pyhd3eb1b0_0
typeguard                 2.12.1                     py_0    esri
typing-extensions         3.10.0.2             hd3eb1b0_0
typing_extensions         3.10.0.2           pyh06a4308_0
urllib3                   1.26.7             pyhd3eb1b0_0
vc                        14.2                 h21ff451_1
vs2015_runtime            14.27.29016          h5e58377_2
wcwidth                   0.2.5              pyhd3eb1b0_0
webencodings              0.5.1                    py38_1
werkzeug                  2.0.1              pyhd3eb1b0_0
wheel                     0.35.1             pyh9f0ad1d_0    conda-forge
win_inet_pton             1.1.0            py38haa95532_0
wincertstore              0.2              py38haa95532_2
winpty                    0.4.3                         4
wrapt                     1.12.1           py38he774522_1
xz                        5.2.5                h62dcd97_0
yaml                      0.2.5                he774522_0
yarl                      1.6.3            py38h2bbff1b_0
zipp                      3.6.0              pyhd3eb1b0_0
zlib                      1.2.11               h62dcd97_4
zstd                      1.4.9                h19a0ad4_0

**Comment by JanMarcelKezmann** [comment]
Hi @StephanElter ,

I guess the two easiest solutions are that you either update your TensorFlow version to 2.6.0 or newer or that you simply run the code in Google Colab while using the **tf.keras.layers.experimental.preprocessing.Normalization()** layer if your work with the TensorFlow version 2.5.0 or the **tf.keras.layers.Normalization()** layer as given in the example if you work with the latest version of TensorFlow which is default in Colab.

**Comment by StephanElter** [comment]
Hello Jan Marcel Kezmann,

regards for your advise!
As i wrote i try also
tf.keras.layers.experimental.preprocessing.Normalization() but i get  
an other error cant solve
"NotImplementedError: Cannot convert a symbolic Tensor  
(data_augmentation/random_rotation/rotation_matrix/strided_slice:0) to  
a numpy array. This error may indicate that you're trying to pass a  
Tensor to a NumPy call, which is not supported"
Do you know how i can solve this?


Can i ask you an other question??
I have a problem using AdamW optimizer with weight_decay and at the  
same time ReduceLROnPlateau. The training loss is rising again after a  
minim value.

I know what the problem is, but not how to solve this.
The problem ist that the weight_decay and lr have to decay in the same ratio.
So how can i reduce the weigth_decay (used in AdamW) coupled dependent  
on the learning rate from ReduceLROnPlateau ??

Thanks a lot!
Regards Stephan

Zitat von Jan Marcel Kezmann ***@***.***>:

**Comment by SuryanarayanaY** [comment]
Hi @StephanElter ,

The API `tf.keras.layers.Normalization` introduced in TF2.6v and since you have used TF2.5v the error appeared. Upgrading to versions >TF2.6v resolves this error. I have tested the tutorial with Tf2.12v and it's also working fine. Attached [gist](https://colab.sandbox.google.com/gist/SuryanarayanaY/e05a9cc00043feab2bc93eae2c78dd7f/kerasio_680-image_classification_with_vision_transformer.ipynb) for reference.

Please check and confirm whether we are good to close the issue now. If still have any queries please let us know.

Thanks!
