### ISSUE TITLE
CycleGan save error

### ISSUE THREAD

**Issue by antoine-l** [keras-team/keras-io#691]
Hi,

I'm running the Colab of CycleGan as is ([https://colab.research.google.com/github/keras-team/keras-io/blob/master/examples/generative/ipynb/cyclegan.ipynb](https://colab.research.google.com/github/keras-team/keras-io/blob/master/examples/generative/ipynb/cyclegan.ipynb)) and have the following error:

> ValueError                                Traceback (most recent call last)
> <ipython-input-13-1726c533b6c0> in <module>()
>      42     tf.data.Dataset.zip((train_horses, train_zebras)),
>      43     epochs=1,
> ---> 44     callbacks=[plotter, model_checkpoint_callback],
>      45 )
> 
> 7 frames
> /usr/local/lib/python3.7/dist-packages/keras/saving/saving_utils.py in raise_model_input_error(model)
>      86       'set. Usually, input shapes are automatically determined from calling'
>      87       ' `.fit()` or `.predict()`. To manually set the shapes, call '
> ---> 88       '`model.build(input_shape)`.'.format(model))
>      89 
>      90 
> 
> ValueError: Model <__main__.CycleGan object at 0x7f1515ca2b50> cannot be saved because the input shapes have not been set. Usually, input shapes are automatically determined from calling `.fit()` or `.predict()`. To manually set the shapes, call `model.build(input_shape)`.
> 

I tried different fixes but they just gave me different errors:
```
  cycle_gan_model.compute_output_shape(input_shape=(None, 256, 256, 3))
  cycle_gan_model.build((None, 256, 256, 3))
```

What can I do to fix it?

Thank you!

**Comment by ossan-tamago** [comment]
I solved the problem by adding a call method to the CycleGan class.

```python
    def call(self, inputs, training=None, mask=None):
        return self.disc_X(inputs), self.disc_Y(inputs), self.gen_G(inputs), self.gen_F(inputs)
```

Then specify the input size like this.

```python
  cycle_gan_model.compute_output_shape(input_shape=(None, 256, 256, 3))
```
