### ISSUE TITLE
about keras-io/examples/nlp/semantic_similarity_with_bert.py

### ISSUE THREAD

**Issue by batermj** [keras-team/keras-io#695]
Environments:
    Python 3.7.0 
    tensorflow                    2.6.0 
    torch                         1.9.1 
    keras                         2.7.0 
    

Traceback (most recent call last):   
    File "semantic_similarity_with_bert.py", line 250, in <module>
         )(sequence_output) 

TypeError: Inputs to a layer should be tensors. Got: last_hidden_state

**Comment by mirzayaser3** [comment]
I am getting Value error can you help?
