### ISSUE TITLE
[RETINANET]: Custom anchor box sizes

### ISSUE THREAD

**Issue by gabrielpeixoto-cvai** [keras-team/keras-io#704]
Hello, first of all thanks for the example.

I was wondering how could I modify the AnchorBox class to consider smaller regions?

I was able to make it run for my dataset and it works fine. However, I have an issue with confidence, it is very low (around 0.1). One of the reasons is that my objects are very small and my image is very big, so the ratio is very small. I am using images in the order of 3000x2000 pixels and my objects are approx 100x100. Event training the network at 1024x1024 has the same result.

I wonder if I modify the *get_anchors* method to consider smaller anchors it is enough.
```
    def get_anchors(self, image_height, image_width):
        """Generates anchor boxes for all the feature maps of the feature pyramid.

        Arguments:
          image_height: Height of the input image.
          image_width: Width of the input image.

        Returns:
          anchor boxes for all the feature maps, stacked as a single tensor
            with shape `(total_anchors, 4)`
        """
        anchors = [
            self._get_anchors(
                tf.math.ceil(image_height / 2 ** i),
                tf.math.ceil(image_width / 2 ** i),
                i,
            )
            for i in range(3, 8)
        ]
        print(f"image_height: {image_height}, image_width: {image_width}, Anchors {anchors}")
        #sys.exit()
        return tf.concat(anchors, axis=0)
```

**Comment by pcoet** [comment]
Hi @gabrielpeixoto-cvai, thanks for reaching out. For support questions like this, please use one of the resources below. Your question will have better visibility that way.

* [TensorFlow forum](https://discuss.tensorflow.org/)
* [Keras mailing list](https://groups.google.com/forum/#!forum/keras-users)

Thanks!
