### ISSUE TITLE
keras-io/examples/vision/ipynb/semisupervised_simclr.ipynb Invalid notebook

### ISSUE THREAD

**Issue by romanoss** [keras-team/keras-io#706]
The Notebook Does Not Appear to Be Valid JSON

**Comment by beresandras** [comment]
The notebook has been fixed and it is now valid. Check it out!

**Comment by SuryanarayanaY** [comment]
Hi @romanoss ,

The issue has been fixed and notebook also made available on https://keras.io/examples/vision/semisupervised_simclr/

Could we mark it resolved now? Thanks!
