### ISSUE TITLE
Model Architecture

### ISSUE THREAD

**Issue by navydhara79-zz** [keras-team/keras-io#713]
Where can I find the model architecture of this image captioning model. ?

**Comment by SuryanarayanaY** [comment]
Hi @navydhara79-zz ,

For checking the model architecture details one can use `model.summary()` and `tf.keras.utils.plot_model()`. It will give the information about each layers with input and output sizes and which layer they are connected to etc.

For example I have taken Retinanet model and using the above mentioned APIs to check the architecture details and it was plotted. You can refer to attached [gist](https://colab.sandbox.google.com/gist/SuryanarayanaY/4f5fef8a93cf653ce4530491a71ec9ea/kerasio_713.ipynb).

Thanks!
