### ISSUE TITLE
Can not save model weights when using code in example “Message-passing neural network for molecular property prediction”

### ISSUE THREAD

**Issue by huzongxiang** [keras-team/keras-io#720]
history = mpnn.fit(

  File "C:\Users\xxx\anaconda3\envs\Tensorflow\lib\site-packages\keras\engine\training.py", line 1230, in fit
    callbacks.on_epoch_end(epoch, epoch_logs)

  File "C:\Users\xxx\anaconda3\envs\Tensorflow\lib\site-packages\keras\callbacks.py", line 413, in on_epoch_end
    callback.on_epoch_end(epoch, logs)

  File "C:\Users\xxx\anaconda3\envs\Tensorflow\lib\site-packages\keras\callbacks.py", line 1368, in on_epoch_end
    self._save_model(epoch=epoch, batch=None, logs=logs)

  File "C:\Users\xxx\anaconda3\envs\Tensorflow\lib\site-packages\keras\callbacks.py", line 1431, in _save_model
    self.model.save_weights(

  File "C:\Users\xxx\anaconda3\envs\Tensorflow\lib\site-packages\keras\engine\training.py", line 2252, in save_weights
    hdf5_format.save_weights_to_hdf5_group(f, self.layers)

  File "C:\Users\xxx\anaconda3\envs\Tensorflow\lib\site-packages\keras\saving\hdf5_format.py", line 641, in save_weights_to_hdf5_group
    param_dset = g.create_dataset(name, val.shape, dtype=val.dtype)

  File "C:\Users\xxx\anaconda3\envs\Tensorflow\lib\site-packages\h5py\_hl\group.py", line 148, in create_dataset
    dsid = dataset.make_new_dset(group, shape, dtype, data, name, **kwds)

  File "C:\Users\xxx\anaconda3\envs\Tensorflow\lib\site-packages\h5py\_hl\dataset.py", line 137, in make_new_dset
    dset_id = h5d.create(parent.id, name, tid, sid, dcpl=dcpl)

  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper

  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper

  File "h5py\h5d.pyx", line 87, in h5py.h5d.create

ValueError: Unable to create dataset (name already exists)

I want to use ModelCheckPoint to save model weghts only in callbacks,  I try many platforms running this code but get these error.
author and contributors
@akensert @fchollet @tanvir-ux

**Comment by huzongxiang** [comment]
I solve this problem by changing my tensorflow version from 2.6.0 to 2.2.0 and numpy version from 1.21 to 1.19

**Comment by akensert** [comment]
Hi @huzongxiang. Good to see you solved it. For why it doesn't work with e.g. TF2.6: I don't know. Based on some quick experimentation, it seems to be related to the MessagePassing layer (when simply replacing it with a Dense layer, there's no error).

**Comment by huzongxiang** [comment]
> Hi @huzongxiang. Good to see you solved it. For why it doesn't work with e.g. TF2.6: I don't know; seems to be some bug with h5py. Based on some quick experimentation, it seems to be related to the MessagePassing layer (when simply replacing it with a Dense layer, there's no error).
> 
> EDIT: [Here's a Google Colab](https://colab.research.google.com/drive/1wKeDpew369Hwfq8ykL5x9fDP5D-gN53B?usp=sharing) that illustrates this.

@akensert Thank you for your reply! I wrote a code referenced to your codes, but I can not save weights so I tried to change the version of my tensorflow to 2.2.0 but the running results reported an error, then I changed my numpy to 1.19, finally, the error disappeared.  The code can keep running without error.
I think I have solved this problem but a bad thing I find that tensorflow 2.2.0 can not get the same result as 2.6.0 do! 
The same code with the same parameters can be trained easily under tensorflow 2.6.0 but it can not be trained under tensorflow 2.2.0!

**Comment by akensert** [comment]
> The same code with the same parameters can be trained easily under tensorflow 2.6.0 but it can not be trained under tensorflow 2.2.0!

@huzongxiang Hmm interesting.. Could you perhaps elaborate on "can not be trained"? Does the model perform much worse (e.g., it converges in some very bad local minimum), or just slightly worse (a few percentage points worse than before)? You could try to adjust the random seeds (first code cell).

**Comment by huzongxiang** [comment]
> 

I test my code under tensorflow 2.2.0, it does not work, the loss keeps decreasing but the AUC remains almost unchanged over 20 epochs. I use a tf.zeros func in a custom layer, this func produces an numpy data error  (warning not a tensor) and dumps the code under other versions of tensorflow with numpy 1.21 except tensorflow 2.6.0. I change numpy to 1.19 then the code can run but it does not work.

**Comment by huzongxiang** [comment]
I test my code under tensorflow 2.2.0, it does not work, the loss keeps decreasing but the AUC remains almost unchanged over 30 epochs. I use a tf.zeros func in a custom layer, this func produces an numpy data error (warning not a tensor) and dumps the code under other versions of tensorflow with numpy 1.21 except tensorflow 2.6.0. I change numpy to 1.19 then the code can run but it does not work.

**Comment by akensert** [comment]
@fchollet Do you have any idea why the [MessagePassing](https://keras.io/examples/graph/mpnn-molecular-graphs/#message-passing) layer causes an error (see above) with model.save_weights(...)?

**Comment by huzongxiang** [comment]
> @huzongxiang (@fchollet) I figured out the problem regarding the error with `model.save_weights(...)`: What you need to do is explicitly pass a name to `self.add_weight()` (otherwise the weights will have the same name).
> 
> So what you need to do is replace this:
> 
> ```python
> self.kernel = self.add_weight(
>       shape=(self.bond_dim, self.atom_dim * self.atom_dim),
>       trainable=True,
>       initializer="glorot_uniform",
> )
> self.bias = self.add_weight(
>       shape=(self.atom_dim * self.atom_dim), trainable=True, initializer="zeros", 
> )
> ```
> 
> With [for example] this:
> 
> ```python
> self.kernel = self.add_weight(
>       shape=(self.bond_dim, self.atom_dim * self.atom_dim),
>       trainable=True,
>       initializer="glorot_uniform",
>       name='kernel_edge_network'
> )
> self.bias = self.add_weight(
>       shape=(self.atom_dim * self.atom_dim), trainable=True, initializer="zeros", 
>       name='bias_edge_network' 
> )
> ```

thank you very much. I'll give it a try.

**Comment by huzongxiang** [comment]
> @huzongxiang (@fchollet) I figured out the problem regarding the error with `model.save_weights(...)`: What you need to do is explicitly pass a name to `self.add_weight()` (otherwise the weights will have the same name).
> 
> So what you need to do is replace this:
> 
> ```python
> self.kernel = self.add_weight(
>       shape=(self.bond_dim, self.atom_dim * self.atom_dim),
>       trainable=True,
>       initializer="glorot_uniform",
> )
> self.bias = self.add_weight(
>       shape=(self.atom_dim * self.atom_dim), trainable=True, initializer="zeros", 
> )
> ```
> 
> With [for example] this:
> 
> ```python
> self.kernel = self.add_weight(
>       shape=(self.bond_dim, self.atom_dim * self.atom_dim),
>       trainable=True,
>       initializer="glorot_uniform",
>       name='kernel_edge_network'
> )
> self.bias = self.add_weight(
>       shape=(self.atom_dim * self.atom_dim), trainable=True, initializer="zeros", 
>       name='bias_edge_network' 
> )
> ```

@akensert Excellent!  It solves my problem, I hope this change will be applied to the official example!

**Comment by SuryanarayanaY** [comment]
Hi @huzongxiang ,

The tutorial is tested with latest version and I tried to save and reload the model in all 3 formats "keras", "tf", and "h5" and all are working fine. I have attached [gist](https://colab.sandbox.google.com/gist/SuryanarayanaY/1eebed27798c7f14f11c8ab537ac1859/kerasio_720-mpnn-molecular-graphs.ipynb) for reference.

Please cross check and confirm whether this issue can be marked as resolved now. Thanks
