### ISSUE TITLE
Dataset for supervised baseline

### ISSUE THREAD

**Issue by aynesss** [keras-team/keras-io#723]
I would to know, for supervised baseline , we must use only labeled subset(like finetune) or all dataset (labeled+unlabeled).

**Comment by SuryanarayanaY** [comment]
Hi @SuryanarayanaY ,

For Supervised base line model we will use labelled dataset which can create a simple model. For semi supervised learning we can use partially labelled dataset (labeled+unlabeled). You may refer one example tutorial for semi supervised learning [here](https://keras.io/examples/vision/semisupervised_simclr/) for more details.

Please confirm if you are still looking for any more details.

Thanks!
