### ISSUE TITLE
Question in Character-level recurrent sequence-to-sequence model

### ISSUE THREAD

**Issue by moo611** [keras-team/keras-io#725]
Hi, I has some confusions in your "**decode_sequence**" function. It seems like you just choose **1 character** which was generated last time as the next time decoder input. My questions are below:
(1) Why you choose 1 character (for example: d) instead of choosing all the  characters generated in the past(for example: abcd) as the next time decoder input? 
(2) In this code "sampled_token_index = np.argmax(output_tokens[0, -1, :])" , -1 means that you choose the **last character's vector** to predict. Why is the last character? Can I use the first character or the second character's vector ... to predict?

I hope your answer, thank you :)

**Comment by pcoet** [comment]
Hi @moo611, thanks for reaching out. Can you repost this to one of the forums below? That way your question will have more visibility.

* [TensorFlow forum](https://discuss.tensorflow.org/)
* [Keras mailing list](https://groups.google.com/forum/#!forum/keras-users)

Thanks!
