### ISSUE TITLE
Error in GraphConvLayer class

### ISSUE THREAD

**Issue by wmgithub** [keras-team/keras-io#726]
According to the description of the `GraphConvLayer` class (Line 382-384 as upon 11/29/2021, keras-io/examples/graph/gnn_citations.py):

> If `combination_type` is `gru`, the `node_repesentations` and `aggregated_messages` are stacked to create a sequence,
then processed by a GRU layer. Otherwise, the `node_repesentations` and `aggregated_messages` are added
or concatenated, then processed using a FFN. 

However, in Line 414, the corresponding `combination_type` is `gated` rather than `gru`. It's very likely to be a performance-critical typo. Please help take a look. Thanks.

**Comment by SuryanarayanaY** [comment]
Hi @wmgithub ,

We are in the process of clearing backlog issues. I have gone through this issue and as per my understanding there is no problem now though i am not sure how the code was earlier.

Now I can see that default combination_type="concat" as mentioned in below code.
https://github.com/keras-team/keras-io/blob/8f49b3ec63c7d959b9457ab7cc961ce4ca922d2f/examples/graph/gnn_citations.py#L406

If combination_type == "gated" then it calls GRN layers which is matching the description mentioned in Line 386-387. For all other cases FFN will be used.
https://github.com/keras-team/keras-io/blob/8f49b3ec63c7d959b9457ab7cc961ce4ca922d2f/examples/graph/gnn_citations.py#L418-L428

Please check and confirm if it resolved or missing something.

Thanks!
