### ISSUE TITLE
ValueError: squeeze_dims[0] not in [-1,1). for '{{node text_vectorization/Squeeze}} = Squeeze[T=DT_STRING, squeeze_dims=[1]](text_vectorization/StaticRegexReplace)' with input shapes: [5].

### ISSUE THREAD

**Issue by Kiraris** [keras-team/keras-io#727]
when I run the code,I got an error,please help me!
**here is the code that I run:**
def custom_standardization(input_string):
    lowercase = tf.strings.lower(input_string)
    return tf.strings.regex_replace(lowercase, "[%s]" % re.escape(strip_chars), "")

strip_chars = "!\"#$%&'()*+,-./:;<=>?@[\]^_`{|}~"
strip_chars = strip_chars.replace("<", "")
strip_chars = strip_chars.replace(">", "")

text_data=np.array(text_data)
vectorization = TextVectorization(
    max_tokens=VOCAB_SIZE,
    output_mode="int",
    output_sequence_length=SEQ_LENGTH,
    standardize=custom_standardization,
)
vectorization.adapt(text_data)

#显示分词后的字典中的前100个
print(len(vectorization.get_vocabulary()))
print(vectorization.get_vocabulary()[0:100])

'''
temp=np.array(captions_mapping.values())
print(vectorization(temp))
'''

# Data augmentation for image data
image_augmentation = keras.Sequential(
    [
        RandomFlip("horizontal"),
        RandomRotation(0.2),
        RandomContrast(0.3),
    ]
)
def decode_and_resize(img_path):
    img = tf.io.read_file(img_path)
    img = tf.image.decode_jpeg(img, channels=3)
    img = tf.image.resize(img, IMAGE_SIZE)
    img = tf.image.convert_image_dtype(img, tf.float32)
    return img

def process_input(img_path, captions):
    return decode_and_resize(img_path), vectorization(captions)

def make_dataset(images, captions):
    dataset = tf.data.Dataset.from_tensor_slices((images, captions))
    dataset = dataset.shuffle(len(images))
    dataset = dataset.map(process_input, num_parallel_calls=AUTOTUNE)
    dataset = dataset.batch(BATCH_SIZE).prefetch(AUTOTUNE)
    return dataset

# Pass the list of images and the list of corresponding captions
train_dataset = make_dataset(list(train_data.keys()), list(train_data.values()))

valid_dataset = make_dataset(list(valid_data.keys()), list(valid_data.values()))

**here is the traceback :**
ValueError                                Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_16400/1365239275.py in <module>
     20 
     21 # Pass the list of images and the list of corresponding captions
---> 22 train_dataset = make_dataset(list(train_data.keys()), list(train_data.values()))
     23 
     24 valid_dataset = make_dataset(list(valid_data.keys()), list(valid_data.values()))

~\AppData\Local\Temp/ipykernel_16400/1365239275.py in make_dataset(images, captions)
     14     dataset = tf.data.Dataset.from_tensor_slices((images, captions))
     15     dataset = dataset.shuffle(len(images))
---> 16     dataset = dataset.map(process_input, num_parallel_calls=AUTOTUNE)
     17     dataset = dataset.batch(BATCH_SIZE).prefetch(AUTOTUNE)
     18     return dataset

D:\Program Files (x86)\python\envs\tensorflow-cpu\lib\site-packages\tensorflow\python\data\ops\dataset_ops.py in map(self, map_func, num_parallel_calls, deterministic)
   1621       return MapDataset(self, map_func, preserve_cardinality=True)
   1622     else:
-> 1623       return ParallelMapDataset(
   1624           self,
   1625           map_func,

D:\Program Files (x86)\python\envs\tensorflow-cpu\lib\site-packages\tensorflow\python\data\ops\dataset_ops.py in __init__(self, input_dataset, map_func, num_parallel_calls, deterministic, use_inter_op_parallelism, preserve_cardinality, use_legacy_function)
   4014     self._input_dataset = input_dataset
   4015     self._use_inter_op_parallelism = use_inter_op_parallelism
-> 4016     self._map_func = StructuredFunctionWrapper(
   4017         map_func,
   4018         self._transformation_name(),

D:\Program Files (x86)\python\envs\tensorflow-cpu\lib\site-packages\tensorflow\python\data\ops\dataset_ops.py in __init__(self, func, transformation_name, dataset, input_classes, input_shapes, input_types, input_structure, add_to_graph, use_legacy_function, defun_kwargs)
   3219       with tracking.resource_tracker_scope(resource_tracker):
   3220         # TODO(b/141462134): Switch to using garbage collection.
-> 3221         self._function = wrapper_fn.get_concrete_function()
   3222 
   3223         if add_to_graph:

D:\Program Files (x86)\python\envs\tensorflow-cpu\lib\site-packages\tensorflow\python\eager\function.py in get_concrete_function(self, *args, **kwargs)
   2529       **kwargs: inputs to specialize on.
   2530     """
-> 2531     graph_function = self._get_concrete_function_garbage_collected(
   2532         *args, **kwargs)
   2533     graph_function._garbage_collector.release()  # pylint: disable=protected-access

D:\Program Files (x86)\python\envs\tensorflow-cpu\lib\site-packages\tensorflow\python\eager\function.py in _get_concrete_function_garbage_collected(self, *args, **kwargs)
   2494       args, kwargs = None, None
   2495     with self._lock:
-> 2496       graph_function, args, kwargs = self._maybe_define_function(args, kwargs)
   2497       if self.input_signature:
   2498         args = self.input_signature

D:\Program Files (x86)\python\envs\tensorflow-cpu\lib\site-packages\tensorflow\python\eager\function.py in _maybe_define_function(self, args, kwargs)
   2775 
   2776       self._function_cache.missed.add(call_context_key)
-> 2777       graph_function = self._create_graph_function(args, kwargs)
   2778       self._function_cache.primary[cache_key] = graph_function
   2779       return graph_function, args, kwargs

D:\Program Files (x86)\python\envs\tensorflow-cpu\lib\site-packages\tensorflow\python\eager\function.py in _create_graph_function(self, args, kwargs, override_flat_arg_shapes)
   2655     arg_names = base_arg_names + missing_arg_names
   2656     graph_function = ConcreteFunction(
-> 2657         func_graph_module.func_graph_from_py_func(
   2658             self._name,
   2659             self._python_function,

D:\Program Files (x86)\python\envs\tensorflow-cpu\lib\site-packages\tensorflow\python\framework\func_graph.py in func_graph_from_py_func(name, python_func, args, kwargs, signature, func_graph, autograph, autograph_options, add_control_dependencies, arg_names, op_return_value, collections, capture_by_value, override_flat_arg_shapes)
    979         _, original_func = tf_decorator.unwrap(python_func)
    980 
--> 981       func_outputs = python_func(*func_args, **func_kwargs)
    982 
    983       # invariant: `func_outputs` contains only Tensors, CompositeTensors,

D:\Program Files (x86)\python\envs\tensorflow-cpu\lib\site-packages\tensorflow\python\data\ops\dataset_ops.py in wrapper_fn(*args)
   3212           attributes=defun_kwargs)
   3213       def wrapper_fn(*args):  # pylint: disable=missing-docstring
-> 3214         ret = _wrapper_helper(*args)
   3215         ret = structure.to_tensor_list(self._output_structure, ret)
   3216         return [ops.convert_to_tensor(t) for t in ret]

D:\Program Files (x86)\python\envs\tensorflow-cpu\lib\site-packages\tensorflow\python\data\ops\dataset_ops.py in _wrapper_helper(*args)
   3154         nested_args = (nested_args,)
   3155 
-> 3156       ret = autograph.tf_convert(func, ag_ctx)(*nested_args)
   3157       # If `func` returns a list of tensors, `nest.flatten()` and
   3158       # `ops.convert_to_tensor()` would conspire to attempt to stack

D:\Program Files (x86)\python\envs\tensorflow-cpu\lib\site-packages\tensorflow\python\autograph\impl\api.py in wrapper(*args, **kwargs)
    263       except Exception as e:  # pylint:disable=broad-except
    264         if hasattr(e, 'ag_error_metadata'):
--> 265           raise e.ag_error_metadata.to_exception(e)
    266         else:
    267           raise

ValueError: in user code:

    C:\Users\zq\AppData\Local\Temp/ipykernel_16400/1365239275.py:10 process_input  *
        return decode_and_resize(img_path), vectorization(captions)
    D:\Program Files (x86)\python\envs\tensorflow-cpu\lib\site-packages\tensorflow\python\keras\engine\base_layer.py:927 __call__  **
        outputs = call_fn(cast_inputs, *args, **kwargs)
    D:\Program Files (x86)\python\envs\tensorflow-cpu\lib\site-packages\tensorflow\python\keras\layers\preprocessing\text_vectorization.py:596 call
        inputs = self._preprocess(inputs)
    D:\Program Files (x86)\python\envs\tensorflow-cpu\lib\site-packages\tensorflow\python\keras\layers\preprocessing\text_vectorization.py:572 _preprocess
        inputs = array_ops.squeeze(inputs, axis=1)
    D:\Program Files (x86)\python\envs\tensorflow-cpu\lib\site-packages\tensorflow\python\util\dispatch.py:180 wrapper
        return target(*args, **kwargs)
    D:\Program Files (x86)\python\envs\tensorflow-cpu\lib\site-packages\tensorflow\python\util\deprecation.py:507 new_func
        return func(*args, **kwargs)
    D:\Program Files (x86)\python\envs\tensorflow-cpu\lib\site-packages\tensorflow\python\ops\array_ops.py:4145 squeeze
        return gen_array_ops.squeeze(input, axis, name)
    D:\Program Files (x86)\python\envs\tensorflow-cpu\lib\site-packages\tensorflow\python\ops\gen_array_ops.py:9874 squeeze
        _, _, _op, _outputs = _op_def_library._apply_op_helper(
    D:\Program Files (x86)\python\envs\tensorflow-cpu\lib\site-packages\tensorflow\python\framework\op_def_library.py:742 _apply_op_helper
        op = g._create_op_internal(op_type_name, inputs, dtypes=None,
    D:\Program Files (x86)\python\envs\tensorflow-cpu\lib\site-packages\tensorflow\python\framework\func_graph.py:593 _create_op_internal
        return super(FuncGraph, self)._create_op_internal(  # pylint: disable=protected-access
    D:\Program Files (x86)\python\envs\tensorflow-cpu\lib\site-packages\tensorflow\python\framework\ops.py:3319 _create_op_internal
        ret = Operation(
    D:\Program Files (x86)\python\envs\tensorflow-cpu\lib\site-packages\tensorflow\python\framework\ops.py:1816 __init__
        self._c_op = _create_c_op(self._graph, node_def, inputs,
    D:\Program Files (x86)\python\envs\tensorflow-cpu\lib\site-packages\tensorflow\python\framework\ops.py:1657 _create_c_op
        raise ValueError(str(e))

    ValueError: squeeze_dims[0] not in [-1,1). for '{{node text_vectorization/Squeeze}} = Squeeze[T=DT_STRING, squeeze_dims=[1]](text_vectorization/StaticRegexReplace)' with input shapes: [5].

**Comment by pcoet** [comment]
Hi @Kiraris, thanks for reaching out. Can you repost this at one of the forums below? That way your question will have more visibility.

* [TensorFlow forum](https://discuss.tensorflow.org/)
* [Keras mailing list](https://groups.google.com/forum/#!forum/keras-users)

Thanks!
