### ISSUE TITLE
Example hosted mistakenly twice

### ISSUE THREAD

**Issue by MohamadJaber1** [keras-team/keras-io#728]
This example is being hosted twice:
https://keras.io/examples/timeseries/timeseries_classification_transformer/ (**Last modified: 2021/08/05**)
https://keras.io/examples/timeseries/timeseries_transformer_classification/ (**Last modified: 2021/06/25**)

And its appearing as:
![transformer](https://user-images.githubusercontent.com/48984186/144042990-e273bce6-4f08-4245-b95f-ba148a22e802.PNG)

**Comment by sachinprasadhs** [comment]
Hi, 

Now the duplicate entry is not visible, it shows only single entry, please verify and close the issue.

![image](https://github.com/keras-team/keras-io/assets/73069040/0dcfcdbd-309e-43e2-908c-f00f8ed0d8c6)
