### ISSUE TITLE
Save Model Pointnet

### ISSUE THREAD

**Issue by Alfajesto** [keras-team/keras-io#733]
Hello all,
I have configured a model that is very similar to the Pointnet (https://github.com/keras-team/keras-io/blob/master/examples/vision/pointnet.py). However, saving the trained model keeps failing. Are there any solutions in this regard?

**Comment by Alfajesto** [comment]
trying to save the model I get the following error:

NotImplementedError: <__main__.OrthogonalRegularizer object at 0x00000183848965E0> does not implement get_config()

**Comment by pcoet** [comment]
Hi @Alfajesto, thanks for reaching out. Can you repost this at one of the forums below? That way your question will have more visibility.

* [TensorFlow forum](https://discuss.tensorflow.org/)
* [Keras mailing list](https://groups.google.com/forum/#!forum/keras-users)

Thanks!
