### ISSUE TITLE
Data-efficient GANs with Adaptive Discriminator Augmentation

### ISSUE THREAD

**Issue by ahtishamkhan404** [keras-team/keras-io#745]
Hi, I need help with this code How do I add my own dataset to this code. I am a beginner in Deep learning
 I try so many time but failed please help.

**Comment by sachinprasadhs** [comment]
Hi, 

Thanks for reporting the issue.

You need to replace the dataset name here `dataset_name = "caltech_birds2011"`  which will be loaded in the function using` tfds.load`
```
def prepare_dataset(split):
    # the validation dataset is shuffled as well, because data order matters
    # for the KID calculation
    return (
        tfds.load(dataset_name, split=split, shuffle_files=True)
        .map(preprocess_image, num_parallel_calls=tf.data.AUTOTUNE)
        .cache()
        .shuffle(10 * batch_size)
        .batch(batch_size, drop_remainder=True)
        .prefetch(buffer_size=tf.data.AUTOTUNE)
```

To list all the available datasets in tfds and more details, refer https://www.tensorflow.org/datasets/overview#load_a_dataset
