### ISSUE TITLE
zsh: illegal hardware instruction and module "tensorflow not found"

### ISSUE THREAD

**Issue by Dinesh-Mali** [keras-team/keras-io#748]
I have created environment via "conda create workspace"

There I installed all necessary packages via conda, where tensorflow2.0.0 installed.

while importing

from Tensorflow.keras.layers import TextVectorization giving me import error that can not import TextVectorization and I'm getting the following error:
AttributeError: module 'tensorflow.keras.preprocessing' has no attribute 'image_dataset_from_directory'

when trying to solve: https://github.com/keras-team/keras-io/blob/master/examples/vision/image_classification_from_scratch.py

my TensorFlow version: 2.0.0
python version: 3.7.12

I am using Mac.

I tried pip3 install tf-nightly: got error zsh: illegal hardware instruction and module "tensorflow not found".

please help.

**Comment by SuryanarayanaY** [comment]
Hi @Dinesh-Mali ,

The reported error on Mac with silicon chip is expected as tensorflow not directly installable at that time. You need to install `tensorflow-macos` along with metal plugin using command `python -m pip install tensorflow-metal` using the metal plugin instructions mentioned [here](https://developer.apple.com/metal/tensorflow-plugin/).

However from TF2.13, `pip install tensorflow` automatically installs `tensorflow-macos`

The tutorial tested and working properly now. Could you please check the attached [gist](https://colab.sandbox.google.com/gist/SuryanarayanaY/979dca2a77ac0a7bc2d8197fc4ee7fbe/keras_660-image_classification_from_scratch.ipynb) and confirm whether it is resolved.

Thanks!
