### ISSUE TITLE
Doubt in the RetinaNet example

### ISSUE THREAD

**Issue by sayakpaul** [keras-team/keras-io#749]
@srihari-humbarwadi was wondering if you could explain the values under `padding_values`:

```
train_dataset = train_dataset.padded_batch(
    batch_size=batch_size, padding_values=(0.0, 1e-8, -1), drop_remainder=True
)
```

**Comment by srihari-humbarwadi** [comment]
We pad 
 - images with 0's
 - boxes with a small float number
 - class ids with -1, which is ignored id

**Comment by sayakpaul** [comment]
Thank you!
