### ISSUE TITLE
Dense computation before convolutional and recurrent layers

### ISSUE THREAD

**Issue by TheSleepingDragon** [keras-team/keras-io#753]
I am having difficulty implementing a dense layer before convolution or recurrent layers in Keras, simply because the dimensions of the output of the Dense layer (axiomatically) does not match the input of the next convolutional or recurrent layers, which accept inputs of higher dimensions. I wish to know whether there is a way to code this structure using Keras. For instance, can we determine (in some ways) how the output of a Dense layer should be to solve this issue?  

Just to give you an overview of what I am thinking of:

```
RNN = Sequential()
RNN.add(Dense(256, activation="LeakyReLU"))
RNN.add(SimpleRNN(units=256, return_sequences=False))
RNN.add(Dense(1, activation="LeakyReLU"))
RNN.compile(loss ="mse", optimizer = 'nadam', metrics=["logcosh"])
```
Of course, this architecture returns an error during `RNN.fit`. Any suggestion would be highly appreciated. Thank you.

**Comment by pcoet** [comment]
Hi @TheSleepingDragon, thanks for reaching out. Can you repost this on one of the forums below? That way your question will have more visibility.

* [TensorFlow forum](https://discuss.tensorflow.org/)
* [Keras mailing list](https://groups.google.com/forum/#!forum/keras-users)

Thanks,

David
