### ISSUE TITLE
How run the model for prediction for a single molecule and also preprocess that molecule in “Message-passing neural network for molecular property prediction”

### ISSUE THREAD

**Issue by mephisto121** [keras-team/keras-io#757]
Hi. I used the mpnn for multi classification and regression model but the problem that I have is when I want to give only one smiles to graph to smiles function and after that for MPNNdataset I get different errors. I cannot run the model with 1 smiles and no y for the outcome.
Is there any way that this can happen?
Thank you.

**Comment by pramodkp** [comment]
Hi ,

Just want to know how did you use for regression model i.e. where n the code you made changes ?

Thanks

**Comment by pcoet** [comment]
Hi @mephisto121 , thanks for reaching out. The issue backlog is not the best place for support requests. Can you repost this to one of the forums below? That way your question will have more visibility.

* [TensorFlow forum](https://discuss.tensorflow.org/)
* [Keras mailing list](https://groups.google.com/forum/#!forum/keras-users).

Thanks!
