### ISSUE TITLE
Have a question for "video_transformers.py" example

### ISSUE THREAD

**Issue by cslee99** [keras-team/keras-io#758]
I separated the train code and test code.
I wanted to use it by saving the model structure and model weight in the train code and loading it in the test code.
However, the following error occurred in the model_from_json( ) code that loads the model.

ValueError: Unknown layer: PositionalEmbedding. Please ensure this object is passed to the `custom_objects` argument.

So I added custom_objects.

loaded_model = model_from_json(loaded_model_json, custom_objects={'PositionalEmbedding':common.PositionalEmbedding})

However, the following error occurs:

TypeError: ('Keyword argument not understood:', 'position_embeddings')

By any chance, if you save the model structure and weight, how do you use it?

My test environment is as below.
tensorflow-gpu          2.6.0
keras                   2.6.0
Keras-Preprocessing     1.1.2

**Comment by SuryanarayanaY** [comment]
Hi @cslee99 ,

If then model have custom objects like custom layers we need to override `get_config()` method and has to serialize those objects explicitly to make them stored during model.save . Also to reload them into reloaded model we need to override `from_config()` which is a class method. Once these methods are overridden then there are 3 ways to make the custom objects saved and restored.

1. Registering custom objects (preferred) with @keras.saving.register_keras_serializable()
2. Passing custom objects directly when loading
3. Using a custom object scope

Please find more details [here](https://www.tensorflow.org/guide/keras/serialization_and_saving).

I have added the necessary code along with `get_config` and `from_config` methods below for `PositionalEmbedding` layer (subclassed layer) from `video_transformers` tutorial.

```
@keras.saving.register_keras_serializable()
class PositionalEmbedding(layers.Layer):
    def __init__(self, sequence_length, output_dim, **kwargs):
        super().__init__(**kwargs)
        self.position_embeddings = layers.Embedding(
            input_dim=sequence_length, output_dim=output_dim
        )
        self.sequence_length = sequence_length
        self.output_dim = output_dim

    def call(self, inputs):
        # The inputs are of shape: `(batch_size, frames, num_features)`
        length = tf.shape(inputs)[1]
        positions = tf.range(start=0, limit=length, delta=1)
        embedded_positions = self.position_embeddings(positions)
        return inputs + embedded_positions

    def compute_mask(self, inputs, mask=None):
        mask = tf.reduce_any(tf.cast(inputs, "bool"), axis=-1)
        return mask

    def get_config(self):
            base_config = super().get_config()
            config = {
                "position_embeddings": keras.saving.serialize_keras_object(self.position_embeddings),
                "sequence_length": self.sequence_length,
                "output_dim": self.output_dim
            }
            return {**base_config, **config}

    @classmethod
    def from_config(cls, config):
        position_embeddings_config = config.pop("position_embeddings")
        position_embeddings = keras.saving.deserialize_keras_object(position_embeddings_config)
        return cls(position_embeddings, **config)
```

You might need similar exercise for `TransformerEncoder` class also. Please have a look into attached resource and sample code and let us know if still having any queries.

Thanks!
