### ISSUE TITLE
Path issue with autogen.py

### ISSUE THREAD

**Issue by merveenoyan** [keras-team/keras-io#774]
Hello 👋 
I'm trying to add Question Answering with 🤗 Transformers and Keras example. 
I created and formatted the script but I need help with the following part in your contribution doc: 

> Run `python autogen.py add_example vision/script_name`. This will generate an ipynb and markdown rendering of your example, creating files in examples/vision/ipynb, examples/vision/md, and examples/vision/img. Do not modify any of these files by hand; only the original Python script should ever be edited manually.

In `scripts`, you can't get to examples directly with examples/vision/script_name (I also think the doc should be updated given that there are more domains), my script is under examples/nlp (shouldn't it be there?).
I get following error:

> (base) ➜  scripts git:(master) ✗ python autogen.py add_example examples/nlp/question_answering.py
> Traceback (most recent call last):
>   File "autogen.py", line 963, in <module>
>     keras_io.add_example(
>   File "autogen.py", line 217, in add_example
>     assert path.count(os.path.sep) == 1
> AssertionError

I also ran it like `python autogen.py add_example examples/nlp/question_answering.py`.
I appreciate help. 
[Here](https://github.com/merveenoyan/keras-io) is my fork of keras-io.

**Comment by ariG23498** [comment]
Hey @merveenoyan 

> (base) ➜ scripts git:(master) ✗ python autogen.py add_example examples/nlp/question_answering.py
Traceback (most recent call last):
File "autogen.py", line 963, in
keras_io.add_example(
File "autogen.py", line 217, in add_example
assert path.count(os.path.sep) == 1
AssertionError

Could you run `python autogen.py add_example nlp/question_answering`?

**Comment by fchollet** [comment]
> Could you run python autogen.py add_example nlp/question_answering?

That's what's intended. You don't specify the path to the example per se, but its name, which has two parts (`nlp/question_answering`)

**Comment by merveenoyan** [comment]
Hello, this is fixed (apparently I was trying to give question-answering.py 😅) Thanks a lot for the help!
