### ISSUE TITLE
Normalisation in timeseries_weather_forecasting.py is actually Standardisation

### ISSUE THREAD

**Issue by Kem47** [keras-team/keras-io#777]
Good afternoon. 
Just wanted to see if it's possible to correct this. I believe what is being used is Standardisation rather than Normalisation as the comments suggest. 

This quote from line 177 suggests that we'll get range between 0 and 1 which is correct for normalisation but it's not what the code does.
> Since every feature has values with varying ranges, we do normalization to confine feature values to a range of `[0, 1]`

Line 201 is where the incorrect normalisation label is used.

Thanks.

**Comment by SuryanarayanaY** [comment]
Hi @Kem47 ,

Standardisation often referred to as `z-score Normalization` is a special case of Normalization while other normalizations called as scaling normalizations . The author used `z-score normalization` technique here. Hence its not a problem I guess. 

Thanks!
