### ISSUE TITLE
tf__call() missing 1 required positional argument: 'training'

### ISSUE THREAD

**Issue by cuge1995** [keras-team/keras-io#80]
when I run the transformer example ? can any one help me ?

**Comment by fchollet** [comment]
Make sure you are running with `tf-nightly` at this time. Do you still run into the issue?

**Comment by fchollet** [comment]
We'll look into it, thanks for the report.

**Comment by NidhiRustagi** [comment]
I have also ran into the same problem while saving the model using keras.model.save_weights() fn, otherwise my code works fine during the training step

**Comment by sachinprasadhs** [comment]
I was able to run the test Colab without any error in Tensorflow version 2.13. 

Please find the below Gist and feel free to close the issue.
https://colab.research.google.com/gist/sachinprasadhs/f39b1bd6add6b48b184906c5f50f15e9/test.ipynb
