### ISSUE TITLE
InvalidArgumentError ner_transformers example

### ISSUE THREAD

**Issue by rodyoukai** [keras-team/keras-io#801]
Hi,

I try to run your example [(https://github.com/keras-team/keras-io/blob/master/examples/nlp/ner_transformers.py)](https://github.com/keras-team/keras-io/blob/master/examples/nlp/ner_transformers.py) and I get this error: 

InvalidArgumentError:  StringToNumberOp could not correctly convert string: 
	 [[{{node StringToNumber_1}}]]
	 [[IteratorGetNext]] [Op:__inference_train_function_2490]

Function call stack:
train_function

I am newbie in Keras, can you help me?

**Comment by SuryanarayanaY** [comment]
Hi @rodyoukai ,

The issue resolved now with the above PR . I have tested the example and its working fine without any error. Please refer attached [gist](https://colab.sandbox.google.com/gist/SuryanarayanaY/73a7d5d2e7035a4c26379ec6740935a1/kerasio_801-of-ner_transformers.ipynb).

Could you please check and close the issue ? Thanks!
