### ISSUE TITLE
condition [32,1,1,1], then [16,64,64,3], and else [16,64,64,3] must be broadcastable

### ISSUE THREAD

**Issue by ahtishamkhan404** [keras-team/keras-io#819]
I have issue in code. I run code after 1 epochs program terminate and also change batch size but can't work. I also search on google this error but can't find any solution.Any Expert Please Checkout my error

Full Code Link Colab Link :https://colab.research.google.com/drive/1kPDPIXliTR1Wxc8vzJ5wjgxoM7fzgnwG?usp=sharing

**Error**

InvalidArgumentError: condition [8,1,1,1], then [32,128,128,3], and else [32,128,128,3] must be broadcastable [[node adaptive_augmenter/SelectV2 (defined at :46) ]] [Op:__inference_train_function_5713]

Errors may have originated from an input operation. Input Source operations connected to node adaptive_augmenter/SelectV2: adaptive_augmenter/Less (defined at :44) IteratorGetNext (defined at :1) adaptive_augmenter/adaptive_augmenter/random_zoom/transform/ImageProjectiveTransformV3 (defined at :38)

Function call stack: train_function

**Comment by pcoet** [comment]
Hi @ahtishamkhan404, thanks for reaching out. The issue backlog is not the best place for support requests. Can you repost this to one of the forums below? That way your question will have more visibility.

* [TensorFlow forum](https://discuss.tensorflow.org/)
* [Keras mailing list](https://groups.google.com/forum/#!forum/keras-users).

Thanks!
