### ISSUE TITLE
How to predict results in Tranformers ASR example

### ISSUE THREAD

**Issue by BernardoOlisan** [keras-team/keras-io#825]
So I follow this tutorial https://github.com/keras-team/keras-io/blob/master/examples/audio/transformer_asr.py 
My question is how can I load the model and then predict it, like 
`model.predict(x)`
where x is an audio file

**Comment by pcoet** [comment]
Hi @BernardoOlisan, thanks for reaching out. The issue backlog is not the best place for support requests. Can you repost this to one of the forums below? That way your question will have more visibility.

* [TensorFlow forum](https://discuss.tensorflow.org/)
* [Keras mailing list](https://groups.google.com/forum/#!forum/keras-users).

Thanks!
