### ISSUE TITLE
Value error

### ISSUE THREAD

**Issue by rsinghal04** [keras-team/keras-io#828]
ValueError                                Traceback (most recent call last)
<ipython-input-32-771b6b012569> in <module>
     16 
     17 # Begin training the model.
---> 18 clustering_learner.fit(x=inputs, y=labels, batch_size=512, epochs=50)

~/.local/lib/python3.9/site-packages/keras/utils/traceback_utils.py in error_handler(*args, **kwargs)
     65     except Exception as e:  # pylint: disable=broad-except
     66       filtered_tb = _process_traceback_frames(e.__traceback__)
---> 67       raise e.with_traceback(filtered_tb) from None
     68     finally:
     69       del filtered_tb

~/.local/lib/python3.9/site-packages/keras/engine/data_adapter.py in _check_data_cardinality(data)
   1651                            for i in tf.nest.flatten(single_data)))
   1652     msg += "Make sure all arrays contain the same number of samples."
-> 1653     raise ValueError(msg)
   1654 
   1655 
ValueError: Data cardinality is ambiguous:
  x sizes: 8035, 7680
  y sizes: 8035
Make sure all arrays contain the same number of samples.

Any idea why this is happening?

**Comment by SuryanarayanaY** [comment]
Hi @rsinghal04 ,

I am assuming you are referring to Semantic Image Clustering example [here](https://keras.io/examples/vision/semantic_image_clustering/). 

I have executed the colab and its executing foine without any error. Please refer to attached [gist](https://colab.sandbox.google.com/gist/SuryanarayanaY/c267ebb718f332f0ecece537f64ea2b0/kerasio_828-semantic_image_clustering.ipynb).

Could you please confirm whether you have done any changes to the code. From the error log it seems the input x generating 7680 samples but corresponding labels are 8035 here. Either this has been fixed already or you might be customizing the code. Please let us know if this is still an issue for you.

Thanks!
