### ISSUE TITLE
mpnn-molecule-graph.py issue

### ISSUE THREAD

**Issue by lchen463** [keras-team/keras-io#848]
Hello, 

Thanks a lot for providing this great example. I have the following error when I run the script. I am not sure if it is induced by the tensorflow version (tensorflow_core._api.v2.version). Thank you.  Could you provide any suggestion to fix the issue? Thanks. Looking forward to hearing back. 

/var/folders/bl/m7v5vphn4sv54f454cthnrpm0000gp/T/ipykernel_70648/1708550741.py:69 call  *
        atom_features_updated, _ = self.update_step(

    ValueError: Shape must be rank 2 but is rank 1 for 'message_passing_1/gru_cell_1/MatMul_1' (op: 'MatMul') with input shapes: [64], [64,192].

**Comment by lchen463** [comment]
Just would like to mention that it works using Colab with the tensorflow._api.v2.version. I have no other issues. thanks.

**Comment by SuryanarayanaY** [comment]
Hi @lchen463 ,

I have tested the tutorial with TF2.12v and its working fine. I have also tested saving and reloading in all the formats and its also working fine.Attached [gist](https://colab.sandbox.google.com/gist/SuryanarayanaY/bc7ec4121549d92cfb30c883f5ba37e6/kerasio_848-mpnn-molecular-graphs.ipynb) for reference.

Could you please check and confirm whether the issue resolved now. Please feel free to close the issue if resolved for you also. Thanks!
