### ISSUE TITLE
tokenizer.encode.offsets throws error

### ISSUE THREAD

**Issue by tewengert** [keras-team/keras-io#85]
for idx, (start, end) in enumerate(tokenized_context.offsets):

AttributeError: 'list' object has no attribute 'offsets'

On Spyder / Python 3.7 on Windows.

Thanks for fascinating topic! Hope to get it working.

**Comment by sachinprasadhs** [comment]
Hi,

The tutorial is working as expected in google colab using TensorFlow 2.12.
Please find the below [Gist](https://gist.github.com/sachinprasadhs/fcbb6443a69682a66ef30643b88751af) for reference.
Upgrade your Tensorflow version to the latest version.
