### ISSUE TITLE
Keras Speaker Recognition - How to check exactness?

### ISSUE THREAD

**Issue by TonyB22** [keras-team/keras-io#854]
Hello !

I am using Keras Speaker Recognition to train my speakers and then find by audio file . https://keras.io/examples/audio/speaker_recognition_using_cnn/

For example I have 3 speakers

1.Tom
2.John
3.Mark

When I use some audio file that belongs to one of this speakers then it works great . But what if speaks Bob ? (that was not trained) Then it says it's Tom.

How can I check exactness ? I want it to throw error like : This speaker not found .

Please help , how to be with none trained speakers.

Thanks !

**Comment by thien290620** [comment]
Hi! 
Tell me a little about the project you are working on

**Comment by pcoet** [comment]
Hi @TonyB22, thanks for reaching out. The issue backlog is not the best place for support requests. Can you repost this to one of the forums below? That way your question will have more visibility.

* [TensorFlow forum](https://discuss.tensorflow.org/)
* [Keras mailing list](https://groups.google.com/forum/#!forum/keras-users)

Thanks!
