### ISSUE TITLE
Move `KerasTuner` tab higher up

### ISSUE THREAD

**Issue by LukeWood** [keras-team/keras-io#857]
The page linked here is great!  But it is very low down - below even Contributing to Keras!  We should move this, KerasCV, and KerasNLP higher.

<img width="896" alt="Screen Shot 2022-04-19 at 12 48 11 PM" src="https://user-images.githubusercontent.com/12191303/164083904-0d7bf9c6-bb1c-4137-a27d-27d746b929eb.png">

**Comment by innat** [comment]
@LukeWood I also think that `KerasTuner - KerasNLP - KerasCV` should be enough higher. Currently, it somewhat looks less important or not highly recommended.
