### ISSUE TITLE
Issue found in Vector-Quantized Variational Autoencoders code example

### ISSUE THREAD

**Issue by eng-amrahmed** [keras-team/keras-io#858]
The below line throws an exception
sampled = dist.sample()

I have solved the issue by installing the tensorFlow-probability version (0.12.0) but it's just a temporary fix.

//!pip install -q tensorflow-probability
!pip install  -q "tensorflow-probability==0.12.0"

**Comment by SuryanarayanaY** [comment]
Hi @eng-amrahmed ,

I can see this issue which is quiet older and it is resolved with latest versions. There might be compatibility issue at that time. 

But with latest versions of tensorflow(2.12v) and tensorflow-probability(0.21.0v) its working fine. I have tested the tutorial and attached [gist](https://colab.sandbox.google.com/gist/SuryanarayanaY/945c82ea2304e5506db1c3e6c59ecc5f/kerasio_858-of-vq_vae.ipynb#scrollTo=Qk-0bNfCMrc1) here for reference.

Please check and confirm whether we can mark this as resolved now. Thanks!
