### ISSUE TITLE
OOM while running AdaIN tutorial in Vertex AI workbench

### ISSUE THREAD

**Issue by chunxiangzheng** [keras-team/keras-io#860]
Environment: 
    TensorFlow 2.8
    4 vCPUs, 15 GB RAM
    NVIDIA Tesla T4 x 1 (GPU)

OOM happens quickly at around 10th step of the first epoch.

Error message:
---------------------------------------------------------------------------
ResourceExhaustedError                    Traceback (most recent call last)
/tmp/ipykernel_3890/1061601352.py in <module>
     18     validation_data=val_ds,
     19     validation_steps=50,
---> 20     callbacks=[TrainMonitor()],
     21 )

/opt/conda/lib/python3.7/site-packages/keras/utils/traceback_utils.py in error_handler(*args, **kwargs)
     65     except Exception as e:  # pylint: disable=broad-except
     66       filtered_tb = _process_traceback_frames(e.__traceback__)
---> 67       raise e.with_traceback(filtered_tb) from None
     68     finally:
     69       del filtered_tb

/opt/conda/lib/python3.7/site-packages/tensorflow/python/eager/execute.py in quick_execute(op_name, num_outputs, inputs, attrs, ctx, name)
     53     ctx.ensure_initialized()
     54     tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
---> 55                                         inputs, attrs, num_outputs)
     56   except core._NotOkStatusException as e:
     57     if name is not None:

ResourceExhaustedError: Graph execution error:

OOM when allocating tensor with shape[64,64,224,224] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
	 [[{{node gradient_tape/moments_3/mul_1-0-TransposeNHWCToNCHW-LayoutOptimizer}}]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info. This isn't available when running in Eager mode.
 [Op:__inference_train_function_6045]

**Comment by LukeWood** [comment]
I have submitted a message to the original author about this.  Thanks for the in depth bug report!

**Comment by LukeWood** [comment]
Update; original reporter have confirmed this to be due to GPU discrepancies and fixed it via reducing batch size.  Thanks for the error report!
