### ISSUE TITLE
Broken dataset link

### ISSUE THREAD

**Issue by egorgam** [keras-team/keras-io#875]
https://download.microsoft.com/download/3/E/1/3E1C3F21-ECDB-4869-8368-6DEBA77B919F/kagglecatsanddogs_3367a.zip

it returns 404

**Comment by sachinprasadhs** [comment]
Hi, 

Please refer the updated URL here https://download.microsoft.com/download/3/E/1/3E1C3F21-ECDB-4869-8368-6DEBA77B919F/kagglecatsanddogs_5340.zip
