### ISSUE TITLE
how do you evaluate the model?

### ISSUE THREAD

**Issue by cosmo-001** [keras-team/keras-io#892]

**Comment by SuryanarayanaY** [comment]
Hi @cosmo-001 ,

For evaluating a model first you need to have untrained data or test dataset that separated and not trained from original dataset. Once your model trained of train dataset then you can use TF built-in method `model.evaluate(x_test,y_test,batch_size=32)` for evaluating the model.

You can found a demo example at [here](https://www.tensorflow.org/guide/keras/training_with_built_in_methods).
