### ISSUE TITLE
Code Example on DropBlock2D Layer and its Regularization Impacts in Training ConvNets

### ISSUE THREAD

**Issue by Nyandwi** [keras-team/keras-io#909]
Hello,

I would like to make a code example on KerasCV DropBlock2D Layer and its regularization impact in training convolutional neural networks.

If this would be a nice thing to have on keras.io, I would be happy to work on it.

DropBlock2D Layer: https://keras.io/api/keras_cv/layers/regularization/dropblock2d/

Paper: https://arxiv.org/abs/1810.12890

**Comment by LukeWood** [comment]
@Nyandwi absolutely!  Please do, and feel free to tag me in the PR.  I am happy to review it for you.

**Comment by Nyandwi** [comment]
Thank you, @LukeWood!

I will tag you when the PR is ready.
