### ISSUE TITLE
Quickstart code is broken 

### ISSUE THREAD

**Issue by LukeWood** [keras-team/keras-io#945]
The code in:

https://keras.io/keras_cv/

does not run because Sequential models cannot take dictionary inputs.

**Comment by sachinprasadhs** [comment]
Hi, 

Quickstart seem to work fine now, here is the attached Gist [![](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.sandbox.google.com/gist/sachinprasadhs/14d30ea3aec35de5d68ef7664f41e0a8/quickstart.ipynb)
