### ISSUE TITLE
decoder in transformer example

### ISSUE THREAD

**Issue by mbfakourii** [keras-team/keras-io#965]
Hello, why is the decoder not used in [this](https://github.com/keras-team/keras-io/blob/a9b0bc50ca2b60621eb6da84c051183380d5e272/examples/timeseries/timeseries_classification_transformer.py) sample code from the transformer network? Isn't the decoder part of the transformer network?

**Comment by SuryanarayanaY** [comment]
Hi @mbfakourii ,

There are different types of transformer variants based on the training methodologies they adopted. Some are based on encoders and some based on decoders and some uses both. Normally sequence-to-sequence problems use encoder-decoder models.

Please find this [article](https://medium.com/mlearning-ai/what-are-the-different-types-of-transformers-in-ai-5085275664e8#:~:text=Understanding%20the%20biggest%20neural%20network%20in%20Deep%20Learning&text=In%20this%20article%2C%20we%20will,sequence%2Dto%2Dsequence) on different transformer architectures.

Also you can refer to [huggingface](https://huggingface.co/models) to know more on pretrained models and their architectures.

Thanks!
