### ISSUE TITLE
Code Example on Denoising Diffusion Probabilistic Models

### ISSUE THREAD

**Issue by FOLEFAC** [keras-team/keras-io#971]
Hello,
I would like to make a code example on Denoising Diffusion probabilistic models. 
Do you think it is needed on keras.io ?
Here is what it would like on kaggle: https://www.kaggle.com/code/folefac/denoising-diffusion-models-with-tensorflow

**Comment by arohi2bujji** [comment]
Hello,

Saw your implementation on Kaggle. Could you please share the notebook(Jupyter or Colab) here. The implementation is for Denoising Diffusion Probabilistic Models only right? I was in long search of it din't find any proper impelemtation. Please respond that help me a lot. Thanks in adavance.

**Comment by FOLEFAC** [comment]
Hello, you can check the colab here:
https://colab.research.google.com/drive/1T_08sIQi2QgujjBdwsViNYj-dkf6wfa0




Le ven. 28 oct. 2022 à 14:01, arohi2bujji ***@***.***> a
écrit :

**Comment by pcoet** [comment]
Hi @FOLEFAC, thanks for getting in touch. Please take a look at our [call for examples](https://github.com/keras-team/keras-io#call-for-examples), and if you think your example would be a good fit, go ahead and create a PR. Thanks!
