### ISSUE TITLE
Incorporate `isort` in CI?

### ISSUE THREAD

**Issue by sayakpaul** [keras-team/keras-io#978]
@fchollet, to help our contributors sort the imports in a nice manner, should we start using `isort`? If so, I can prepare a PR that does all the changes necessary to incorporate it in the CI. Of course, we would need to add an instruction to the README so that the contributors are aware of it. I can include that in the PR too. 

WDYT?

**Comment by pcoet** [comment]
Hi @sayakpaul, thanks for reaching out. I'm going to close this issue, as it hasn't had any activity in more than a year.
