### ISSUE TITLE
Found a broken link at "Image classification via fine-tuning with EfficientNet"

### ISSUE THREAD

**Issue by mohantym** [keras-team/keras-io#980]
Here the text location of broken link
[efficientnet_weight_update_util.py](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/applications/efficientnet_weight_update_util.py)

Could not find the official link to make a PR .

Unofficial link - 
https://github.com/MarkusRosen/keras-efficientnet-regression/blob/master/efficientnet_weight_update_util.py

**Comment by TylerADavis** [comment]
I believe the reason for this is that TF Keras was [moved out of the main TensorFlow repository](https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999). The link you're looking for is https://github.com/keras-team/keras/blob/master/keras/applications/efficientnet_weight_update_util.py

**Comment by mohantym** [comment]
Hi @TylerADavis !
Thanks for pointing me towards the correct source. created PR #1014 to fix this. 
Thank you!

**Comment by mohantym** [comment]
Closing this issue as concerned PR has been merged.
Thank you!
