### ISSUE TITLE
Error in keras example - Speaker Recognition using cnn colab file 

### ISSUE THREAD

**Issue by robotjellyzone** [keras-team/keras-io#984]
As a part of the hugging face sprint, I was trying to add the hf space & model link for this [Keras example](https://keras.io/examples/audio/speaker_recognition_using_cnn/) but got an error while executing the file. Then, I checked the original/official example [colab file](https://colab.research.google.com/github/keras-team/keras-io/blob/master/examples/audio/ipynb/speaker_recognition_using_cnn.ipynb) and tried executing this colab file but got the following similar error.

![image](https://user-images.githubusercontent.com/36916536/178933892-c9230210-8d50-4701-a9d3-f71283c0fcc2.png)

**Comment by merveenoyan** [comment]
I ran it in colab as well and I got the error. pinging @fbadine here if he has any idea 🙂

**Comment by fbadine** [comment]
I will try later today or tomorrow and will feedback

**Comment by fbadine** [comment]
The reason for the error is that the example notebook does not find any data. It assumes that the dataset should have been installed.
```
# Get the data from https://www.kaggle.com/kongaevans/speaker-recognition-dataset/download
# and save it to the 'Downloads' folder in your HOME directory
```
The reason for this is that downloading from Kaggle requires authentication and a token.
@fchollet is this ok or should the notebook download data to make it easier as an end-to-end sample however, it's out of the scope f the example?

**Comment by SuryanarayanaY** [comment]
@robotjellyzone ,

As confirmed in above comment, the dataset has to be downloaded from kaggle which may needs account and authentications token. Hence it was left to users who has to do it manually. 

There is also note available in the [tutorial](https://keras.io/examples/audio/speaker_recognition_using_cnn/) which is provided in attached snapshot below.This can make users aware of this to avoid the reported error.

<img width="757" alt="Screenshot 2023-09-05 at 5 44 31 PM" src="https://github.com/keras-team/keras-io/assets/116063290/3de4b063-b26c-4a47-988b-2cf4a9638eb3">

Can we marked it as closed as the required information available. Please check and confirm. Thanks!
