### ISSUE TITLE
Problem with "Denoising Diffusion Implicit Model" - not learning. 

### ISSUE THREAD

**Issue by Bejro** [keras-team/keras-io#989]
The model proposed in [ddim.py](https://github.com/keras-team/keras-io/tree/master/examples/generative/ddim.py) does not converge at all. It stays stable in a state that estimates the noise to be ~0 with an error of 0.7979 forever. My quick fix was to drop the AdamW optimizer and use Adam. I am just getting into diffusion models, thus, can somebody explain to me what exactly the problem is?

**Comment by sachinprasadhs** [comment]
After updating the tutorial to Keras 3, I can see the error is reduced to
` 511/511 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - i_loss: 0.6896 - n_loss: 0.2961`

Updated tutorial here https://keras.io/examples/generative/ddim/#training
